### ISSUE TITLE
A drawing/annotation/signature that is not on the last page fails to be extracted from the canvas

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#1001]
**Describe the bug**

With a form containing a drawing/annotation/signature widget that **is not on the last page**. A submission cannot be created.

In Enketo Core, the drawing binary is not created correctly. It has size 0.
In Enketo Express an exception occurs when the submit button is clicked and a submission is created.

**To Reproduce**

1. Load [drawing-bug.xml.txt](https://github.com/enketo/enketo-express/files/13167184/drawing-bug.xml.txt) ([xlsform](https://docs.google.com/spreadsheets/d/1WlWhO8D2DAffkGT9EpnVY-lMu6Tmm_M1WDLwtP7kC-A/edit?usp=sharing))
2. Draw something
3. Click Validate button
4. Observe in console that the attachment has size 0.

in Enketo Express: 

1. Load [drawing-bug.xml.txt](https://github.com/enketo/enketo-express/files/13167184/drawing-bug.xml.txt) ([xlsform](https://docs.google.com/spreadsheets/d/1WlWhO8D2DAffkGT9EpnVY-lMu6Tmm_M1WDLwtP7kC-A/edit?usp=sharing))
2. Draw something
5. Attempt to submit
6. See error in console as in the screenshot below (and failure to submit)

<img width="681" alt="Screenshot 2023-10-25 at 10 21 47 AM" src="https://github.com/enketo/enketo-express/assets/627350/e9b2bd0a-bf91-400d-a942-f93cb3c88606">

**Expected behavior**

The drawing to be extracted correctly.

**Additional context**

It may have to do with the fact that the canvas is not visible when the binary file is attempted to be created from the canvas content.

The issue was introduced in 7.2.0. https://github.com/enketo/enketo-core/commit/4f6abec01a9aae681df8dfb3ef0efc5b3dbda5e4

In Enketo Express this is a regression in 6.1.0.

**Comment by lognaturel** [comment]
@MartijnR Thanks for filing this. Fix for review at https://github.com/enketo/enketo/pull/4/commits/56697e800b6dc88683a10f176fe9de546ef4d12e

**Comment by MartijnR** [comment]
Thanks for taking this on! 

I used the opportunity to try my hand at running the new monorepo, and had no problem verifying the fix in both enketo-core and enketo-express. Very smooth so far! 👍

**Comment by lognaturel** [comment]
Woohoo, great news!
