### ISSUE TITLE
Should this repo be archived?

### ISSUE THREAD

**Issue by m5r** [enketo/enketo-core#1003]
I noticed the version `8.0.0` of `enketo-core` was released ~3 weeks ago but I couldn't find anything about it on this repo.  
After digging for a bit, I found out about the decision to merge packages into [a monorepo](https://github.com/enketo/enketo/tree/main/packages/enketo-core) and there I found the recent changes that were shipped as part of enketo-core v8.0.0

Is the monorepo now the only place we should look at for updates about enketo? If so, should this repo be archived?  
As part of the transition to the monorepo, what will happen to the remaining open issues of each package?

**Comment by garethbowen** [comment]
In addition consider updating the URLs in the package.json to the new repo

- https://github.com/enketo/enketo/blob/main/packages/enketo-core/package.json#L21
- https://github.com/enketo/enketo/blob/main/packages/enketo-core/package.json#L37

**Comment by lognaturel** [comment]
Hoping I can get to both next week. Tracked at https://github.com/enketo/enketo/issues/3
