### ISSUE TITLE
Print view does not display long text in its entirety

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#166]
The text gets cut off in printout. 

To reproduce: 

1. load test form: https://docs.google.com/spreadsheets/d/1qHG7CJyhb2xzyTMzzq03iyDeL_JXRlLsSpKEmwBICUs/edit?usp=sharing
2. print (or view print preview) 

There are two different issues:

1. Simple text input
2. Multiline text input

in two different scenarios:

a. default theme (formhub)
b. grid theme

Would be great if there was a css-only solution, but it probably needs some javascript magic.

There is a js print module that is called when a user in Enketo Express clicks the print button (and NOT the print command in the browser directly). This function is not exposed in enketo-core, but can be called be called e.g. by adding a few lines in app.js or via the console. See https://github.com/enketo/enketo-core/blob/master/src/js/print.js.

**Comment by MartijnR** [comment]
I think for multiline inputs the solution can be to tweak https://github.com/enketo/enketo-core/blob/master/src/widget/textarea/textarea.js to also expand when it is initialized (and to make sure the print CSS doesn't overwrite the height).

**Comment by MartijnR** [comment]
[print-long-text.xml.txt](https://github.com/enketo/enketo-core/files/3852548/print-long-text.xml.txt)

**Comment by pbowen-oc** [comment]
It looks like single line text is still not being displayed fully:
![OC11560- User Input](https://user-images.githubusercontent.com/25179620/71940685-394d4c80-3185-11ea-9cc5-dd72642d4d77.png)

There is also an issue with long multi-line text overlapping other text in the History, although this could be more directly related to https://github.com/OpenClinica/enketo-express-oc/issues/266 :
![OC11560 - User Input Displayed in History and overlapping the next value](https://user-images.githubusercontent.com/25179620/71940734-6ef23580-3185-11ea-8ca1-95f6ab1e2877.png)

**Comment by gushil** [comment]
@MartijnR 
I just want to make confirmation because I see different html code for printing in OpenClinica and enketo-core. Is there something I missed?

Enketo-core
<img width="1423" alt="enketo-core-latest-in-local" src="https://user-images.githubusercontent.com/60411/71992583-2c555980-3268-11ea-8909-6d892ce4798c.png">

OpenClinica
<img width="1420" alt="enketo-on-qe-runtime" src="https://user-images.githubusercontent.com/60411/71992608-3a0adf00-3268-11ea-8898-2279bdbd51ba.png">

**Comment by MartijnR** [comment]
Ah, I get it, I think! The new widget has probably not been enabled in enketo-express. I'll do this quickly and will send you a link to the commit.

**Comment by MartijnR** [comment]
See link above. I added some comments to the commit as well. Thanks for finding this difference in HTML @gushil!

**Comment by pbowen-oc** [comment]
While this is working for us within the printed history (for long queries, etc), it is not working for data entered into regular form text items:
<img width="1792" alt="text-overrap" src="https://user-images.githubusercontent.com/25179620/73381940-9e7ff380-4294-11ea-9638-8b500317c2af.png">

**Comment by MartijnR** [comment]
Looks like it is working (as the overflow is shown now), but caused a bug in the Grid theme.

* [ ] check or hear from @pbowen-oc whether this occurs with single-line inputs or with multiline input or both.
* [ ] try to reproduce in Enketo Core with the Grid theme
* [ ] PR to Enketo Core (if reproducible in Enketo Core)
* [ ] update Enketo Express after Enketo Core PR has merged
* [ ] update Enketo Express OC after Enketo Express has been updated
* [ ] do final check by running form in Enketo Express OC

**Comment by pbowen-oc** [comment]
@MartijnR - I observed it with single line text input using the Grid theme. I'm not sure about other cases.

**Comment by MartijnR** [comment]
To reproduce the print view in Enketo Core for the Grid theme:

tbc

**Comment by theywa** [comment]
I can reproduce it using enketo-express and the issue is miscalculate fixed row height when printing. I modified the print-height-adjusted script to fix the issue.
