### ISSUE TITLE
Select dropdown outline issue

### ISSUE THREAD

**Issue by Deepthi-Chand** [enketo/enketo-core#232]
Hi,
I just came accross this...
![screen shot 2014-11-11 at 6 16 55 pm](https://cloud.githubusercontent.com/assets/4657923/4993032/41402238-69cf-11e4-840e-5790920c0252.png)

As you can notice the blue highlighting that appears on the option about to be chosen is weirdly shaped (like a bucket). This seems to be specific to Chrome alone. It also happens when option is dragged (from the empty space).

**Comment by MartijnR** [comment]
Can you confirm if this issue still exists perhaps? I don't seem to be able to reproduce it.
