### ISSUE TITLE
Remove option for filepicker

### ISSUE THREAD

**Issue by Deepthi-Chand** [enketo/enketo-core#244]
Hey,
For media type questions (image or video or audio), there tis no option to remove the selected media (not reselecting the media). Is there a particular reason for the same. 

Thanks,
Deepthi Chand.

**Comment by MartijnR** [comment]
Adding a specific remove option now more of a priority (for Enketo-Express usage) when a file is loaded from storage and should be cleared.

**Comment by Deepthi-Chand** [comment]
Hey Martijn,
Are there any updates on this?

**Comment by MartijnR** [comment]
It's on the Nice-To-Have list but not planned to be implemented yet. Probably won't happen until a sponsor specifically requests it.

**Comment by MartijnR** [comment]
Looks like it is allowed/possible to set file input value programmatically to `""`.

* [ ] check IE11/Safari support
* [ ] implement

**Comment by alxndrsn** [comment]
What's the **`e`** label for?

**Comment by MartijnR** [comment]
I was trying to propose a bunch of issues to a donor/adopter (named "e"...;)) at some point in the past. I should remove this now as that never worked.

**Comment by MartijnR** [comment]
Combined with #249
