### ISSUE TITLE
File picker select, download, reset changes

### ISSUE THREAD

**Issue by Deepthi-Chand** [enketo/enketo-core#249]
Hi Martijn,
We recently pulled the latest enketo code and observed that browse option is removed for media type questions. I think it is not much intuitive if we do not have browse option . But I want to know what is your though process around it.

Also I observed for date question when appearance is month-year, in enketo form we show YYYY-MM instead of MM-YYYY. Is there any reason behind the same.

Thanks,
Deepthi Chand. A

**Comment by MartijnR** [comment]
Hi Deepthi,

You mean the little button that you normally find in native HTML file inputs, right? This was changed to look like a regular input (basically a fake file input) to allow for easier Cordova-wrapping where the file inputs are overridden using a native hook.  However, we could perhaps put a (fake) button back if that makes the UI better. I quite like that they look the same as number and text inputs, but am not sure what is best for users.

If I remember correctly, the date input formats were chosen to:

1. stay close to the ISO format used in the datatype
2. have a format that will be least confusing between different locales (e.g. in the USA 01-07-2015 is the 1st of July not the 7th of January).

Ideally we should localize these input formats, but that's not something I personally look forward to doing :P.

**Comment by MartijnR** [comment]
Ah, I realize you might be referring to the name of the _appearance_! Yes, it would be more consistent to use appearance="year-month". That was an early choice in the XForm format development. We should probably leave that now.

**Comment by MartijnR** [comment]
downloads disabled in IE11 forever

downloads disabled in MS Edge until browser bug is fixed

**Comment by MartijnR** [comment]
bcaf2e477185eaf6fa90a11f0796420f399a757f

**Comment by MartijnR** [comment]
* [ ] Edge workaround?
* [ ] max size async workaround?
* [ ] loading file from storage not showing download button

**Comment by MartijnR** [comment]
https://stackoverflow.com/questions/24007073/open-links-made-by-createobjecturl-in-ie11

**Comment by MartijnR** [comment]
the dataURI download seems to also fail for a 3.2 MB file
