### ISSUE TITLE
Media file exceeding max file size present in the serialized form-model xml

### ISSUE THREAD

**Issue by ajaydivakaran** [enketo/enketo-core#256]
Steps to reproduce:
1) Select a media file whose file-size exceeds the default 5mb.
2) Submit the submission.
3) Observe the xml sent to the server.

Actual: It contains the file-name of the media-file.
Expected: The file-name should not be present since it has violated the file size constraint.

Code observation:
Currently their is no check on file-size before updating the form-model.

Fix done on the forked repository:
Check for file-size before updating the form-model.

Would you be interested in a pull-request?

**Comment by MartijnR** [comment]
Thanks!

Yes, PR very welcome.
