### ISSUE TITLE
Edit of multiple-select question not populating values

### ISSUE THREAD

**Issue by Deepthi-Chand** [enketo/enketo-core#258]
Steps to reproduce,
Have a 'select multiple' question inside a repeat question.
Make a submission with more than one repeat blocks.

Try editing the submission
It doesn't populate selected choices from second block.

Observation:
Question nodes are created ans populated with appropriate values.
'setAllValues' function fails to set the choices selected.

pfa attached screenshot
![screen shot 2015-03-02 at 3 08 43 pm](https://cloud.githubusercontent.com/assets/4657923/6438335/0ef85c52-c0ee-11e4-8ae7-f4b01bd42ede.png)

note: (edit) looks like its a css issue since values are being sent back properly if saved without any change.

Thanks and regards:
Deepthi Chand

**Comment by MartijnR** [comment]
Thanks!

**Comment by MartijnR** [comment]
I think this is fixed. Please check if possible.
