### ISSUE TITLE
Read only select-one question is still select able on Enketo UI 

### ISSUE THREAD

**Issue by ajaydivakaran** [enketo/enketo-core#260]
The select-one choices are select able though the answer is not populated in the submitted xml file.

On the ODK app it shows the choices as disabled which gives some visual clue to the user that the answers are read-only. 
Is the Enketo UI being select able intentional?

**Comment by MartijnR** [comment]
Thanks. Not intentional.  this is a long-standing bug that somehow never got turned into a github issue. I consider it a very low priority, but it should be fixed.

**Comment by rhunwicks** [comment]
This issue is affecting us. We would be happy to try and fix it and put together a PR, but we haven't done any development on Enketo before. @MartijnR could you point us in the right direction?

**Comment by MartijnR** [comment]
PR would be welcome! This is where the fix would go: https://github.com/enketo/enketo-core/blob/master/src/widget/select-desktop/selectpicker.js (and it's sibling sass file).

**Comment by MartijnR** [comment]
Sorry I removed the link, because I mistakenly thought this referred to select question with the `minimal` appearance. Not sure if that's the case.

Wherever it occurs, the best solution is probably to add the `disabled` property to the `<input>` elements.

**Comment by MartijnR** [comment]
The notewidget is probably the place to do this: https://github.com/enketo/enketo-core/blob/master/src/widget/note/notewidget.js

**Comment by MartijnR** [comment]
Actually you'd think that built-in HTML behaviour would make inputs with a readonly attribute not-selectable. If that attribute is missing, the solution would be to add this in enketo-xslt.

**Comment by MartijnR** [comment]
Ok, last msg for today :). It might be fixable by changing [this line](https://github.com/enketo/enketo-core/blob/master/src/widget/note/notewidget.js#L53) to:

```js
$el.find( '[readonly]' ).addClass( 'ignore' ).prop('disabled', true);
```
