### ISSUE TITLE
Adding repeat section causes date-time question to loose its formatting

### ISSUE THREAD

**Issue by ajaydivakaran** [enketo/enketo-core#264]
Scenario:

1) Create a questionnaire with a repeat section along with a date-time question.
2) Enter a date-time answer
3) Add a repeat section (click on the +).
4) Observe the format of the date-time answer previously populated.

Actual:
  The date and time part gets get updated to e.g "2015-03-07T14:45"

Expected:
  The date and time part should retain its original format.

![datetimeformat](https://cloud.githubusercontent.com/assets/1208709/6798957/05742138-d238-11e4-8d63-fdb60139469d.png)

**Comment by MartijnR** [comment]
Thanks. Not able to reproduce this yet.

Can you reproduce this with http://localhost:8080/forms/index.html?xform=https://ona.io/enketo/forms/18900/form.xml (after clean clone of this repo, and running `grunt server`)

Maybe it's specific to one browser?

**Comment by MartijnR** [comment]
please re-open when you have more info that allows us to reproduce
