### ISSUE TITLE
faster clicks on touchscreen

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#271]
investigate

**Comment by MartijnR** [comment]
Radio button hover is quick. Click is slow.

Text field click takes long time to show keyboard

**Comment by MartijnR** [comment]
Check if there is difference in those two lags between a very small and a very large form.

**Comment by MartijnR** [comment]
The radio button lag could have something to with the widget (the unselect functionality). It could also have to do with setting the value in the Model when the change event fires.

**Comment by MartijnR** [comment]
@dorey was right about the DOM size affecting this for radio buttons and keyboard popup. Bad news for Enketo. Good news for dorey....

**Comment by MartijnR** [comment]
* [ ] move required msg, constraint msg, required * out of DOM?

**Comment by MartijnR** [comment]
It actually seems that the main culprit is the fakefocus event and the progress update that it triggers!

**Comment by MartijnR** [comment]
Maybe @dorey wasn't right after all.... heh heh

**Comment by MartijnR** [comment]
* [ ] very first click (when progress.updateTotal hasn't been called yet) is still slow

**Comment by MartijnR** [comment]
* [ ] test on some slow devices

**Comment by alxndrsn** [comment]
Hi Martijn, I'm seeing radio clicks on mobile take a couple of seconds to register - immediately on the click, there is a light blue background shade (using the default styles, iirc), and after a couple of seconds the darker blue concentric circles appear.  Is that the kind of response time you'd expect?  If so, any tips for making it faster?  Or is this more likely due to complicated forms and re-validation on radio check?  If it's the latter, I might look into making the UI respond before the validation/recalculation has completed.

**Comment by MartijnR** [comment]
I think it's because of either validation of the field itself, or branch/calculation updates.  I thought it was okay after the previous work in this thread. Could be a regression as well.

**Comment by alxndrsn** [comment]
Example form available at https://alxndrsn.github.io/enketo-core/forms/?xform=https://raw.githubusercontent.com/alxndrsn/enketo-client-side-transformer/master/xforms/assessment.xml

It's using client-side XSLTs but I can't think of a reason that would affect performance of radio buttons.

**Comment by MartijnR** [comment]
Thanks. I don't see the issue, but my device might be too fast.

In any case, performance investigation can be very time-intensive. I probably won't be able to look at this for a while unless a sponsor pushes me.

**Comment by alxndrsn** [comment]
No problem.

My current thinking is that it's not radio-specific, but perhaps just that in our forms we have a lot of logic attached to radio buttons.  Preventing double-touch-deselect on radios helps a lot, as does clearer feedback for the `:hover` event on touchscreen devices.

It's likely we'll get onto more performance investigation soon.  I'll share if anything interesting comes out of that.

**Comment by MartijnR** [comment]
Great. Thanks for that.

**Comment by MartijnR** [comment]
Please re-open or create a new issue if there is a non-logic-related performance issue
