### ISSUE TITLE
Images not working in demo

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#289]
## Steps to recreate

1. check out `master` branch
2. run `grunt style compile server`
3. browse to http://localhost:8005/forms/?xform=https://ona.io/enketo/forms/68781/form.xml
4. scroll down to _Choose your favorite bird_
5. observe that the images are not loaded:
<img width="641" alt="screen shot 2015-08-19 at 10 56 52" src="https://cloud.githubusercontent.com/assets/191496/9352368/16224756-4661-11e5-8d06-e3e780f2f1ad.png">

-----

In the demo forms, images aren't loaded (on my machine).  The image URLs are using the custom javarosa protocol `jr://`, e.g.: 

    <img lang="default" class="active" src="jr://images/nuthatch.png" alt="image">

I can't find any handling for the protocol in code; how is `enketo-core` expected to support it?

**Comment by MartijnR** [comment]
This is actually deliberately dealt with outside of enketo-core. This way enketo-core doesn't have to support the form [Form Discovery API](https://bitbucket.org/javarosa/javarosa/wiki/FormListAPI) (nor any other OpenRosa API), allowing this be replaced with a custom solution (as used in some hybrid mobile apps around Enketo). 

In Enketo Express (and Enketo Legacy) a lookup in the XFormsManifest (published by the OpenRosa server) is made. The manifest contains the actual media URLs. Enketo Express then converts this to a local URL to avoid cross-domain issues.
