### ISSUE TITLE
Allow configuration of different XPath implementations

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#298]
Probably not useful to most users, but would be very handy for us to allow config of the XPath evaluator, e.g. replace
```javascript
FormModel.prototype.bindJsEvaluator = function() {
    ...
}
```
> https://github.com/enketo/enketo-core/blob/master/src/js/FormModel.js#L283

with

```javascript
FormModel.prototype.bindJsEvaluator = require('custom-xpath-evaluator');
```
and then specify the default `bindJsEvaluator` implementation in a separate module.

If this is acceptable, I can submit a PR.

**Comment by alxndrsn** [comment]
An example implementation: https://github.com/alxndrsn/enketo-core/commit/e692d5651be1cb0670f9f84724c875a1453c091b

**Comment by MartijnR** [comment]
Looks cool. Yes, PR welcome. Had to wrap my head around the fact that this.xml is available in that module, but makes sense.

I hope we can just replace with your evaluator soon... Should be much faster.
