### ISSUE TITLE
Buttons are disabled by `class` instead of `attribute`

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#304]
In this code https://github.com/enketo/enketo-core/blob/master/src/js/Form.js#L460, buttons are enabled and disabled via a CSS class called `disabled`.

It seems more standard (and more in-line with [bootstrap's recommendations](http://getbootstrap.com/css/#buttons-disabled), if that's relevant), to use the `disabled` attribute on a button element.

Would this be an improvement?  Happy to submit a patch.

**Comment by MartijnR** [comment]
Yes, this would be better. I hope you'll find every nook and cranny this is used in. :)

(sorry I somehow missed this)

**Comment by alxndrsn** [comment]
haha!  I'll see what we can do :-)

**Comment by alxndrsn** [comment]
I think this may be all that's required for a fix - `disabled` can't be applied as a `prop` to a lot of elements (basically non-inputs/buttons), so use of classes there are appropriate.

**Comment by MartijnR** [comment]
ah, okay now I understand why classes were used everywhere. Thanks! Will look at PRs soon.

**Comment by MartijnR** [comment]
I think this is done. Please reopen if necessary.
