### ISSUE TITLE
Is it safe to use custom `type` values in `<bind>` elements?

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#310]
More of a query than a bug, although perhaps this could be documented.

I am writing some custom widgets and found it convenient to use a custom value for the `type` attribute in a `<bind>` element.  This seems to work, and my custom value gets passed through to the form XML as the `data-type-xml` attribute on an `<input>` element.  From inspection of `FormModel.types`, it looks like this custom type should just be treated as if it were a `string`.  This is very convenient for me, but reading the ODK XForms spec, there's no mention of custom data types.  Is this feature deliberate?  Do you think it's safe to rely on it?!

**Comment by MartijnR** [comment]
Hi Alex,

Yes, this should be safe. Unknown types are treated as string. I've added an issue to the spec. Thanks!

**Comment by alxndrsn** [comment]
Great, thanks :-)
