### ISSUE TITLE
Custom validation for custom data types

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#311]
Following on from #310, is it possible to have custom validation for a custom data type?  I was hoping this could be added using a widget, but looking at the code around https://github.com/enketo/enketo-core/blob/master/src/js/FormModel.js#L1033, that doesn't seem to be the case.

My current use case is validating a phone number field.  I'm not sure if that could be done with XPath, and ideally I'd use [libphonenumber](https://github.com/googlei18n/libphonenumber) in the browser.  My current workaround is to use my widget to hide the real `<input>`, and only copy the value to that from a fake `<input>` when my custom (JS) validation passes.

**Comment by MartijnR** [comment]
You can actually use the regular constraint validation (with the regex() function) for this. That would be the preferred solution I think (and would work in any OpenRosa-compliant client).

I haven't thought about adding the ability to extend FormModel with new types. Moving `types` to a separate module and then optionally overriding this entire module might be a decent solution.

**Comment by alxndrsn** [comment]
Sadly it's not very regexable, but I'll have a look at modifying `types` somehow...

**Comment by alxndrsn** [comment]
Turns out this would be quite a simple change.  I'm not sure if that commit/PR fits with the code style, but exposing the `types` object from `FormModel` allows very simple injection of validators for custom types: https://github.com/alxndrsn/medic-webapp/blob/647c27dbced878be32cd9ee8a2bf33e92c3726d8/static/js/enketo/widgets/phone-widget.js#L17

**Comment by alxndrsn** [comment]
I think this issue was resolved by c0efdac :smile:
