### ISSUE TITLE
document browser support

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#317]
Just having a quick look at #304, and was wondering what browsers are currently supported/targeted by `enketo-core`.  Can't see anything in https://github.com/enketo/enketo-core/blob/master/README.md; is it documented elsewhere?

**Comment by MartijnR** [comment]
Yes, I should add something. Basically, the latest version each popular modern browser is tested (though much older browsers may work fine).

**Comment by alxndrsn** [comment]
Yep, after writing this I noticed things like this CSS selecter:
```css
[disabled] {
  ...
}
```
which means we're quite up-to-date :-)
