### ISSUE TITLE
Change validation to use promises

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#320]
If field and form validation could be converted to use `Promise`s, it would make async validation possible on (custom) fields.

**Comment by MartijnR** [comment]
Not sure. Is there a use case for async validation _that would work offline_?

**Comment by alxndrsn** [comment]
A very reasonable question!

Our main use case is that we want to check certain fields for uniqueness against our DB before saving the form data.  We're using [PouchDB]() for storage, and all its APIs are asynchronous.

I think the same case would apply if using IndexDB - according to MDN, [_operations performed using IndexedDB are done asynchronously_](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API#Synchronous_and_asynchronous).

I get that this is probably not a priority for Enketo.  However, the changes weren't extensive so if this isn't something you want on the mainline, then it shouldn't be too much trouble maintaining a fork, or working out a neat way of adding an async `Form.prototype.validate`.

**Comment by MartijnR** [comment]
Ah yes, thanks. I think that's a good use case especially for hybrid apps that sync data two-ways. PR welcome (I use Q.Promise elsewhere until there is cross-browser promise support) . I hope I'm not overlooking a potential issue in enketo-express. As far as I remember, there are 3 validation scenarios:

**Comment by alxndrsn** [comment]
:+1: thanks
