### ISSUE TITLE
remove medic-mobile tags from master

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#325]
strange, those commits don't even exist in master

**Comment by MartijnR** [comment]
see https://github.com/enketo/enketo-core/commits/medic-0.4.3

**Comment by MartijnR** [comment]
removed

**Comment by alxndrsn** [comment]
sorry!

**Comment by MartijnR** [comment]
It was a weird thing and likely my fault. On github when clicking a medic tag it showed all kinds of ghost commits that were not actually present in enketo/enketo-core, and never were (but in your fork). Weird stuff. May have been a github bug as well.
