### ISSUE TITLE
Check current page for errors before moving to Next page

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#326]
As suggested in #320:

> upon page next click, block UI to check current page for errors

I don't think it will be necessary to check on Prev.

**Comment by alxndrsn** [comment]
Is there any chance of problems if earlier fields depend on input in later fields to pass validation?  Seems like a very weird/bad/incorrect form design, but perhaps others have seen valid uses?

**Comment by MartijnR** [comment]
Thanks for adding this issue.

Yes, there is definitely an issue with that. However, this would make it behave closer to ODK Collect. There have been some requests to do this (https://github.com/kobotoolbox/enketo-express/issues/300).

I guess this would be a case of the benefits outweighing the 'costs'.

If it is not necessary to have such forward-looking logic, I guess only the default (non-pages) mode would be an option. However, we could also consider adding a setting (a class on the body) that does not add the page-flip-validation.

**Comment by abbyad** [comment]
From my experience you encounter the same form design issue in Collect already. If you have validation that relies on a later field the validation for the earlier page will always fail. 

If you find yourself in this situation you can skip directly to another field in Collect, but not in Enketo.

**Comment by MartijnR** [comment]
Yes, with KoBo we were discussing to add some way to bypass like ODK Collect. But it seems to me that is a bit weird. Why have the protection and allow bypassing it? Not sure, including whether to still keep 'Go to End'.

**Comment by abbyad** [comment]
Skipping from section to section may make sense for some long forms (something like big government tax forms), however we've never had a use for it yet. For what its worth, we are hiding 'Go to End' right now.

**Comment by MartijnR** [comment]
Thanks. So you just have Back, Next and Go to Beginning. I think that makes sense when the flow is restricted. 

So maybe this:
page-validate enabled (default): Back, Next, Beginning
page-validate disabled: Back, Next, Beginning, End (maybe in future: Jump to section)

**Comment by abbyad** [comment]
We removed Go-to-Beginning for now pending more user testing, but the way you have it makes sense for general use.

**Comment by alxndrsn** [comment]
I think this can be closed.

**Comment by MartijnR** [comment]
Yes, thanks for that. Very useful addition. I asked some people to comment on the new feature, wrt to the First/Last buttons and a possible Jump-to-section. I am leaving it open for a weeks to see if they want to comment.

**Comment by ccollins0601** [comment]
Hi Martijn,
This is great. We're trying to break it now. So far so good, will let you know if we find any problems.

Regarding navigation, at OC our ideal would be to always have the Back, Next, Beginning, End, and 'Jump to Section' always show, whether the validate capabilities are disabled or not. Though this would allow you to 'cheat' and still get to the end, it looks like the form submit still re-validates and catches it.

An idea for 'Jump to Section' -  have a '3 dot' menu in upper right (e.g. https://cdn-images.xda-developers.com/direct/2/2/5/7/4/5/8/Screenshot_2013-09-14-18-25-55.jpg) that opens a drop-down list of sections. One other comment: hidden/conditional pages should appear in the jump to section only after they are shown on the form.

**Comment by alxndrsn** [comment]
> I am leaving it open for a weeks to see if they want to comment.

Can we close it now?  😉

**Comment by MartijnR** [comment]
yes! :)
