### ISSUE TITLE
Change Promises to follow ES6 Promises/A+ spec

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#327]
`Q.defer()` generates a `Deferred` object, which is [no longer recommended as part of the `Promise` spec][1].

This is currently used in a couple of places:

* [`src/js/file-manager.js`](https://github.com/enketo/enketo-core/blob/master/src/js/file-manager.js#L28)
* [`src/widget/geo/geopicker.js`](https://github.com/enketo/enketo-core/blob/master/src/widget/geo/geopicker.js#L694)

As part of this change, I also request changing the `Promise` library from [`Q`][2] to [`lie`][3], as `lie` does not provide extra functionality beyond the [Promises/A+ spec][4], so this will make it simpler to follow the spec in future.

[1]: https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Deferred
[2]: https://github.com/kriskowal/q
[3]: https://github.com/calvinmetcalf/lie
[4]: https://promisesaplus.com/

**Comment by MartijnR** [comment]
Totally agree with removing deferred usage. I think I have already removed the additional Q features I had been using previously, so swapping with lie is fine with me.

Thanks

https://github.com/kobotoolbox/enketo-express/issues/237
