### ISSUE TITLE
Only one `calculate` constraint can be applied per field

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#334]
From the code, it doesn't seem like it's currently possible to have more than one `calculate` constraint applied to the same field (i.e. https://github.com/enketo/enketo-core/blob/master/src/js/Form.js#L1992).  Is my reading correct?

I've read the [XForms spec section on `<bind>`](http://www.w3.org/TR/xforms) it's not clear to me if a field can have multiple bindings applied, and therefore multiple `calculate` constraints.

This would be useful to allow error messages differentiating why a value is not accepted, e.g. _value is not long enough_ vs _value cannot contain weird characters_.

**Comment by MartijnR** [comment]
I've always understood it's one bind only and yes multiple would not be possible with the current engine. (I believe multiple binds pointing to the same node was something (planned) to be added to XForms 2.0 - but this effort died?). 

Would be worth checking it it's (accidentally) supported in ODK Collect hough.

**Comment by alxndrsn** [comment]
As you say, there's a chance Collect supports it, but probably worth sticking to the spec.  Thanks!
