### ISSUE TITLE
How do you browse to next page programmatically?

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#338]
I'm trying to hijack the `<enter>` key, so that pressing enter in a `<input type="text">` shifts focus to the next question.

This works fine when there are multiple questions on the same page, but fails when trying to turn the page, or trigger `submit`.  This appears to be because of some strange deferred validation, stemming from this code:

> ```javascript
// validate 'required', checking value in Model (not View)
validReq = !( n.enabled && n.inputType !== 'hidden' && n.required && getDataNodeObj().getVal()[ 0 ].length === 0 );
```
> _— https://github.com/enketo/enketo-core/blob/master/src/js/Form.js#L2011_

It seems like the value of `getDataNodeObj().getVal()[ 0 ]` is the **_previous_** value of the field, whereas `n.val` is up-to-date.  Can you give any more background on what the comment means, specifically:

1. why is it important to check the Model and not the View?  And
2. how do I get the Model to update before submit/next triggers the validation?

For reference, here's my code:

```javascript
$('.enketo form').find('input').on('keydown', function(e) {
  if(e.keyCode !== 13) {
    return;
  }
  var $thisQuestion = $(this).closest('.question');

  // If there's another question on the current page, focus on that
  if($thisQuestion.attr('role') !== 'page') {
    var $nextQuestion = $thisQuestion.find('~ .question');
    if($nextQuestion.length) {
      return $nextQuestion.first().trigger('focus');
    }
  }

  // TODO here I've tried a number of things including `validate`, `change`,
  // `blur`, and also doing nothing at all.
  $thisQuestion.trigger('change');

  // If there's no question on the current page, try to go to next
  // page, or submit the form.
  var enketoContainer = $thisQuestion.closest('.enketo');
  var next = enketoContainer.find('.btn.next-page:enabled:not(.disabled)');
  if(next.length) {
    next.trigger('click');
  } else {
    enketoContainer.find('.btn.submit')).trigger('click');
  }
});
```

**Comment by MartijnR** [comment]
Hmm.

> is the previous value of the field

It shouldn't be. Value is set here: https://github.com/enketo/enketo-core/blob/master/src/js/Form.js#L2001 (the function name should perhaps be validateAndUpdate or something).

Maybe there is a bug?

What if the question is a select minimal, map-based geo input etc? I think both `blur` and `fakeblur` might be interesting but am not sure. Or maybe `valuechange.enketo` if it doesn't fire too often.

**Comment by alxndrsn** [comment]
As I'm triggering a `validate` event, I don't think line 2001 is executed: rather the validation occurs at https://github.com/enketo/enketo-core/blob/master/src/js/Form.js#L1997 - i.e. _without_ a call to `_dataNodeObj.setVal()`.

I think either:

1. I'm firing the wrong type of event; or
1. `setVal()` should be called prior to the `validate()` call on line 1997

**Comment by MartijnR** [comment]
I think I may have lost you. Pressing enter will fire the change event (I think) which sets the value in the model via validateInput. Is your handler executing before the change event is fired by the browser maybe?

**Comment by alxndrsn** [comment]
Apologies - didn't realise I'd posted that.  There is no change event fired, and I was mistakenly triggering it on the `.question` instead of on the `<input>`.  I've changed to trigger it on the `<input>`, and everything seems fine now.  I'm not sure why the change event is not triggered automatically, but perhaps because of the call to `event.preventDefault()`.

**Comment by MartijnR** [comment]
ah yes, that must be it, together with apparently getting precedence
