### ISSUE TITLE
Support npm v3

### ISSUE THREAD

**Issue by garethbowen** [enketo/enketo-core#346]
enketo-core uses sass imports to inline css using a relative path to dependencies in the node_modules folder, for example: [datepicker](https://github.com/enketo/enketo-core/blob/master/src/widget/date/datepicker-extended.scss#L1), [timepicker](https://github.com/enketo/enketo-core/blob/master/src/widget/time/timepicker-extended.scss#L1), [slider](https://github.com/enketo/enketo-core/blob/master/src/sass/core/_slider.scss).

npm changed the way dependencies are included in v3 so all non-conflicting nested dependencies are stored in the highest "node_modules" folder rather nested under the child. For example, the `boostrap-slider-basic` dependency is stored in `medic-webapp/node_modules` rather than `medic-webapp/node_modules/enketo-core/node_modules`. This means when we run the sass compile target it fails to find the required file.

Find a way to support both v2 and v3 structures.

Alternatively, publish a dist css file without imports.

Our workaround for now is to copy the three files to the expected location before running sass compile.

**Comment by MartijnR** [comment]
Thanks Gareth. I agree. Will do something shortly. I think dropping v2 support would be acceptable now.

**Comment by garethbowen** [comment]
I don't think dropping v2 support will solve the issue completely. For example if I have two libraries which both depend on enketo-core but they depend on incompatible versions, then npm v3 will put enketo-core in the sub node_modules folder so both versions can co-exist. That's a bit of an edge case but it would be a shame to drop v2 support and then hit this problem again in v3!

The cleanest solution I think is to bundle the compiled css file. That way you can use whatever npm version you like, whatever css precompiler you like, etc, etc and downstream apps will be unaffected.

**Comment by MartijnR** [comment]
I agree with that problem, but adding the dist/css files is not a good solution. E.g. in Enketo Express I replace some sass files (fonts, buttons, variables) to the match the UI around the webforms and create themes with a different color scheme. Wouldn't want to override css as it would cause too much bloat. I don't think there is much of a use case for these css files (that doesn't encourage bad practices).

Another solution would be to split off the themes in a different module (both npm and bower). I don't really like that either.

Maybe the best would be to do something fancy with the `@import` statement, e.g. make them conditional by setting a $npm-major-version variable (default: 3) or use globbing to import those 3 files regardless of where they are (that will probably be slow).

**Comment by garethbowen** [comment]
Splitting the themes off would work well for us, but the fancy imports will work just fine. Thanks.

There's also the [importer option](https://github.com/sass/node-sass#importer--v200---experimental) but it's experimental and maybe not be available in the grunt task. It's something to watch though.

**Comment by MartijnR** [comment]
Thanks. That importer option looks very interesting!

**Comment by MartijnR** [comment]
Using the importer option this can be fixed like this in the app that uses enketo-core: https://github.com/enketo/enketo-express/commit/af07c20c7cf4d671252292c0899f420f26571dae

It seemed the least bad option until @import statements themselves can be made dynamic.
