### ISSUE TITLE
Required radio buttons can be unselected

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#347]
We are currently seeing issues with radio buttons being slow to register clicks (#271).  One consequence of this is that users may touch a radio a second time before the initial click has processed.  Once both `onclick` events have been processed, the radio will have changed from unchecked -> checked -> unchecked.

Disallowing unselecting of radio buttons which are marked `required` will prevent the confusing double-touch behaviour in many of our use-cases.

**Comment by alxndrsn** [comment]
I've just noticed the `.no-unselect` class - will give it a try.

**Comment by alxndrsn** [comment]
To achieve this, I've created my own widget with:

```js
        'selector': 'input[type=radio][required]'
```

```js
    Unselectableradios.prototype._init = function() {
        $( this.element ).addClass( 'no-unselect' );
    };
```

**Comment by MartijnR** [comment]
I think your solution is good. 

I'm afraid removing unselect for required questions only in enketo-core's widget, is too inconsistent. 

It's quite strange to me that HTML doesn't provide a built-in way of unselecting radiobuttons. Enketo's solution seems like such a hack and there have been quite a few issues with this in the past.

**Comment by MartijnR** [comment]
Closing this. 

If the underlying issue of slow radio button clicks persists, that should be a separate issue.

**Comment by alxndrsn** [comment]
Depending on how you look at it, the underlying issue is actually slow hardware ;¬)

That said, I don't see the inconsistency mentioned here:

> I'm afraid removing unselect for required questions only in enketo-core's widget, is too inconsistent.

**Comment by MartijnR** [comment]
Right, and hopefully there is some scope to improve performance in Enketo's code..

The inconsistency is that all other questions can be emptied even if they are required.
