### ISSUE TITLE
Fields are calculated incorrectly on form load

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#352]
On form load, calculated field values seems to depend on the order of the `<bind>` elements in the `<model>`.

# Example form

https://raw.githubusercontent.com/alxndrsn/enketo-client-side-transformer/8d8ce09fd019500bd5a850036d1dd7ddd55619eb/xforms/order.xml

# Screenshots

These are from `medic-webapp`, but I have confirmed the bug occurs on `enketo-core`'s current `master`.  It just doesn't look as nice ;-)

## Initial load

<img width="318" alt="screen shot 2015-12-18 at 12 08 57" src="https://cloud.githubusercontent.com/assets/191496/11895574/517e3174-a580-11e5-874b-a527bb4c1216.png">

-----

## Value changed

<img width="334" alt="screen shot 2015-12-18 at 12 09 04" src="https://cloud.githubusercontent.com/assets/191496/11895562/3316e58c-a580-11e5-8d38-1ee388e0c7aa.png">

-----

## Value changed back to initial value

<img width="337" alt="screen shot 2015-12-18 at 12 09 11" src="https://cloud.githubusercontent.com/assets/191496/11895569/3ac38042-a580-11e5-8323-bca25ba8a6c6.png">

**Comment by alxndrsn** [comment]
This can be "fixed" by adding extra calls to `calcUpdate()` at https://github.com/enketo/enketo-core/blob/master/src/js/Form.js#L223.

However, this requires variable number of calls to `calcUpdate()`, depending how many levels of field interdependency are defined in the calculations.

**Comment by alxndrsn** [comment]
The obvious explanation for this is that the `dataupdate` listener has not been added to the model at the time `calcUpdate()` is called at https://github.com/enketo/enketo-core/blob/master/src/js/Form.js#L223.

**Comment by alxndrsn** [comment]
More complex example form at https://raw.githubusercontent.com/alxndrsn/enketo-client-side-transformer/0374c0b992abc7efede8b9fd296560d9044b4eb1/xforms/order.xml

**Comment by alxndrsn** [comment]
Here's a PR with a workable fix: https://github.com/enketo/enketo-core/pull/353

Not sure if it's 'correct', and will slow down form loading a bit - something we're suffering from already.

**Comment by MartijnR** [comment]
Ah interesting. Thanks for that. Let me merge the PR, wait a few days for the [this](https://github.com/enketo/enketo-core-performance-monitor) to collect some performance data, and then we can decide what to do. 

I wonder if you could argue that it is an acceptable issue... (I'm embarrassed to write that).

**Comment by alxndrsn** [comment]
:)  not sure what the argument would be - I assume we found the issue because it bit @abbyad ;-)

**Comment by MartijnR** [comment]
Performance trumps creative form design support? ;)

On Fri, Dec 18, 2015 at 8:34 AM, Alex Anderson <notifications@github.com>
wrote:

> :) not sure what the argument would be - I assume we found the issue
> because it bit @abbyad <https://github.com/abbyad> ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/enketo/enketo-core/issues/352#issuecomment-165807856>.
>

-- 
-- 
*Revolutionizing data collection since 2012.*

Enketo <https://enketo.org/>    |    LinkedIn 
<http://www.linkedin.com/company/enketo-llc>    |    GitHub 
<https://github.com/enketo>    |    Twitter <https://twitter.com/enketo>    
|    Blog <http://blog.enketo.org/>

**Comment by alxndrsn** [comment]
:)

The only problem is, how do you know when you're being too creative?!

**Comment by MartijnR** [comment]
Yeah, that's a challenge. You'd need to implement some kind of user screening perhaps to weed out the creative ones.

**Comment by MartijnR** [comment]
Well, it seems the performance impact is surprisingly negligible (unless the monitoring app is broken). Let's keep it! Thanks. :+1:

**Comment by georgepoulos** [comment]
I have problem with this update.
I have to calculate some int numbers, with default is 0.
Maybe i don't fill all the fields (maybe no appear (as form logic)
 So When the calc is updated cannot take the sum because is NAN and not the sum of the fields that I complete

**Comment by MartijnR** [comment]
Hi George,

What you're describing sounds like expected behavior and not a bug. If any argument of sum() is empty it HAS to return NaN. This is defined by the XPath specification. So the solution will likely have to be in your formulae.
