### ISSUE TITLE
Adding repeated item immediately scrolls window to top of page

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#356]
It seems like when a repeated item is added, the window immediately scrolls to the top.  This has no effect if the scroll is already at the top, but if the user has scrolled down a bit, then it can be disorientating.

Ref. medic/medic-webapp#1588

**Comment by MartijnR** [comment]
Thanks! Sounds like a bug. It shouldn't call focusOnFirstQuestion [if the page doesn't change](https://github.com/enketo/enketo-core/blob/master/src/js/Form.js#L445), but apparently it does.

**Comment by alxndrsn** [comment]
Thanks.  I'll have a look at the proper fix at some point, but for now we're getting on fine with the example in the PR.

**Comment by MartijnR** [comment]
I think this does the trick, hopefully without breaking stuff on mobile screens (the scrollIntoView() was only required for mobile if I remember correctly).

This avoids the double scrolling of the PR (first to top, then to element).

**Comment by alxndrsn** [comment]
Thanks, will give this a whirl in the next couple of days/

**Comment by alxndrsn** [comment]
:+1: works good - now no scrolling occurs at all

**Comment by MartijnR** [comment]
Great. Thanks for checking!
