### ISSUE TITLE
double constraint validation?

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#358]
https://docs.google.com/spreadsheets/d/1lzUOvNezo9HbVfJtISofZRbN0ZiI4SV8r7yLT4i7eLA/edit?usp=sharing

When enter value in first input, the constraint validation is performed twice. (Log FormModel.evaluate() to see)

@alxndrsn this could be the big performance improvement opportunity you were looking for :)

**Comment by MartijnR** [comment]
It only makes a difference for single questions, not for whole-form-validation. So not as exciting as I had hoped.

**Comment by alxndrsn** [comment]
Sounds exciting enough to me!  Will try the update in the next couple days, thanks :-)
