### ISSUE TITLE
How do I synchronise Enketo with my database

### ISSUE THREAD

**Issue by adam-je** [enketo/enketo-core#359]
I have a ready made web application running on PHP and Mysql. We are considering switching to Enketo forms, embedded or otherwise for their offline capability and quick to launch capabilities. 

I have scouted over google but cant find any direction on how to synchronise Enketo captured data to my MySQL database. There's the option to download the form as csv, convert, and import into my database but that presents obvious downsides.

I'm currently using enketo on KoboToolbox but can switch towards a self-hosted server or preferably another provider. Can the Enketo API on apidocs.enketo.org help?

I would like and will appreciate any direction given towards this.

**Comment by adam-je** [comment]
This answer states that the API on KoBoToolbox can achieve this. http://support.kobotoolbox.org/customer/portal/questions/11665485-api

API https://kc.kobotoolbox.org/api/v1/

**Comment by MartijnR** [comment]
Enketo-core is just the form engine and doesn't deal with submissions. It's dealt with in Enketo Express (nodeJS) and the old Enketo Legacy (PHP). However, Enketo Express/Legacy simply forwards submissions to an OpenRosa server such as ODK Aggregate or KoBoCAT or Ona. It doesn't store them on a server.

I'm not very familiar with the KoBo API. Best to ask them directly.

Good luck!
