### ISSUE TITLE
Update HTML5 `required` tag in line with `data-required` value

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#362]
It would be very handy for me (and also more standards-compliant?) if the [HTML5 required](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-required) attribute was added and removed from `<input>` elements in line with calculated values for `data-required`.

If this would be accepted then I will work on a patch, otherwise I'll look at updating my code which expects `required` to be present.

**Comment by MartijnR** [comment]
Does your use case involve querying the DOM for `[required]` or did you re-activate some native HTML5 behaviour? In the former case, if dynamic required functionality isn't desired, would it be an option to query for `[data-required="true()"]` instead?

**Comment by alxndrsn** [comment]
> Does your use case involve querying the DOM for `[required]`
It does indeed.

> would it be an option to query for `[data-required="true()"]` instead?
Certainly would, but if `data-required` is a complex expression, will the DOM value always be `true()`, or could it be an expression that evaluates to `true()` or `false()`?

**Comment by MartijnR** [comment]
The DOM query was an option if you didn't really need to use dynamic required expressions (there hasn't been much demand for it until last month so I imagine very few people use it). 

I'm glad you're not using HTML5's built-in behaviour though. If it works for you to only add/remove the `required` attribute when `data-required` is **currently** evaluated (only after the change event and validateAll I believe) it is fine with me. This would only make it psuedo HTML5-compliant.

I would be afraid of a solution that requires the `required` attribute to always be up to date, i.e. updating during form loading and updating questions that have a required-expression-dependency on another question when that other question gets a new value.

**Comment by alxndrsn** [comment]
For the moment, we're going with matching `[data-required="true()"]`.  We will reconsider if we start using dynamic required expressions.

**Comment by MartijnR** [comment]
Great. I'll close this for now. Just re-open when required.
