### ISSUE TITLE
Powered by Enketo requirement feedback

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#364]
I added something to the license section: https://github.com/enketo/enketo-core#license to make it obligatory to give at least something back to the project (just spreading the word).

Any feedback? Bad, good? By email or below are both great.

**Comment by pld** [comment]
Is it supposed to be 12 pixels or 12 points? Pixels are really small, but maybe that's intentional.

**Comment by MartijnR** [comment]
Thanks! Should be points.
