### ISSUE TITLE
Throw error if instanceID node is missing.

### ISSUE THREAD

**Issue by rooney** [enketo/enketo-core#372]
@theywa found that the latest enketo-core returns XML that lacks `instanceId`. We believe this is a bug.

**Comment by rooney** [comment]
also tagging @kkrumlian

**Comment by MartijnR** [comment]
I think this might be because you're using an old incompatible version of enketo-transformer. There have been some major changes recently (OC-related). Are you experiencing this in any version of enketo-express, or enketo-express-oc as well? Or after upgrading to the latest enketo-transformer (and enketo-core)?

**Comment by theywa** [comment]
Thanks MartijnR, I tried downgrade enketo-transformer version to 1.7.4 and that solved the bug( checked on participant, edit, and anonymous submit in IE and modern browser ), is it okay to not used latest enketo-transformer version when using latest enketo-core version?

**Comment by MartijnR** [comment]
No that's definitely not okay. I added a warning to the changelog. 

Can you help me reproduce the issue you have with the latest enketo-core and the latest enketo-transformer? E.g. by completing these reproducible steps:

1. Start instance of latest enketo-transformer published on npm
2. Edit enketo-core app.js to use this instance
3. Edit index.html to use non-minimized js
4. Start enketo-core with `grunt develop`
5. Open form: ......... (link to XForm)

**Comment by theywa** [comment]
Sure, following your example I found out that this bug only happen to xml file that generated from xls file. No meta and instanceId tag found on it. Here is the link of xml file (  [pp.xml](http://supadosworks.com/videos/demo-documentation/pp.xml) ) that generated from xls file ( [pp.xls](http://supadosworks.com/videos/demo-documentation/PP_CRF_v1.0.xls) ) also this is example of worked xml file ( [birdwatching.xml](http://supadosworks.com/videos/demo-documentation/birdwatching.xml) )

**Comment by MartijnR** [comment]
Ah ok, thanks for checking. So the XForm is the issue. The major change in enketo-xslt (and enketo-transformer), also means enketo no longer tries to correct this by adding a missing node. I think this is better, however, enketo should have thrown an error that this form is invalid.

**Comment by MartijnR** [comment]
to maintain backwards-compatibility the instanceID is now automatically re-added again (a temporary addition) in enketo-transformer 1.8.2
