### ISSUE TITLE
Start enketo-transformer as part of grunt develop

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#392]
Trying to test an example form, following the instructions in README:

<img width="1269" alt="screen shot 2016-12-21 at 17 54 13" src="https://cloud.githubusercontent.com/assets/191496/21398130/89101398-c7a6-11e6-8f8e-48092120fcfd.png">

When the transform page is accessed directly:

<img width="1278" alt="screen shot 2016-12-21 at 17 54 20" src="https://cloud.githubusercontent.com/assets/191496/21398129/890da36a-c7a6-11e6-8006-da38619f2ae4.png">

Is this service discontinued, or just temporarily unavailable?  Or am I just doing it wrong?

**Comment by MartijnR** [comment]
Good point.

Sorry, it's been down for a long time now. I usually fire up enketo-transformer locally on port 8085.

Let's leave this issue open to either create a new dev server for this or instruct people to do this differently. We may even be able to fire up enketo-transformer in this repo (it's already included for testing) as part of `grunt develop`.

**Comment by alxndrsn** [comment]
I think starting enketo-transformer locally is definitely the correct way forward.  I was also getting CORS rejections until I disabled it on the commandline, although this may have been handled correctly when the xslt server was up.
