### ISSUE TITLE
grunt develop does not build CSS files until there is a change

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#394]
If you have never run `grunt style` or `grunt sass`, there will be no files in `build/css` when `grunt develop` is run.  If you subsequently change one of the `.scss` source files, the `build/css` directory will appear with some `.css` files.

This was a bit surprising when starting the demo using `grunt develop` on a fresh checkout.

Would it be appropriate to include the `style` target as part of `grunt develop`?

**Comment by MartijnR** [comment]
Yes, I think so. I don't remember why I took that out. It doesn't make sense to me now.

Thanks!

**Comment by alxndrsn** [comment]
Fixed in #395
