### ISSUE TITLE
Localising form titles

### ISSUE THREAD

**Issue by garethbowen** [enketo/enketo-core#405]
Using javarosa I can translate form labels but I can't find a way to do the same for form titles (`<h:head><h:title>`). I've tried adding a `ref="jr:itext('patient:label')"` but it's ignored. I've checked the spec and couldn't find any information.

Is there a way to localise form titles? Is this by design?

**Comment by MartijnR** [comment]
Yes it's by design (sort of). We haven't come up with, or agreed on, a way to specify this in XForms. Would definitely be nice to have.
