### ISSUE TITLE
Converted integers not updated in view

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#407]
E.g. 4.4 is stored as 4 in model for type=integer, but view keeps showing 4.4 in UI.

**Comment by MartijnR** [comment]
This issue, though still present, has become somewhat theoretical since 305d9039ccd71c8a26182862c17d2034e27f0835.

It is now not possible for general users to add a decimal value in an integer input field.

So we can leave this open, as it should actually be done, but it's no longer a priority.

**Comment by alxndrsn** [comment]
Is it really worth fixing a bug that can't affect users?  I vote to close 🙂

**Comment by MartijnR** [comment]
Sorry, I missed your vote! Good one! :)
