### ISSUE TITLE
jr:choice-name changes are not immediately propagated to all 2nd-level dependencies

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#412]
Version: 4.27.2

From https://github.com/medic/medic-webapp/issues/3281

With the following form, change the textfield and see the new value immediately reflected in the choice labels below.  However, the bold-faced label below that will not update until the radio button is changed:

```xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>Test Issue 3281</h:title>
    <model>
      <instance>
        <issue-3281 delimiter="#" id="issue_3281" prefix="J1!issue_3281!" version="2017-03-24">
          <input>Default Value</input>
          <translator>clinic</translator><output/><debug/>
          <note/>
          <meta>
            <instanceID/>
          </meta>
        </issue-3281>
      </instance>
      <bind nodeset="/issue-3281/input" type="string"/>
      <bind nodeset="/issue-3281/translator" type="select1"/>
      <bind calculate="jr:choice-name( /issue-3281/translator ,' /issue-3281/translator ')" nodeset="/issue-3281/output" type="string"/>
      <bind nodeset="/issue-3281/debug" readonly="true()" type="string"/>
      <bind nodeset="/issue-3281/note" readonly="true()" type="string"/>
      <bind calculate="concat('uuid:', uuid())" nodeset="/issue-3281/meta/instanceID" readonly="true()" type="string"/>
    </model>
  </h:head>
  <h:body>
    <input ref="/issue-3281/input">
      <label>Input</label>
    </input>
    <select1 ref="/issue-3281/translator">
      <label>Translator</label>
      <item>
        <label>[<output value=" /issue-3281/input "/>] District</label>
        <value>district_hospital</value>
      </item>
      <item>
        <label>[<output value=" /issue-3281/input "/>] Health Center</label>
        <value>health_center</value>
      </item>
      <item>
        <label>[<output value=" /issue-3281/input "/>] Area</label>
        <value>clinic</value>
      </item>
    </select1>
    <input ref="/issue-3281/debug">
      <label>jr:choice-name($ {translator},'$ {translator}') = **<output value=" /issue-3281/output "/>**</label>
    </input>
    <input ref="/issue-3281/note">
      <label>The value above is stale if _Input_ is changed and you leave the textbox since it modifies the choice label for _Translator_ but not the value. The choice-name function gets updated if the choice value is modified, but should also update if the choice label changes.</label>
    </input>
  </h:body>
</h:html>
```

I'm planning to dig further into this, but figured it's worth sharing here in case it's a known issue or expected behaviour.

**Comment by MartijnR** [comment]
Thanks. It doesn't ring any bell, so it's a new one I think.

**Comment by alxndrsn** [comment]
Current hypothesis:

* the `<select1>'s item labels are changed by `outputUpdate()`
* `outputUpdate()` does not trigger `calcUpdate()` on calculations with `jr:choice-name`

**Comment by MartijnR** [comment]
Sorry, for not looking at your PR till now.  It's just that I feel such an intense dislike for the utterly non-sensible jr:choice-name() function and often would rather remove it completely ;).

However, I had a look and the issue, or at least part of it, is that calc.update() doesn't seem to find the dependency on /issue-3281/input to trigger a recalculation of /issue-3281/output.

I'll look further.

P.S. I do not understand why jr:choice-name's 2nd param has to be a string but am just ignoring that for now.

**Comment by MartijnR** [comment]
Oh, I see. The label is dynamic. So changing the output would have to trigger calculations that rely on the label that contains that output. 

Yes... sorry, that's just another reason that jr:choice-name() should not exist at all. I now even more regret having added support for this function. I don't think we should let outputs trigger re-calculations and thereby go even deeper into this choice-name mess. Sorry about that.

However, the good news is that in the latest Enketo-core it has become much easier to extend and replace almost everything including output.js. So it's possible to customize this and still use the npm-published enketo-core! 

FWIW, I think you'd have to search for all jr:choice-name() uses in the form that refer to the question of which the output is a part.

**Comment by alxndrsn** [comment]
Thanks for the comprehensive response!  I'll have a think about how we support this in the medium-term.

Are there any obvious alternatives to `jr:choice-name()`?  If so, perhaps it could be deprecated.

**Comment by MartijnR** [comment]
It might be possible to place labels into a secondary instance and use `<output>` to display them. This way they can become queryable in any XPath expression without resorting to calculating with view elements. 

The translation aspect is a bit harder. Enketo has a secret way of supporting translations in secondary instances (developed for external, but also working for internal instances). This is simply using `lang` attributes. I haven't proposed or announced this as I'm trying to take it one step at a time (my priority - by many miles - is [this](https://github.com/opendatakit/xforms-spec/issues/88) and this would come before).

Having a calculation change if the language changes means we'd need so add something quite radically new to XForms and that may be quite a hard problem to solve.

**Comment by alxndrsn** [comment]
Overriding `./output` for `require()` calls works a treat 😄.  My only concern is the risk of collisions if we ever have another relative path to a file called `output.js` in our project.

**Comment by MartijnR** [comment]
Maybe another technique could avoid that risk if you add a file in your app that calls Enketo's output.js and then changes or overrides it. The downside, is that the overridden code will still be in your compiled js (doing nothing). This is the approach we're taking in OpenClinica, e.g. [here](https://github.com/OpenClinica/enketo-express-oc/blob/master/public/js/src/module/branch.js) (note, we've called the file branch.js but we could have given it any other name like enketo-core.override.branch.js)

To avoid the issue of having significant redundant code, I have been splitting up Enketo Core modules in smaller functions (the ones we'd like to override) which would be fine to do in output.js as well, I think.

**Comment by alxndrsn** [comment]
Finally we're patching the `output.js` file in local `node_modules` at build time, so no immediate worried about collisions :slightly_smiling_face:
