### ISSUE TITLE
Move Form.getRequiredTransformerVersion to a separate module?

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#415]
It's a shame that `getRequiredTransformerVersion()` is implemented in `Form.js`, as it means enketo-core's `package.json` file is included when we browserify our code, even though this function isn't used.

If this function could be moved to its own module, then it, and `package.json`, would only be included when needed.

**Comment by MartijnR** [comment]
Ah yes, didn't think of that... Thanks. It does cause bloat. Hmmm. 

I do like the interface (and it's used by a client) compared to require('enketo-core/module'). I wonder if we could create a separate file that just stores this value (as part of `grunt develop` which extracts it from package.json) and commit this.

**Comment by alxndrsn** [comment]
> I wonder if we could create a separate file that just stores this value (as part of grunt develop which extracts it from package.json) and commit this file.

Could easily do something using [`grunt-text-replace`](https://www.npmjs.com/package/grunt-text-replace) and some placeholder string like `__ENKETO_TRANSFORMER_VERSION__`.  I'll take a look.

**Comment by MartijnR** [comment]
Writing a separate  json file (extracted from package.json) is probably preferable so that we ship a functioning module (with the Form.js entry point) without special build requirements.

Thanks for the PR. I realize you don't even use enketo-transformer!
