### ISSUE TITLE
"required" message not dynamic

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#419]
The display of the subtle "required" message  (on the top right of a question) is not dynamic. It is always shown for any required expression regardless of whether it evaluates to true or false.

Either evaluate required expression to determine whether to show this or not. Or get rid of this subtle required message entirely (and only keep the asterisk)?

<img width="657" alt="f5a4b9f4-1a13-11e7-94f1-8ec3d96a088b" src="https://cloud.githubusercontent.com/assets/627350/25393284/5343c51c-2998-11e7-9626-bfe327fa22cb.png">
<img width="688" alt="f5a01750-1a13-11e7-864e-4830fac6052c" src="https://cloud.githubusercontent.com/assets/627350/25393288/551b43b0-2998-11e7-97b8-c2c755325aa0.png">

thoughts?

**Comment by alxndrsn** [comment]
_My_ immediate thought it just get rid of it ;¬)  I'll have a proper think tomorrow, though!

**Comment by MartijnR** [comment]
Thanks! It would clean up the code nicely too...

@rowo, we introduced this decades ago, back in the old Formhub days, imitating another survey application. Do you think Ona users appreciate this feature or wouldn't miss it at all if we removed it?

**Comment by MartijnR** [comment]
Just to clarify: this issue is only about the display of the single word "required". Nothing else. Just a small UI thing.

Required is already dynamic. Nothing will change with that.

**Comment by rowo** [comment]
@MartijnR So just to understand this — hiding the "required" flag kind of hedges the situation a bit by not making the required messaging as prominent and only showing an asterisk (but the underlying issue of a required label on a non-required field will still exist) — that right?

**Comment by MartijnR** [comment]
@rowo the asterisk clue has recently become dynamic as well so we no longer have any mismatch (if we remove the subtle "required" text).

**Comment by rowo** [comment]
For Ona, I think writing out "Required" has been helpful, especially with training new users who don't have the experience of conventional web forms. Here's an [older article from 2008](http://www.lukew.com/ff/entry.asp?725) about spelling optional/required out on forms — and 2008 or earlier is about where I think some of our users are at. I can't really give you a percentage though.

**Comment by alxndrsn** [comment]
@MartijnR finally, we don't really mind what happens with the required message - happy to go with consensus.

**Comment by rowo** [comment]
@MartijnR Does the required flag still show up when a required field isn't completed? If so, I think it's okay as just the asterisk. @mberg any strong feelings here?

**Comment by abbyad** [comment]
From what I can tell the `required` label only shows when you are actively on the field, which is not so useful when navigating through form with field-lists because it shows up pretty inconsistently. Given that, we'd have no problems having it removed altogether, but as @alxndrsn said we'd be happy to go with the consensus.

**Comment by MartijnR** [comment]
Thanks for the feedback!

@rowo it is supposed show up when the field gets focus and then 1) either become persistent and turn red if the user moves to another question without entering a value or 2) fade out. See [demo](https://odk.enke.to/preview?form=http://23.21.114.69/xlsform/downloads/tmpwo_1t4pj/widgets-required.xml) (temporary link). However, it's indeed quite inconsistent at the moment (i.e. not showing up at all for a lot of question types).

**Comment by MartijnR** [comment]
Because of the various issues with it, I'll remove it for now. Definitely happy to revisit a suggestion for a clearer way of marking a required question though.
