### ISSUE TITLE
Flip to second page when first page is not relevant

### ISSUE THREAD

**Issue by garethbowen** [enketo/enketo-core#459]
When rendering a form with the first page marked not relevant the page is still rendered instead of flipping to the first relevant page. We recently upgraded from [our own fork](https://github.com/medic/enketo-core) of enketo-core circa 4.27.2 where this worked as expected to the official release version 4.39.0 so it appears to be a regression.

More information, screenshots, and a test form are available here: https://github.com/medic/medic-webapp/issues/3928

I've done some debugging and `page.updateAllActive()` is called three times. The first two times all pages are found to be active, but the third time correctly finds and filters out the inactive pages. Unfortunately `page.flipToFirst()` is called between the 2nd and 3rd `page.updateAllActive()` call so the first page is still considered active.

Rearranging the init calls in `Form.init()` so that `this.pages.init();` is after `this.branch.update();` fixes the issue but I don't know the library well enough to know if this has unintended consequences.

**Comment by MartijnR** [comment]
Thanks Gareth!

**Comment by MartijnR** [comment]
* [ ] look at why updateAllActive is called so often
* [ ] check if fix has side effects

**Comment by MartijnR** [comment]
Proposed fix didn't seem to have any side effects as far as I could see. Thanks! 👍
