### ISSUE TITLE
time format incorrect

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#463]
Should be like `<start_time>09:15:00.000+03</start_time>` instead of  `<start_time>09:15</start_time>`.

See https://opendatakit.github.io/xforms-spec/#data-types

@alxndrsn, @spatialdude, @tedrick, this could be significant for you since you are not using ODK Collect (which is currently using the correct format). It will be corrected in Enketo Core shortly.

**Comment by MartijnR** [comment]
* [ ] fix in XPath evaluator
* [ ] test time comparison in XPath evaluator
* [ ] change type in Enketo Core
* [ ] change widget in Enketo Core
* [ ] test loading old format from existing record

**Comment by tedrick** [comment]
@zhif7782 @huoyixin

**Comment by zhif7782** [comment]
@tedrick @MartijnR as far as you know, will there be any risk if we upgrade Enketo Core after the fix? Such as calculation will of time will be wrong or submitted results will be incorrect.

**Comment by MartijnR** [comment]
@zhif7782 XPath expressions using time will be tested for issue with that will hopefully be avoided (at least time comparisons). I don't think we can do any calculations with time at the moment (and that won't change). In addition, the old time format will also still have to work when an old record is loaded into a form as loading data is a much-used Enketo feature.

The main thing is probably to just be able to handle the new format in the Survey123 backend or convert it to the old format before sending it through.

**Comment by zhif7782** [comment]
Thanks @MartijnR for the explanation, will test accordingly after the issue has been fixed.

**Comment by MartijnR** [comment]
Took me a while to figure out but it turns there has never been any support for time comparisons in Enketo (and ODK Collect) (as well as calculations), so there was no need to worry about this as that remains unchanged. All times are converted to number `NaN` when comparing (just like "a" < "b" is `false` and "b" < "a" is also `false`) in any compliant XPath evaluator.
