### ISSUE TITLE
Limit file upload size on client-side

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#465]
I know there are good reasons for validating file upload size on the server-side as well as the client-side, but for usability I'd like to check the size of a file upload before saving a form.

I have a form definition for collecting images:
```
<h:html xmlns="http://www.w3.org/2002/xforms"                                                                                                                                                xmlns:h="http://www.w3.org/1999/xhtml"                                                                                                                                               xmlns:ev="http://www.w3.org/2001/xml-events"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:jr="http://openrosa.org/javarosa">
    <h:head>
        <h:title>Photos - Demo Form</h:title>

        <model>
            <instance>
                <photos id="photos">
                    <my_photo/>
                    <meta>
                        <instanceID/>
                    </meta>
                </photos>
            </instance>

            <bind nodeset="/photos/my_photo" type="binary"/>
        </model>
    </h:head>

    <h:body>
        <upload ref="/photos/my_photo" mediatype="image/*">
            <hint>Select a picture or take a photo</hint>
            <label>Image widget</label>
        </upload>
    </h:body>
</h:html>
```

# Things I've tried

## 1. Override `FormModel.prototype.types.binary.validate`

Unfortunately due to https://github.com/enketo/enketo-core/blob/master/src/js/Form-model.js#L1565-L1569, validate() is never actually called for `binary` input fields.

Even if it _were_ called, `validate()` is only passed the "value" of the field, which for an `<input type="file">` is actually the _name_ of the file.  What we would actually need access to is `that.nodes[0].files` to access e.g. `that.nodes[0].files[0].size`

## 2. Add a photo input widget

Adding custom validation in a widget:

```
    …
    Photowidget.prototype._init = function() {
        var $el = $( this.element );
        $el.on('change', function() {
            var i, tooBig, $this;

            for ( i = 0; i < this.files.length; ++i ) {
                if ( this.files[ i ].size > MAX_FILE_SIZE ) {
                    tooBig = true;
                }
            }

            if ( tooBig ) {
                …TODO mark this field as invalid so that constraint message is displayed…
            }
        });
    };
    …
    module.exports = {
        'name': pluginName,
        'selector': 'input[type=file][accept="image/*"]',
    };
    …
```
Adding a warning in HTML from the widget seems trivial, but there doesn't seem to be a simple way of invalidating the corresponding field in the model.

-----

1. Is there a simple way to impose a size constraint on a binary field in the current version of Enketo?
2. If not, do you have any suggestions for how it might be achievable?

**Comment by MartijnR** [comment]
Hi @alxndrsn,

The scaffolding to restrict file sizes is built-in but it happens at the widget level. 

1. https://github.com/enketo/enketo-core/blob/master/src/widget/file/filepicker.js#L141 calls getFileUrl()
2. The filemanager is meant to be overwritten by the application. It has an example _isTooLarge function. This is how we've done it in Enketo Express: https://github.com/kobotoolbox/enketo-express/blob/master/public/js/src/module/file-manager.js

The reason this is best done before actually populating the model (and therefore not using `validate()` is that invalid values would still be stored. The current way is similar to how a browser prevents text input into a number field.

**Comment by alxndrsn** [comment]
This is really great, thanks!

I don't think I'd need to change anything in file-manager.js _except_ for the max file size.  If there was a simple way to override just this function, then that would be interesting to me.  Currently I am using the following patch:
```
*** 159,165 ****
   * @return {Boolean}      [description]
   */
  function _isTooLarge( file ) {
!     return false;
  }

  module.exports = {
--- 159,165 ----
   * @return {Boolean}      [description]
   */
  function _isTooLarge( file ) {
!     return file && file.size > 32 * 1024;
  }

  module.exports = {
```

-----

Also, simply adding the `filepicker` widget to my app seems slightly different to the demo at https://enke.to/x/#widgets:
<img width="409" alt="screen shot 2017-11-01 at 10 49 32" src="https://user-images.githubusercontent.com/191496/32265143-d26bccd2-bef2-11e7-9aa4-9245f2b16c0a.png">
<img width="415" alt="screen shot 2017-11-01 at 10 49 17" src="https://user-images.githubusercontent.com/191496/32265144-d2a38294-bef2-11e7-87ad-7442b64d042a.png">

Am I doing something obviously wrong, or is there further custom code I should be writing?

**Comment by MartijnR** [comment]
Let's expose isTooLarge (and remove the underscore). Makes sense. I guess my thinking was the whole thing would always be replaced with one that used local storage (e.g. to load an existing record with images).

In your screenshot, it looks like there is perhaps a CSS issue. Is the filepicker css file included?

**Comment by alxndrsn** [comment]
> Let's expose isTooLarge (and remove the underscore).

Sounds great, thanks!

> In your screenshot, it looks like there is perhaps a CSS issue. Is the filepicker css file included?

Yes exactly - I remembered to add the widget, but forgot the CSS.  Thanks again 🙂

**Comment by alxndrsn** [comment]
> Let's expose isTooLarge (and remove the underscore).

Let me know if a PR would be appreciated.

**Comment by MartijnR** [comment]
Please do, since it nicely combines with https://github.com/enketo/enketo-core/issues/466. 👍 

I need to look up that albatross sketch now, as I don't know it and am intrigued!

**Comment by alxndrsn** [comment]
Any chance of getting a release soon containing this fix?

**Comment by MartijnR** [comment]
Yes, sorry. I'll try to look at PR today or tomorrow and create a release immediately after merging

**Comment by MartijnR** [comment]
Oh, I got confused. This is already merged... I will release a new version today! With or without the translation PR.

**Comment by alxndrsn** [comment]
Thanks!

**Comment by MartijnR** [comment]
As you probably noticed I actually still forgot to do it yesterday... Sorry about that. It was finally done this morning.

**Comment by alxndrsn** [comment]
Can't say I noticed :¬)
