### ISSUE TITLE
tests fail on Travis due to daylight savings time

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#474]

**Comment by alxndrsn** [comment]
`npm test` fails for me with the following:
```
HeadlessChrome 0.0.0 (Mac OS X 10.12.6) Data node XML data type is converted for XML type: time with value: 0:0 FAILED
	Expected '00:00:00.000-07:00' to equal '00:00:00.000-06:00'.
	    at UserContext.<anonymous> (/var/folders/7m/mc4v802x6z1br52hl8c_0q8w0000gn/T/1c405668eba95187bb3e2d1ace7c9a63.browserify:48760:42)
...
HeadlessChrome 0.0.0 (Mac OS X 10.12.6) Data node XML data type is converted for XML type: time with value: 00:00 FAILED
	Expected '00:00:00.000-07:00' to equal '00:00:00.000-06:00'.
	    at UserContext.<anonymous> (/var/folders/7m/mc4v802x6z1br52hl8c_0q8w0000gn/T/1c405668eba95187bb3e2d1ace7c9a63.browserify:48760:42)
.
HeadlessChrome 0.0.0 (Mac OS X 10.12.6) Data node XML data type is converted for XML type: time with value: 23:59 FAILED
	Expected '23:59:00.000-07:00' to equal '23:59:00.000-06:00'.
	    at UserContext.<anonymous> (/var/folders/7m/mc4v802x6z1br52hl8c_0q8w0000gn/T/1c405668eba95187bb3e2d1ace7c9a63.browserify:48760:42)
.
HeadlessChrome 0.0.0 (Mac OS X 10.12.6) Data node XML data type is converted for XML type: time with value: 23:59:59 FAILED
	Expected '23:59:59.000-07:00' to equal '23:59:59.000-06:00'.
	    at UserContext.<anonymous> (/var/folders/7m/mc4v802x6z1br52hl8c_0q8w0000gn/T/1c405668eba95187bb3e2d1ace7c9a63.browserify:48760:42)
```
Related?

**Comment by MartijnR** [comment]
will change timezone to Phoenix which doesn't have DST

**Comment by alxndrsn** [comment]
Is this symptomatic of a bug in the date handling?  Or just the way the tests are written?  We don't have many users in AZ ;¬)

**Comment by MartijnR** [comment]
Oh no users in AZ? Hmmm, that's a problem. I think we need to start requiring our users to move to Arizona. Haha.

They were just badly written (new) tests. :)

**Comment by alxndrsn** [comment]
I think this is fixed as demonstrated by this build: https://travis-ci.org/alxndrsn/enketo-core/builds/320215720

Do we want multiple-timezone builds for the main build?  Or should we revisit if we get timezone issues in future?

**Comment by MartijnR** [comment]
This issue was specific to daylight savings time in my timezone, I believe. We (you actually ;)), are overriding the timezone here: https://github.com/enketo/enketo-core/blob/master/test/karma.conf.js#L8 because there are a few tests that rely on this specific timezone.

(Cool to learn you can add this to Travis like that!)
