### ISSUE TITLE
Add support for truly dynamic repeat counts.

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#48]
question num_child: how many children?

If jr:noAddRemove="true()": # of repeats has to correspond to num_child. 

If num_child < num_repeats: present confirmation dialog.

We should show the confirmation dialog only if the number of children changes to a number that is less than the current number of child repeats shown and only if one of the exceeding child repeats has entered values in them that would be deleted (so this means the confirmation dialog would almost never be shown).

**Comment by MartijnR** [comment]
Going ahead with simply aggressively deleting repeats if the repeat count is updated!

**Comment by MartijnR** [comment]
Automatically disabling + and - buttons makes sense to me.

**Comment by MartijnR** [comment]
* [ ] check for regressions when there are multiple instances in model and no repeat count
* [ ] check for behaviour when repeat_count is `0` or negative.

**Comment by esmail** [comment]
@MartijnR, I'm having a weird issue with this when the `style` is set to `pages`. As soon as the `repeat_count` value is registered as 2 or greater (tested with both `count-selected(${MULTISELECT_QUESTION})` and `${INTEGER_QUESTION}`), Enketo jumps to the second repeat group's page.

**Comment by MartijnR** [comment]
Thanks!

**Comment by esmail** [comment]
@MartijnR, cool; I wasn't entirely sure this was the right repo. for this :)

Any immediate plans to work on it, by chance? We have a HHI-internal project wanting to use this for a form going out Monday (we also have a workaround using skip logic and notes).

**Comment by MartijnR** [comment]
Yes, it's perfect! It's a bit of a mess to be honest. Some enketo-core issues are only reported in enketo-express and some only in enketo-core. I need to figure out a better system...

I'll put on my list to do on Friday, but I cannot guarantee it will fixed unfortunately (70% sure that it will be).

**Comment by esmail** [comment]
Awesome. Much appreciated :)
