### ISSUE TITLE
Cannot GET /transform

### ISSUE THREAD

**Issue by KishanIos007** [enketo/enketo-core#486]
i am trying to use ``enketo-core`` in local server.. i follow the following steps:

```
1) clone the repository 
2) cd to the enketo-core-master
3) npm intsall
4) grunt --v
5) npm start

```

after doing this i am still not able to create the css and js in build folder.after some r & d i fount that it is running on port 8005 and in request url it is port number 8085 so i change the port number in app.js and again repeat the steps from 3 to 5 now css and js is created in build folder but when i click on the first url (see the image)

![capture](https://user-images.githubusercontent.com/18045135/34242015-50c54ea0-e63f-11e7-87e1-2ea6f3023514.PNG)

i get the following error in developer console (see the image)

![1](https://user-images.githubusercontent.com/18045135/34242046-7cb36bc8-e63f-11e7-9ede-59e9a1b13494.PNG)

see this also u will get better idea

![2](https://user-images.githubusercontent.com/18045135/34242094-ae29f99c-e63f-11e7-84b5-c320f87ba09f.PNG)

**UPDATE**

I remove the ``/transform`` from the url but still nothing is showing 😢 

Please can anyone help me out ?

Thanks in advance.

**Comment by KishanIos007** [comment]
@cloudchen  can u please help me

**Comment by KishanIos007** [comment]
@MartijnR  can u please help me

**Comment by alxndrsn** [comment]
@KishanIos007 You need to be running https://github.com/enketo/enketo-transformer as well

**Comment by alxndrsn** [comment]
@KishanIos007 if you clone the repo at https://github.com/enketo/enketo-transformer, and then start that server as well as enketo-core, then the demo page should work for you.

**Comment by MartijnR** [comment]
enketo-transformer has actually been added as a dev dependency so if `npm install` succeeded, you could use `grunt develop` instead of `npm start` to get it all working together without having to clone enketo-transformer. 

See detailed steps here: https://github.com/enketo/enketo-core#how-to-develop-enketo-core

**Comment by alxndrsn** [comment]
@MartijnR thanks for clarifying - very neat!  Can we add enketo-transformer to `npm start`?  Starting only `enketo-core` doesn't seem very useful.

**Comment by KishanIos007** [comment]
can i use enketo-core as node_module in ionic ?? 
actually we are try to develop ionic application so after searching we fount that ionic has not any plugin for enketo core so we are trying to use as node_module ..is it possible ?? @MartijnR  we just want to ensure that is is fissile or not ..is yes then how ?? can you explain it ?? @MartijnR  @alxndrsn  

any help from your side is appreciable.
Thanks in advance :)

**Comment by KishanIos007** [comment]
when i clone and ``npm install`` i get this



```
kishan@kishan:~/enketo/enketo-core$ sudo npm install
[sudo] password for kishan: 

> libxmljs-mt@0.18.0 install /home/kishan/enketo/enketo-core/node_modules/libxmljs-mt
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/kishan/enketo/enketo-core/node_modules/libxmljs-mt/build'
gyp ERR! System Linux 4.4.0-21-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/kishan/enketo/enketo-core/node_modules/libxmljs-mt
gyp ERR! node -v v9.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs-mt@0.18.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs-mt@0.18.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kishan/.npm/_logs/2017-12-21T18_35_30_341Z-debug.log

```

**Comment by KishanIos007** [comment]
any video tutorial from the scratch is available or not ?? i search a lot but couldn't find if :cry: 

@MartijnR

**Comment by MartijnR** [comment]
@alxndrsn Yes, that makes perfect sense to change  the npm start script! :)

@KishanIos007 yes, enketo-core is really meant to be used as an npm module. You'd have to do your transformation separately outside of Enketo core.

Sometimes npm install fails because of [libxslt](https://github.com/albanm/node-libxslt) (which is the issue your log is showing). This could either be because your OS isn't compatible, or there is a bug, or some mysterious reason that is resolved by removing `node_modules` and running npm install again. I often experience the latter as odd as it may sound.
