### ISSUE TITLE
recent jr:choicename-regression

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#490]
https://github.com/kobotoolbox/enketo-express/issues/900

**Comment by MartijnR** [comment]
add failing test first

**Comment by dlobo** [comment]
This will still give an error if we have multiple jr:choice-name in a statement:

if( /data/C1 =01, jr:choice-name( /data/C2 ,' /data/C2 '), jr:choice-name( /data/C3 ,' /data/C3 ' )

You get this error: 

FormLogicError: Could not evaluate: if( /model/instance[1]/data/C1 =01, "", jr:choice-name( /model/instance[1]/data/C3 ,' /data/C3 ' ), message: The expression is not a legal expression. (line: undefined, character: undefined)

(happy to create a new issue for this and/or investigate and see how to potentially fix it)

thanx

**Comment by MartijnR** [comment]
Thanks. There's already an issue for it here: https://github.com/enketo/enketo-core/issues/505. You may add to it there please.
