### ISSUE TITLE
jr:choice-name issue

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#505]
Won't properly parse:

`jr:choice-name( selected-at( /energy_1/light/light_equip , 1), ' /energy_1/light/light_equip ' )`

I think we should re-write the `replaceChoiceNameFn` function and use `utils.parseFunctionFromExpression` instead. I should have realized before that that would be more robust.

[energy_1.xml.txt](https://github.com/enketo/enketo-core/files/1665124/energy_1.xml.txt)

**Comment by alxndrsn** [comment]
👍 sounds good!

**Comment by dlobo** [comment]
This will still give an error if we have multiple jr:choice-name in a statement:

if( /data/C1 =01, jr:choice-name( /data/C2 ,' /data/C2 '), jr:choice-name( /data/C3 ,' /data/C3 ' )

You get this error:

FormLogicError: Could not evaluate: if( /model/instance[1]/data/C1 =01, "", jr:choice-name( /model/instance[1]/data/C3 ,' /data/C3 ' ), message: The expression is not a legal expression. (line: undefined, character: undefined)

(happy to create a new issue for this and/or investigate and see how to potentially fix it)

thanx
