### ISSUE TITLE
improve performance of getRelatedNodes

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#506]
* cache the actual nodes that contain the logic (not their parents)
* cache the filtered result if no repeat?

**Comment by alxndrsn** [comment]
Hey @MartijnR, and feel for how much difference this makes for users, and where the speed-up is seen?

**Comment by MartijnR** [comment]
Hi @alxndrsn,

I think theoretically it should make a difference for forms with a lot of logic && repeats. However, I didn't have much time for this work, and ended up doing it blindly. I think it would be good to revisit this and disable the cache in getRelatedNodes to see if there is a measurable improvement (otherwise better to remove the cache to reduce complexity, but keep some of the other changes). The automatic [performance monitor](https://github.com/enketo/enketo-core-performance-monitor) is not showing a nice impact on 1 form (bench6) only.
