### ISSUE TITLE
Show warning if select_multiple value has spaces

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#510]
Pyxform will check for this but there is always a chance that a form that builds a choice list from external data contains such options, so it needs to be checked on the client.

https://github.com/opendatakit/javarosa/issues/263#issuecomment-369019465

**Comment by theywa** [comment]
@MartijnR, Can you elaborate more about the "builds a choice list from external data contains" and "checked on the client"? and if possible steps to testing it

**Comment by MartijnR** [comment]
hi @theywa, 

Enketo Express can load external data files that will be used in the XForm (referred to with `<instance src="..."/>`) (e.g. clinicaldata.xml, users.xml as OC uses). One way they can be used is to build choice lists for select_multiple questions. Since form validators do not know the content of this external data file (which can change as well), they cannot show warnings for values that contain spaces (and are not allowed). 

In Enketo Core, the ability to load external files is not included. Instead the XML content of such external data files can be passed during form instantiation with the data property. 

I'll create a form and a form instantiation snippet you could use to develop this check (and create an automated test from).

Let's add this feature only to itemset.js (i.e. dynamic choice list generator for both internal and external data). So it won't be available to hardcoded non-dynamic choice lists (we can rely on form validators to check for those). I think the only feasible way to do this is to add the check at the time a new dynamic list is built, so that means that a warning may only pop up halfway through the data entry session.

**Comment by MartijnR** [comment]
Here is a test form (added .txt to extension just to fool github) which you can add to the /test/forms folder:

[external-data.xml.txt](https://github.com/enketo/enketo-core/files/3378387/external-data.xml.txt)

To instantiate with external data in app.js (temporarily) add:

```js
modelStr: modelStr,
        external: [ {
            id: 'mydata',
            xml: new DOMParser().parseFromString(
                `   <root>
                        <item>
                            <label>11</label>
                            <group>a</group>
                            <name>1 1</name>                        
                        </item>
                        <item>
                            <label>22</label>
                            <group>a</group>
                            <name>22</name>
                        </item>
                        <item>
                            <label>33</label>
                            <group>b</group>
                            <name>33</name>
                        </item>
                        <item>
                            <label>44 (value has spaces!)</label>
                            <group>b</group>
                            <name>4 4</name>
                        </item>
                    </root>
                `, 'text/xml' )
        } ]
```

Both select_multiple questions contain a value with a space, so both should prompt a warning. Let's make the warning helpful by mentioning the value. Eg. something like "select multiple question has an illegal value "a a" that contains a space"

**Comment by theywa** [comment]
@MartijnR - Thank you for the details instruction, it's really helpful and I'm really sorry for the late response.  I create a [PR](https://github.com/enketo/enketo-core/pull/643), also include the screenshot example.

**Comment by MartijnR** [comment]
Hi @theywa, Thanks! Here is a newer version of the test form that also tests a select minimal (with external data). So this form should show 3 errors.

[external-data-v2.xml.txt](https://github.com/enketo/enketo-core/files/3419292/external-data-v2.xml.txt)
