### ISSUE TITLE
range widget: rating appearance

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#527]
https://github.com/XLSForm/pyxform/issues/145

https://github.com/XLSForm/xlsform.github.io/issues/128

**Comment by theywa** [comment]
@MartijnR - is the new appearance(rating) will look like the one in the [doc](https://docs.opendatakit.org/form-question-types/#range-widget-with-rating)?

**Comment by MartijnR** [comment]
Yes!

**Comment by MartijnR** [comment]
test form: https://docs.google.com/spreadsheets/d/1_2ka0cRBi8M-kVyfEkNe2OTN2PwzH0tY1DO_t0iL_YE/edit?usp=sharing

**Comment by MartijnR** [comment]
Martijn's to check list:

* [ ] step of 2, 3
* [ ] readonly
* [ ] programmatically emptying (calculate outcome is '')
* [ ] clearing by user
