### ISSUE TITLE
Referring to previous repeat: calculations not triggered

### ISSUE THREAD

**Issue by enketo-issue-mover** [enketo/enketo-core#545]
_From @MartijnR on August 3, 2015 22:11_

https://docs.google.com/spreadsheets/d/13tMk8fNhTdAaarBxHotAaKLT7dqw-60gODjiExOlgts/edit?usp=sharing

_Copied from original issue: kobotoolbox/enketo-express#278_

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on August 4, 2015 19:59_

two issues:
1. repeat-position injection (due to unfortunate historic javarosa mistake), messes up the expression: `/path/to/repeat[2][position()=2]`
2. references from one repeat to another repeat do not not trigger calculation updates (they haven't for a long time).

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on August 4, 2015 20:19_

One part of this bug (incorrect calculation) is fixed: https://odk.enke.to/preview?form=http://23.21.114.69/xlsform/tmp/tmpapc1k0/indexed_repeat.xml. However, updating the calculation when the dependent node (in another repeat) updates might not be possible. Will think about a solution.

If no solution can be found that does not severely degrade performance, I think we should discourage referring to a question inside a repeat **from another question inside another repeat**.

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on September 5, 2018 18:59_

I think this is resolved. Check this.

**Comment by MartijnR** [comment]
yes it is resolved
