### ISSUE TITLE
Grid theme options with appearance columns/columns-pack break out of cell

### ISSUE THREAD

**Issue by enketo-issue-mover** [enketo/enketo-core#546]
_From @MartijnR on July 22, 2015 22:14_

<img width="253" alt="screen shot 2015-07-22 at 4 12 38 pm" src="https://cloud.githubusercontent.com/assets/627350/8838783/949565c2-308c-11e5-858b-696dcc2db7b8.png">

css `break-word: breakall` solves this but may need to reduce margins and padding to give a little more space.

Not related to ltr/rtl.

_Copied from original issue: kobotoolbox/enketo-express#265_

**Comment by MartijnR** [comment]
`word-break: break-all;` on option-label looks good, but best to combine this work after pyxform discussion on replacement for compact, horizontal etc.

**Comment by gushil** [comment]
Hi @MartijnR I'd like to trying to fix this issue.
Do you have form that I can use to reproduce this?

**Comment by MartijnR** [comment]
Welcome @gushil!

I've not always been very good at adding test forms to issues... I created one just now here: https://docs.google.com/spreadsheets/d/1-REKB15ODvKwG1tTKLRf6Vp4aEUf2hURccoNpidxG2g/edit#gid=1

A quick way to convert to XForm is using this service: http://opendatakit.org/xlsform/

Note, enketo-core doesn't automatically switch theme stylesheets, so you have to do that manually in the developer template in index.html, by commenting out the default stylesheet and uncommenting the grid stylesheets.

**Comment by MartijnR** [comment]
I changed the title of this issue to use appearance "columns" and "columns-pack" (which are the recent replacements of "horizontal" and "horizontal-compact").

**Comment by gushil** [comment]
![image](https://user-images.githubusercontent.com/60411/59408680-c5a9b380-8dde-11e9-92ac-64925ed4f91e.png)
How about this?
