### ISSUE TITLE
hover over table item no longer centered

### ISSUE THREAD

**Issue by enketo-issue-mover** [enketo/enketo-core#549]
_From @MartijnR on February 9, 2017 17:49_

<img width="331" alt="screen shot 2017-02-09 at 10 48 47 am" src="https://cloud.githubusercontent.com/assets/627350/22795861/65b42322-eeb5-11e6-8493-7e9bb362a21d.png">

_Copied from original issue: kobotoolbox/enketo-express#639_

**Comment by MartijnR** [comment]
* [ ] fix in ltr
* [ ] check rtl
