### ISSUE TITLE
fix/change Compact and horizontal-compact, etc appearances 

### ISSUE THREAD

**Issue by enketo-issue-mover** [enketo/enketo-core#552]
_From @tinok on July 20, 2018 13:20_

Using `compact` shows the choices tightly but without radio buttons: 
![image](https://user-images.githubusercontent.com/673511/43004479-e885790e-8bfd-11e8-81b1-73ee58c65fb3.png)

Using `horizontal-compact` shows the choices as expected, with radio buttons: 
![image](https://user-images.githubusercontent.com/673511/43004494-f668aa5a-8bfd-11e8-9d44-6c41c896bbf4.png)

According to the `ref-table` [documentation](http://xlsform.org/en/ref-table/) these two should have the same appearance since they are supposed to be aliases. So either they should be listed as different appearances in the table or `compact` should be fixed to work just like `horizontal-compact`.

_Copied from original issue: kobotoolbox/enketo-express#1084_

**Comment by MartijnR** [comment]
Changed to implementing the new agreed upon appearances: https://forum.opendatakit.org/t/spec-proposal-harmonize-compact-compact-n-horizontal-horizontal-compact-appearances/15565/23

**Comment by MartijnR** [comment]
* [ ] update widgets form
* [ ] update table in XLSForm.org

**Comment by MartijnR** [comment]
https://docs.google.com/spreadsheets/d/1PJVnA9HRzNPYzq3nZcrGHH4MOtavtNFnbCEpVq9mDk8/edit#gid=0

**Comment by MartijnR** [comment]
@lognaturel we're ready when you are! :) (it's only live on opendatakit.org/xlsform previews for now)

In Enketo the `columns` appearance is always 1-3 columns for now, but that will become truly automatic and dynamic (up to a larger amount of columns) in the future.
