### ISSUE TITLE
remove jQuery queries from Model

### ISSUE THREAD

**Issue by enketo-issue-mover** [enketo/enketo-core#557]
_From @MartijnR on October 31, 2016 21:1_

There are highly likely jQuery-related bugs remaining with nodeNames containing a `.` after fixing #571 

refactor:

- cloneRepeat
- determineIndex (also check for difference between this and getRepeatIndex)
- anything containing `.replace( /\./g, '\\.' )`

it would make sense for NodeSet.get to always return a single Element (not jquerified)
and to add NodeSet.getAll that always returns an array of Elements.

_Copied from original issue: kobotoolbox/enketo-express#573_

**Comment by MartijnR** [comment]
Mostly done. Remaining:

* [ ] model.$events
* [ ] removing deprecated methods that use jQuery (but warning now shown in console)
