### ISSUE TITLE
range-widget: picker appearance

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#575]
As described here: https://docs.opendatakit.org/form-question-types/#range-widgets (and [in forum](https://forum.opendatakit.org/t/a-slider-widget-for-selecting-a-value-from-a-range/2615/11))

This perhaps entirely done in enketo-xslt I think, essentially creating a _select_one + minimal_ widget.

**Comment by pbowen-oc** [comment]
@MartijnR - Can you clarify how this should work for desktop browsers? It looks like it's designed for mobile.

@theywa

**Comment by MartijnR** [comment]
I think this should look exactly like a "select_one minimal widget". So the form looks exactly the same with these two forms (with the same difference between mobile/desktop/Grid):


| type	 | name	| label | appearance | parameters
|-----|--------|------|-------------|------------
range | range_integer_widget_picker |	a label | picker | start=1;end=10;step=1

and 

| type	 | name	| label | appearance | 
|-----|--------|------|-------------|
| select_one num | int | a label | minimal |

| list_name | name | label
|-- | -- | -- |  
num | 1 | 1
num | 2 | 2
num | 3 | 3
num | 4 | 4

**Comment by theywa** [comment]
@MartijnR - Sorry for the late response, [PR](https://github.com/enketo/enketo-xslt/pull/56) ready for review.
- range picker 
![Screenshot from 2019-08-21 20-54-47](https://user-images.githubusercontent.com/13865076/63434798-58f30b00-c458-11e9-8d33-54dd6752d55a.png)
- range picker readonly
![Screenshot from 2019-08-21 20-55-10](https://user-images.githubusercontent.com/13865076/63434836-6a3c1780-c458-11e9-89e7-d84179aa5525.png)
- select minimal
![Screenshot from 2019-08-21 20-55-39](https://user-images.githubusercontent.com/13865076/63434886-7d4ee780-c458-11e9-8a91-46c974063a9b.png)
- select minimal readonly
![Screenshot from 2019-08-21 20-55-51](https://user-images.githubusercontent.com/13865076/63434909-88a21300-c458-11e9-87e5-da9cd2375c6c.png)
- validation response
![Screenshot from 2019-08-21 20-56-34](https://user-images.githubusercontent.com/13865076/63434948-9788c580-c458-11e9-96e7-7da0cd6e1742.png)

**Comment by MartijnR** [comment]
That's quick! Could you create a test (or multiple) in enketo-transformer for this please?

P.S. Feel free to just request a review from me in the GitHub interface. I think that makes it show up on https://github.com/orgs/enketo/projects/2 in the right column, and makes it easier to track.

**Comment by theywa** [comment]
What kind of test? Is something like [PR](https://github.com/enketo/enketo-transformer/pull/59) enough?

**Comment by MartijnR** [comment]
Step number 2, I mentioned above comparing the `form` output of 2 forms. So that could go in this file: https://github.com/enketo/enketo-transformer/blob/master/test/transformer.spec.js. Otherwise, we could easily break this feature in the future.

**Comment by MartijnR** [comment]
Oh sorry, didn't look at your PR. Will do so now!
