### ISSUE TITLE
Create a sketch / signature widget

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#58]
Using Canvas (and FileSystem API for offline-capable version)

**Comment by MartijnR** [comment]
Make sure this is printable. May need to keep up-to-date hidden png/jpg save of canvas as sibling of canvas that will be printed.

**Comment by MartijnR** [comment]
```xml
<instance>
  <widgets xmlns="widgets">
    <my_image/>
  </widgets>
</instance>

<bind nodeset="/widgets/my_image" type="binary"/>

<h:body>     
  <upload ref="my_image" appearance="signature" mediatype="image/*">
    <hint>Freeform touch signature capture</hint>
    <label>image widget</label>
  </upload>
</h:body>

```

**Comment by ccollins0601** [comment]
Hey @MartijnR could something like jSignature do the trick?
http://willowsystems.github.io/jSignature/#/demo/

**Comment by MartijnR** [comment]
Thanks @ccollins0601,
Yes, it would. I'm hoping we can use something much lighter though, but haven't really played around with HTML5 canvas yet.

**Comment by MartijnR** [comment]
* [ ] collect signature as blob
* [ ] draw widget (just a little larger without the baseline)
* [ ] printable
* [ ] editable within session
* [ ] editable when loading submitted record

**Comment by MartijnR** [comment]
approach:

* change input type from file to text and add data-drawing boolean attribute (or with value 'true')
* If the canvas has content it should have a filename as value for the text (alternatively, if both content and Save button was clicked). If it does not have content it should not have a value. This will take care of the "required" functionality
* filemanager looks for data-drawing and value of input and obtains dataURL from canvas. dataURL is converted to Blob (modern browsers can do toBlob() right away)
