### ISSUE TITLE
Figure out how to generate developer documentation

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#580]
Ideally from JSDoc (or other) style comments in code.

* [ ] figure out tools and format
* [ ] propose to team
* [ ] implement as test in one of Enketo's (smaller?) repos before we go all-in and add the require comments to the code everywhere.

**Comment by MartijnR** [comment]
Hi @leszek, I had a look and made a comment. I agree your approach is great. We need to figure out where to publish (automatically). Do you think gh-pages would work (and is automatable from changes in master?).

 leszekleszek on Apr 1
gh-pages could kinda work (there is option to either build automatically from repo root, or from docs directory)
 leszekleszek on Apr 1
the only problem is that Jekyll doesn't have a way of running Node which is required to build documentation
 leszekleszek on Apr 1
but still, if we build new documentation (npm run build-docs) and just commit (to master), the changes will be visible on the website
 leszekleszek on Apr 1
a working idea would be to use https://www.npmjs.com/package/publish-please to replace npm publish
 leszekleszek on Apr 1
because with that, we can do more checks and run scripts during prepublish phase
 leszekleszek on Apr 1
so we would have a documentation always in-sync with npm module of enketo-core, but not necessarily with master branch
 leszekleszek on Apr 1
but maybe it's good enough? Do we encourage usage of enketo-core and others via npm module only? Apr 1, 2019 15:06
 leszekleszek on Apr 1
I used publish-please before with npm modules and I liked it

**Comment by MartijnR** [comment]
Thanks @leszek,

Yes, we encourage the use of npm to install enketo-core.

I like the idea of using publish-please to add checks and the docs build step! Let's do it and use github pages from the docs folder, and see how it goes.

I think we can exclude the docs folder from npm install with the `files` config in package.json: https://docs.npmjs.com/files/package.json#files, or exclude it from the whole npm package with .npmignore.

**Comment by MartijnR** [comment]
Sorry, I flagged wrong person.. I meant to flag magicznyleszek

**Comment by MartijnR** [comment]
Sorry, I flagged wrong person.. I meant to flag @magicznyleszek magicznyleszek

**Comment by magicznyleszek** [comment]
@MartijnR the PR (#610) is ready for you to check it. I've added `publish-please` and module files whitelisting :) A question came up as I merged latest master: should we keep docs for all build versions? Because that's what JSDoc is generating.

**Comment by MartijnR** [comment]
Will check it out! I agree, let's just do the latest version. We can revisit when needed.
