### ISSUE TITLE
Advanced hierarchical Table of Contents

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#590]
To be considered. Like ODK Collect showing hierarchy. Also see ongoing discussion: https://forum.opendatakit.org/t/new-xform-appearance-hierarchy-visible-groups/16858/2

TL/DR; wrt groups, only show a group as a group in the hierarchy if it has a label

**Comment by MartijnR** [comment]
* [ ] create a complex test form
* [ ] see how it works in Collect
* [ ] mimic this if that looks good

**Comment by gushil** [comment]
Hi @MartijnR , need some clarification.

From what I read in discussion and by using ODK Collect to open forms mentioned in https://github.com/opendatakit/collect/pull/2764, these are targets for this issue:

- [ ] Show TOC if there is a group with a label in a form, even when the form is only one page.
- [ ] Show Nested Group as nested label.
- [ ] Group TOC item is different (ODK Collect using some 'folder' icon) with Page TOC item.
- [ ] Click Group TOC item made us jump into the right form item.

**Comment by MartijnR** [comment]
@gushil, good questions. We can deviate a little from ODK Collect because we have pages and non-pages mode (and Collect is always in pages mode).

1. Enketo will only show a ToC if a form is in pages mode (and yes, if it has one page, it will be shown). So this can remain as it is currently.
2. Groups are only shown in the ToC if they have a label (I believe this is what Collect does?). Currently, Enketo doesn't show groups at all.
3. All questions are shown (if that's the case in ODK Collect). Currently, Enketo only shows one item per page.
3. Clicking any item in the ToC (group or question) jumps to that item

Could you share your test form in this thread please? (Google Drive ideally)

**Comment by gushil** [comment]
I'm using this test form https://docs.google.com/spreadsheets/d/1UD7QxArWhgJOgC18uQANupa4TAmZbWKOEdaqSmkdN0o/edit?usp=sharing

**Comment by gushil** [comment]
It looks like groups already shown in ToC ?

![image](https://user-images.githubusercontent.com/60411/64164451-7dde7980-ce6d-11e9-96a4-8d006949acce.png)

**Comment by MartijnR** [comment]
Hi Agus,

No, it doesn't include groups in Enketo's current implementation, I think. It just extracts the first question label (or hint) from each page and shows that in the ToC.

Btw, I had a look at ODK's Collects (GoTo) implementation. How about we keep ours a bit simpler and show one long list with collapsible groups (default: collapsed) (using `<details><summary/></details>` perhaps)?

**Comment by MartijnR** [comment]
So for your test form, the TOC would look something like

This form showcases ...
* Text Widgets (collapsible)
   - Text widget
   - Multiline text widget
   - etc
* Date and time widgets (collapsible)
    - Date widget (no appear..
    - Month-year widget
   - Year widget
* Multiple choice widgets (collapsible)
    - etc

**Comment by gushil** [comment]
I think I got the idea (including collapsible list) and currently implementing it.

However I still don't understand what do you mean by using `<details><summary/></details>` ?

**Comment by MartijnR** [comment]
Hi @gushil,

That's just an idea for implementing the collapse/uncollapse feature without javascript which I like a lot. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary

We're using this for "guidance hints" as well. However, feel free to use another method if you think that's better. You may also want to have a look at how we do collapsible groups in the form.

**Comment by gushil** [comment]
Ok. Will look into that and current implementation of collapsible groups in the form.

Thanks for the suggestion.

**Comment by gushil** [comment]
PR created, waiting for review.
![image](https://user-images.githubusercontent.com/60411/64351459-8b8a2f80-d024-11e9-83d8-df51f88d9214.png)

**Comment by gushil** [comment]
![image](https://user-images.githubusercontent.com/60411/64431016-bc7d6980-d0e3-11e9-9b1d-24eed2976573.png)

**Comment by gushil** [comment]
![image](https://user-images.githubusercontent.com/60411/64431067-dcad2880-d0e3-11e9-8845-d2656e97185e.png)

**Comment by gushil** [comment]
![image](https://user-images.githubusercontent.com/60411/64431108-f2bae900-d0e3-11e9-9cea-252fb8a08817.png)

**Comment by gushil** [comment]
![image](https://user-images.githubusercontent.com/60411/64431152-0ebe8a80-d0e4-11e9-888e-4dd491000745.png)

**Comment by MartijnR** [comment]
better test form: https://docs.google.com/spreadsheets/d/1Ug-fml-jTTmM7QCBhmKUrirQCLIB9v4D_vGidAyHPH8/edit?usp=sharing
