### ISSUE TITLE
Readonly file input .addEventListener error because reset button does not exist

### ISSUE THREAD

**Issue by awemulya** [enketo/enketo-core#593]
When I Try to view submission (https://apidocs.enketo.org/v2#/post-instance-view). This Error message pops up. My Survey contains Repeated Groups.

But Edit api is working for same Instance.

![screenshot from 2019-01-09 13-24-34](https://user-images.githubusercontent.com/5351212/50884311-aadba900-1412-11e9-9938-2fed3fe27fbd.png)

This Errror in view occurs if I have repeatable Groups.

**Comment by MartijnR** [comment]
Got it. Many thanks! Looks like it happens with forms that have a file input.

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=ReadOnly2.xml

**Comment by MartijnR** [comment]
Fixed in latest `master` of Enketo Express (unreleased). Thanks again, and sleep well!

**Comment by awemulya** [comment]
Many Many Thanks Martin. What a quick Support. Thanks a lot.

**Comment by awemulya** [comment]
![screenshot from 2019-01-10 09-55-18](https://user-images.githubusercontent.com/5351212/50945664-d5cf0700-14bd-11e9-8e2a-e2ab95d7fb5c.png)

File is being previewed but the following error message is Shown Which is not required Since everithing is working well.
File (**) could not be found (leave unchanged if already submitted and you want to preserve it).

**Comment by pakkibokati2012** [comment]
@MartijnR  Thanks for intant support! Great Work!
