### ISSUE TITLE
Internet Explorer 11

### ISSUE THREAD

**Issue by microstudi** [enketo/enketo-core#594]
I have a form that has all the questions hidden by default, except the first one (which is a checkbox).
When the first checkbox is clicked, the rest of the form is shown (it is done using the internal logic capabilities on the form editor).

This works fine on most browser except Internet Explorer 11 which doesn't show the subsequent checkboxes.

![ie](https://user-images.githubusercontent.com/1401520/50978442-b7383280-14f4-11e9-9ec8-a14950372f33.png)

This is how it is supposed to be shown:

![normal](https://user-images.githubusercontent.com/1401520/50978479-cdde8980-14f4-11e9-9e93-41310b6dd668.png)

**Comment by MartijnR** [comment]
I just pushed a little fix that adds a missing IE11 polyfill. May be worth uploading your form to https://opendatakit.org/xlsform and clicking "Preview in Enketo", just in case it was not a CSS issue. That preview server is the cutting edge Enketo Express version.

**Comment by microstudi** [comment]
thanks, I've tested it, it's not that. Still waiting to get some windows machine tomorroe and I'll look if it's a CSS issue

**Comment by microstudi** [comment]
Found the line, it's this:
https://github.com/enketo/enketo-core/blob/dbc18f2cb382e58af98c90138b443ac2407dd61a/src/sass/formhub/_iefix.scss#L7

a `opacity: 0` statement. By commenting it bullets are shown again.
As I don't know why did you put it in the first place maybe @MartijnR  can tell me if I should make a pull-request to comment this line....

**Comment by MartijnR** [comment]
Sorry for the late response. I don't know why it's there. Should be safe enough to remove since only IE11 would be affected by any regressions.

**Comment by lognaturel** [comment]
IE 11 is no longer supported.
