### ISSUE TITLE
Loading image file from record in readonly view, shows error message even when file is there.

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#600]
@awemulya I moved your other issue here. Thanks!

![screenshot from 2019-01-10 09-55-18](https://user-images.githubusercontent.com/5351212/50945664-d5cf0700-14bd-11e9-8e2a-e2ab95d7fb5c.png)

Image File is being previewed but the following error message is Shown Which is not required Since everything is working well.

**Comment by awemulya** [comment]
Thank you Martin. Thank you very very much.
