### ISSUE TITLE
Checkbox checked background image not working in Chrome 72

### ISSUE THREAD

**Issue by garethbowen** [enketo/enketo-core#601]
As of Chrome 72 the check in the checkbox no longer renders. 

![screenshot from 2019-02-15 21-25-47](https://user-images.githubusercontent.com/2064938/52843924-4fff4500-3168-11e9-8283-508b964f4d17.png)

It looks like it's due to the `#` in the background-img svg url: https://stackoverflow.com/questions/30733607/svg-data-image-not-working-on-firefox-or-chrome-72 . Replacing the `#` with a `%23` makes it work as expected.

**Comment by MartijnR** [comment]
Thanks! I think you may have a different scss image-url() build function handlers than we have in Enketo Core's grunt. But it's a good opportunity to have a quick look if we can remove that entirely.

* [ ] check for FF SVG bug
* [ ] url-encode # in tickbox URL of regular non-Grid themes

**Comment by MartijnR** [comment]
The current solution no longer relies on a build task. Thanks for reporting!
