### ISSUE TITLE
The file question type isn't working for the most recent version of Enketo 

### ISSUE THREAD

**Issue by dkwamboka** [enketo/enketo-core#603]
The question type **_file_** is not working for Enketo version 1.74.3, which is what we are currently using in Ona. Uploading a file gives the error: _Cannot set property 'src' of null_
[Form1](https://enketo.ona.io/x/#cb74Zia9)

However, this seems to work on KoBo, Enketo version 1.73.0.
[Form 2](https://ee.kobotoolbox.org/x/#bQhpggBA)

Testing this on the [widgets ](https://enke.to/::widgets) form also returns the above error.

**Comment by MartijnR** [comment]
thanks @dwamboka, this issue must have been present for a while!
