### ISSUE TITLE
geowidget should not be instantiated on geopoint calculations without a form control

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#607]

**Comment by tiritea** [comment]
sample form to replicate:

[selectgps.xlsx](https://github.com/enketo/enketo-core/files/2907794/selectgps.xlsx)

will throw "TypeError: this.question is null" error

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=selectgps.xml

**Comment by MartijnR** [comment]
* [ ] check and fix same error in other widgets
