### ISSUE TITLE
Time question will throw error in Edge

### ISSUE THREAD

**Issue by huoyixin** [enketo/enketo-core#612]
**Description**
In Edge browser when we add an time question ( or some question use the timepicker). the survey will throw an error.
Edge Version: 41.16299.1004.0
EdgeHtml Version: 16.16299
**Screenshots**
![GX0%Y7% MPY_09AG802SQ3M](https://user-images.githubusercontent.com/9018127/56023558-af309e80-5d40-11e9-813f-d8db4c915f89.png)

**Test xlsx** [time.xlsx](https://github.com/enketo/enketo-core/files/3072386/time.xlsx)

**Comment by huoyixin** [comment]
This issue maybe because of the `append` function in timepicker-extended.
https://github.com/enketo/enketo-core/blob/446077bc2a81b7d392b1b0bc3626817f1dec4579/src/widget/time/timepicker-extended.js#L26

[IE and Edge doesn't support the append function](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append). It work well in IE was because we have an polyfill for it.

**Comment by MartijnR** [comment]
Ah, thanks!

**Comment by MartijnR** [comment]
@huoyixin I'm updating my Edge (which will take some time), but it looks like you are referring to Edge Mobile perhaps (though I tested Edge Mobile on Android and it doesn't have the issue either). Is anybody using Edge Mobile? It's not a browser we support (or had ever heard of actually ;)).

**Comment by huoyixin** [comment]
Sorry, that was my mistake with the MDN table. 
But this `append` function can not work in my edge `41.16299.1004.0` browser, I will check again.
Thanks for you quick response.

**Comment by MartijnR** [comment]
No worries. Thanks. Since 41.x is quite old, and the error message mostly prevents users from using it, I think it's best to leave this as is.
