### ISSUE TITLE
output in select option labels not working

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#615]
see https://forum.opendatakit.org/t/populating-multiple-choice-questions-with-dynamic-values-trouble-with-choice-filter/19289

**Comment by MartijnR** [comment]
oops, likely not a bug

**Comment by MartijnR** [comment]
Not a bug the XForm contains ${references}:

```xml
<item>
                        <itextId>static_instance-pname_list-5</itextId>
                        <name>${pname6}</name>
                        <number>6</number>
                    </item>

```

**Comment by lognaturel** [comment]
That's a cute form! I don't see anything wrong with the block you point to. It just means that the underlying value saved in the instance will be literally the string `${pname6}`. Probably not what the user expects but I think it should be supported.

I'm guessing what Enketo is unhappy with is 
```xml
<text id="static_instance-pname_list-5">
    <value><output value=" /Replication/pname6 "/></value>
</text>
```

I think we talked previously about where `output` should be allowed. This seems like an odd use of it that probably shouldn't be.

**Comment by joshuaberetta** [comment]
@lognaturel, I've seen this come up today in our community. Is the decision to leave things as is? If there is a dynamic choice label (`${something_dynamic}`) and no specified language, the choice list will have the label of literally `"${something_dynamic}"` (not resolved); if there is more than just the default language, then there will be no label but still an option.

<img width="313" alt="" src="https://user-images.githubusercontent.com/50016008/123691556-9f5ee100-d80a-11eb-8cd1-3d791ba8d397.png">
<img width="299" alt="" src="https://user-images.githubusercontent.com/50016008/123691548-9c63f080-d80a-11eb-89f7-6eb54a9e9bbe.png">
