### ISSUE TITLE
form preview from odk.enke.to not working in android (both chromium and IAB)

### ISSUE THREAD

**Issue by shankari** [enketo/enketo-core#619]
I'm trying to integrate enketo forms into a hybrid angular/ionic-based app. Woo!
Happy to link to the solution once I figure it out.
While testing, though, I found that recent android cannot load the surveys even in the default chrome browser (see video below).

When I connect and inspect, I see the following errors:

```
Uncaught TypeError: Illegal constructor
    at HTMLHtmlElement.<anonymous> (ie11-polyfill.min.js:3)
    at enketo-webform-bundle.min.js:1
    at enketo-webform-bundle.min.js:1
enketo-webform-ie11-bundle.min.js:1 Uncaught TypeError: Cannot read property 'add' of undefined
    at enketo-webform-ie11-bundle.min.js:1
    at Object.<anonymous> (enketo-webform-ie11-bundle.min.js:1)
    at Object.149.buffer (enketo-webform-ie11-bundle.min.js:1)
    at o (enketo-webform-ie11-bundle.min.js:1)
    at t (enketo-webform-ie11-bundle.min.js:1)
    at enketo-webform-ie11-bundle.min.js:1
```

Android version: 8.0.0 (emulator)
Chrome version: 58.0.3029.125
Test URL: https://odk.enke.to/preview?form=https://xlsform.opendatakit.org/downloads/ngzcr5fw/rkunsw-survey1.xml
(note that this is the standard enketo preview service)
[enketo_not_working_android_chrome.mp4.gz](https://github.com/enketo/enketo-core/files/3135644/enketo_not_working_android_chrome.mp4.gz)

**Comment by shankari** [comment]
As you can see, this seems to be related to the IE11 polyfills. If I remove them as below the form works.

```
diff --git a/build/index.html b/build/index.html
index 25a5ebc..a8ed758 100644
--- a/build/index.html
+++ b/build/index.html
@@ -26,10 +26,6 @@
         //{{globalModelStr}}

     </script>
-
-    <!-- IE11 polyfills (ignored by other browsers, and not downloaded) -->
-    <script nomodule src="https://cdn.polyfill.io/v2/polyfill.js?ua=ie%2F11.0.0&features=es2015%2Ces2016%2Ces2017%2Ces2018%2Cdefault-3.6%2CNodeList.prototype.forEach"></script>
-    <script nomodule src="./js/obscure-ie11-polyfills.js" charset="utf-8"></script>
 </head>

 <body>
@@ -91,15 +87,6 @@

     <!-- all the scripts -->
     <script id="main-script" defer module type="text/javascript" src="./js/enketo-bundle.js" charset="utf-8"></script>
-    <script nomodule>
-        document.querySelector( '#main-script' ).remove();
-        c = "./js/enketo-ie11-bundle.js";
-        var script = document.createElement( 'script' );
-        script.type = 'text/javascript';
-        script.src = './js/enketo-ie11-bundle.js';
-        document.body.appendChild( script );
-
-    </script>
 </body>

 </html>
```

**Comment by MartijnR** [comment]
> I'm trying to integrate enketo forms into a hybrid angular/ionic-based app. Woo!

Sounds very cool!

Indeed, the ie11bundle and polyfills should definitely be removed for your project. We will soon remove them from Enketo entirely when we drop support for IE11.  It is odd that a) the ie11 bundle got load and b) that you got this error, but let's not waste time on investigating that bloated IE11 build because you are using a modern browser.

As you've probably seen you can also greatly simplified the build task (no Babel, no Core-JS) when IE11 does not need to be supported.

Good luck!
