### ISSUE TITLE
focusOnFirstQuestion can hide question behind sticky header

### ISSUE THREAD

**Issue by raphaelmerx** [enketo/enketo-core#621]
#### Description
When using a "one question per page" form, and a sticky header, the call to `focusOnFirstQuestion` at https://github.com/enketo/enketo-core/blob/master/src/js/page.js#L289 can hide the question behind the header. 

#### Reproduction steps
* Use the following odk xml: https://gist.github.com/raphaelmerx/6d8740bd5fce4d2861da7f1c8e034ec8
* Including it on a page that has a header with `position: fixed`, with a height of 130px, the question appears entirely under the header.

**Comment by MartijnR** [comment]
Hi Raphael, 

If I understand correctly the sticky header is added by you outside enketo-core, right? If so, Enketo can of course not accommodate this. Sorry, if I misunderstood.

However, you could override that function without forking enketo-core. This is the technique we're using in OpenClinica, see example here: https://github.com/OpenClinica/enketo-express-oc/blob/master/public/js/src/module/page.js There is some risk that future updates in enketo-core will break your override, so you'd have to check and test every time you upgrade enketo-core.

P.S. The place to fix it might not be in that function though, depending on how large the fixed header is.
