### ISSUE TITLE
Print style of select-minimal needs tweaking

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#638]
margin-left and break-word

**Comment by pbowen-oc** [comment]
![2019-07-01 15_14_32-Window](https://user-images.githubusercontent.com/25179620/60460978-36403500-9c13-11e9-9a4a-a862c6f380ba.png)
![2019-07-01 15_15_21-Window](https://user-images.githubusercontent.com/25179620/60460979-36d8cb80-9c13-11e9-9be5-846bf24a2a7a.png)

**Comment by pbowen-oc** [comment]
[Print example.xlsx](https://github.com/enketo/enketo-core/files/3347686/Print.example.xlsx)
