### ISSUE TITLE
Large internal instances load super slow

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#676]
See https://github.com/XLSForm/pyxform/files/3065923/nigeria_wards_internal_simplified.xml.txt

Looks like I may have misdiagnosed this initially as transformer-related: https://github.com/enketo/enketo-transformer/issues/62

* [x] profile parsing XML parsing in model - super fast
* [x] make form smaller
* [ ] final test with original form

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=nigeria_wards_internal_simplified.xml

**Comment by MartijnR** [comment]
Weird thing is that all evaluations are slower. As if the model is much larger.

**Comment by MartijnR** [comment]
It's caused by the JS evaluator.

**Comment by MartijnR** [comment]
@alxndrsn this may be what you were looking for... 🥇 It might be hard to try to find remaining slow performance examples now, but I'll look.

http://localhost:8005/?xform=https://github.com/XLSForm/pyxform/files/3065923/nigeria_wards_internal_simplified.xml.txt

### loading time after XForm retrieval and transformation

`master` branch: 300,000 ms (5 minutes)
`fix/slowness` branch: with new XPath evaluator: 400ms

A modest **750x** improvement for this form. I hope this is to your satisfaction @pbowen-oc 😃 

@lognaturel fyi, this progress may interest you, as you reported this extreme performance issue with large internal instances. Looks like this is finally resolved.

:rocket: :rocket: :rocket:

**Comment by pbowen-oc** [comment]
That's fantastic! Great work!

**Comment by lognaturel** [comment]
Hurray, thank you!

**Comment by MartijnR** [comment]
closed by https://github.com/enketo/enketo-core/commit/c451d4497bb3885b28fa0bf468ec20e986184546
