### ISSUE TITLE
Predicate in repeat doesn't filter as expected

### ISSUE THREAD

**Issue by lognaturel** [enketo/enketo-core#678]
I have a repeat with a select question. I would like to make it so that each select option can only be selected once across repeat instances. I use the following predicate ([XLSForm](https://docs.google.com/spreadsheets/d/12vcVPGGewjtqnf6hmKEFiPZN_I2d36CKJ-zhbZfWbpI/edit#gid=0)):

`name = current()/. or not(selected(join(" ", /select-no-duplicates/repeat/option), name))`

All repeat instances still show all options.

The first part of the predicate would be clearer as `name = current()` but Validate fails on that. I haven't been able to try the form with just `current()` and perhaps that would work in Enketo. As far as I know, `current()` and `current()/.` should be equivalent.

**Comment by MartijnR** [comment]
Ah, thank you!! I'm guessing this is caused by the workaround for [this](https://opendatakit.github.io/xforms-spec/#a-big-deviation-with-xforms). I wish we could remove that workaround already. Enketo injects repeat positions in those absolute paths to repeat nodes (/select-no-duplicates/repeat/option), to 'correct' them. 

I seems impossible to make a distinction between a reference to ${option} within the same instance (in an old XForm that use an absolute path) and a case like yours where you want a node-set of all ${option}s in all repeat instances. Does Collect have a clever way of doing that?

* [ ] verify repeat-position-injection is the cause of this

**Comment by MartijnR** [comment]
I guess the repeat-injections could exclude references to its own path, but the bug would still exist for references to other repeat node.

**Comment by lognaturel** [comment]
> I seems impossible to make a distinction between a reference to ${option} within the same repeat instance (in an old XForm that uses an absolute path) and a case like yours where you want a node-set of all ${option}s in all repeat instances.

I'll have to look at the JavaRosa code again but I believe it's based on usage. That is, in "true" XPath, `/repeat/node` refers to the node in the first repeat when a single node is requested and to all nodes from all repeats if a nodeset is requested. In JavaRosa, `/repeat/node` refers to the node in the current repeat when a single node is requested and to all repeats if a nodeset is requested.

**Comment by MartijnR** [comment]
Ah thanks, so this is done inside the evaluator in JavaRosa and in Enketo it is done before the evaluator comes into play.

**Comment by lognaturel** [comment]
Ahh, right, you don't have control over that kind of evaluator behavior, of course.

Is there a way we can gracefully switch clients over to the true intended behavior  (first node) when an absolute path is used to represent a single node? I can't really think of a way to detect user intent so it feels like we just have to wait until old forms are unlikely to be around to switch things over.

**Comment by lognaturel** [comment]
As a side note, `current()` and `current()/.` should both work there, right?

**Comment by MartijnR** [comment]
Oh gee, I didn't quite realize the wizardry you have going on in this form. I actually think I concluded in the past that it was impossible to do what you have found a way to do (at least in Collect). 👍 

> current() and current()/. should both work there, right?

I think you are right. Of course, it appears that Enketo doesn't support that yet.. I think this is bug number 4 or 5 you demonstrated with your 1-line form... 😩 It would be nice if you could occasionally share a form that demonstrated how well Enketo works :wink: (If such forms exists of course).

**Comment by MartijnR** [comment]
> Is there a way we can gracefully switch clients over to the true intended behavior (first node) when an absolute path is used to represent a single node? I can't really think of a way to detect user intent so it feels like we just have to wait until old forms are unlikely to be around to switch things over.

Yes, I also think we'd have to wait. It might be worth putting some 'future' mode in Enketo's engine that anticipates this (but that probably can only be used in custom mini-ecosystems).

**Comment by lognaturel** [comment]
> I actually think I concluded in the past that it was impossible to do what you have found a way to do

Don't worry, @yanokwa also said it was impossible. 😂

> I think this is bug number 4 or 5 you demonstrated with your 1-line form... 😩 It would be nice if you could occasionally share a form that demonstrated how well Enketo works 😉

😅 It works great, I promise. I only get called in to write impossible forms.

I really wish we had a better way of sharing out these kinds of recipes. I have so many that I think are really cool. I'll be sure to point out others that run into Enketo trouble when I see it.

**Comment by MartijnR** [comment]
> I only get called in to write impossible forms.

Haha. Well, you're really good at it.

I can sigh a little bit of a relief, because the [easy workaround](https://docs.google.com/spreadsheets/d/1QtVC6TQ1Z2YWRARnUY66UBy-HKUf-zYTS60Y3K3aKfw/edit?usp=sharing) by bringing the repeat node ref outside the repeat, is working after all (I thought it wasn't but made a mistake in the calculation expression).  (live: https://odk.enke.to/preview?form=https://xlsform.opendatakit.org/downloads/5625gt__/select-no-duplicates-workaround.xml)

> I really wish we had a better way of sharing out these kinds of recipes. 

Yes, that would be a great thing to publish somewhere for those that wish to explore the nooks and crannies of XPath.

**Comment by lognaturel** [comment]
> Haha. Well, you're really good at it.

😻

> Yes, that would be a great thing to publish somewhere for those that wish to explore the nooks and crannies of XPath.

Any ideas on how to make them usable? I put most of my test forms at https://drive.google.com/drive/u/1/folders/0B3xDc_jQAXPwUjdyQ3JPWWRSbzg but without any kind of indexing scheme or metadata it's not particularly useful to others.

**Comment by MartijnR** [comment]
tests (manually add `odk:generated-by` attribute):

* [ ] localhost:8005/?xform=repeatCount.xml
* [ ] a version of the above form

**Comment by MartijnR** [comment]
@lognaturel Maybe the (future) website could have some advanced XPath tutorial section that lists these forms with a description.

**Comment by MartijnR** [comment]
changed to `odk:xforms-version`. We can just do a presence test or >= "1.0.0"

https://github.com/XLSForm/pyxform/pull/430

**Comment by MartijnR** [comment]
This requires copying model attributes in enketo-transformer unfortunately
