### ISSUE TITLE
How can I use the template

### ISSUE THREAD

**Issue by hussain1368** [enketo/enketo-core#691]
Hi,
I want to integrate the enketo core in my app. I have set up the enketo-transformer and enketo-core and they both work fine. But I don't know what's the right way to add the styles or theme. The documentation is very short and I couldn't learn so much. Should I import all the files in the sass folder? If so is there any order to observe? Is these sass files enough or I need to add additional css?
I appreciate if you can help me with this.
Thank you

**Comment by MartijnR** [comment]
Hi, I am on holiday, so I cannot respond in detail atm, but you need to add css for the ui around the form that your app takes care of, e.g. modal dialogs, buttons. You may also want to replace the icons. 

Have a look at enketo-express, as it is a good example for what you are doing. Good luck, and let me know in a week or so where you are still stuck. Any recommendations or a PR, at that time for documentation improvements will be very welcome too!
