### ISSUE TITLE
Performance of select_..._from_file

### ISSUE THREAD

**Issue by hussain1368** [enketo/enketo-core#692]
Is there any way I can have a drop-down or radio button list for select_one_external?
Currently I am getting a simple text box in which I have to type the code of selected item.
Thank you

**Comment by MartijnR** [comment]
Hi, 

No you cannot. Select_one_external is not part of the ODK spec, and will never be supported in Enketo. 

I recommend trying to see if select_one_from_file works for you (which is in the spec).

**Comment by hussain1368** [comment]
Thank you,
I used select_one_from_file  and it works, but the problem is the speed is too slow for a high number of choices. I expected that because at xlsform.org is suggested to use select_one_external for the large number of choices. Do you think is there any other way that I can use to have good performance with a large number of choices? And if not is there any way I can customize the app to use an external web API from which the app can obtain the list of choices for certain questions?

**Comment by MartijnR** [comment]
Just be sure, the performance issue is with Enketo, right?

I think we'll be working on this in the near future. If you are able to share a form with a performance issue (simpler is better, but any form will help) with a large troublesome external document, that could be very useful for us.

**Comment by hussain1368** [comment]
Thank you. That's great, How can I share it with you?

**Comment by MartijnR** [comment]
Hi Hussain, If it is not confidential, easiest is to zip the 2 files and drag the zip file into a new response to this thread. Thanks!

If it is confidential you can email it to info@enketo.org as well.

**Comment by hussain1368** [comment]
[Kobo_Test.zip](https://github.com/enketo/enketo-core/files/4152247/Kobo_Test.zip)
Thank you

**Comment by MartijnR** [comment]
52,000 lines in csv file.

Kobo_Test on ona.io/enketo, local enketo-express:

**Comment by MartijnR** [comment]
@hussain1368, just to be sure, the issue you experienced was with initial slow loading of the form, right?

Sorry for the late response, btw!
