### ISSUE TITLE
Replace XPath evaluator

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#699]
Replace with this one: https://github.com/medic/openrosa-xpath-evaluator/ (will likely move to enketo github account)

Track here:  https://github.com/medic/cht-core/issues/6196

Advantages:
- Better performance
- Better license
- Supports missing functions, e.g. digest()

**Comment by Freeedim** [comment]
Hi there!

Is there any foreseeable timeline for this?

There is a feature in it that I have been missing so bad for so long...

Cheers!

**Comment by MartijnR** [comment]
> There is a feature in it that I have been missing so bad for so long...
Are you referring to the digest() function?

> Is there any foreseeable timeline for this?
Nothing concrete, but I can tell you this is our highest priority at the moment. A [bug](https://github.com/medic/openrosa-xpath-evaluator/issues/30) needs to be fixed first.

**Comment by Freeedim** [comment]
Indeed, I can't wait for that digest function.

Thanks for the pointer. I don't understand everything in the referred conversation, but does it mean the bug with selected-count() not working with a space-separated values string will also be fixed? I would love this too as I am constantly making wonky things to workaround this problem.

**Comment by MartijnR** [comment]
@Freedim that count-selected() bug doesn't really seem worth fixing. The bug referred to is for this usage: `count-selected('a b')`. It is does not occur for `count-selected(${some-node}) where some-node has value "a b".  I cannot think of any use case for the former.

Maybe you've discovered a different bug with count-selected?

**Comment by Freeedim** [comment]
Great news! 
Thanks a lot!
