### ISSUE TITLE
Select with autocomplete appearance and choice filter shows choice value rather than label if only explicit languages set

### ISSUE THREAD

**Issue by lognaturel** [enketo/enketo-core#704]
See sample form: https://docs.google.com/spreadsheets/d/1cWmVtVyTh5PX-Cqc6IndSgnqGpSdmZXOf1N7TzEp_d8/edit#gid=0 

Notice that the choice filter doesn't work either.

If I remove `label::English (en)` on all labels, it works as expected.

(I know this is totally niche but it had me really scratching my head and I figured y'all should know in case it's an easy fix.)

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=autocomplete-cascade.xml
