### ISSUE TITLE
placement-map feature not supported with multiple languages in enketo

### ISSUE THREAD

**Issue by Kalyan-Lama** [enketo/enketo-core#713]
The `placement-map` feature does not function as it should in a xlsform with multiple languages (2 language and more). You are able to view the map in the default language (or the first language selected by the system if not set) but if you change the language to another language the map gets washed out (it becomes plain).

Map seen clearly in `Spanish` language:
![image](https://user-images.githubusercontent.com/50188479/82083090-de1a0080-9708-11ea-8c1e-e1bc638d2794.png)

Now when you change the language to `English`, the map disappears:
![image](https://user-images.githubusercontent.com/50188479/82083159-f68a1b00-9708-11ea-9a11-719a92ac05fc.png)

**Reference xlsform:**
[placement-map (multiple language).xlsx](https://github.com/enketo/enketo-express/files/4636368/placement-map.multiple.language.xlsx)

**Flowdock:** https://www.flowdock.com/app/kobotoolbox/support/threads/yg-dJJnFfVV5IxGV4BVn2qPRX4x

**Comment by MartijnR** [comment]
Reproduce with http://localhost:8005/?xform=All_widgets.xml

Cause is calling the update function of the geo widget, though it should actually rebuild the map.

* [ ] fix bug where geowidget update function doesn't rebuild the map
* [ ] look into not calling the update function for the geo widget when language changes
