### ISSUE TITLE
Rendering the index/position of a repeat group for an XLSForm with multiple language

### ISSUE THREAD

**Issue by FrankApiyo** [enketo/enketo-core#716]
There seems to be an issue rendering the index/position of a repeat group for an XLSForm with multiple languages on Enketo. The index/position of iterations on the form indexed_repeat.xlsx (attached) works fine. I edited the label columns of the XLSForm to `label::English`
[indexed_repeat.xlsx](https://github.com/enketo/enketo-express/files/4680172/indexed_repeat.xlsx)
[indexed_repeat_language.xlsx](https://github.com/enketo/enketo-express/files/4680174/indexed_repeat_language.xlsx)
<img width="684" alt="Screen Shot 2020-05-20 at 5 56 35 PM" src="https://user-images.githubusercontent.com/25260439/82865875-78abe800-9f30-11ea-8060-aa42247bc2ea.png">

 and uploaded the form as indexed_repeat_language.xlsx (also attached) and it shows/reads all the iterations as enketo/enketo-express#1; see the attached screenshot. The form indexed_repeat_language.xlsx works fine on ODK Collect

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=https://xlsform.getodk.org/downloads/zq9_c2e4/indexed_repeat_language.xml

**Comment by MartijnR** [comment]
The XForm output {pos} is different (`../pos` vs `/data/grp1/member../pos`). Might be a pyxform issue.

**Comment by MartijnR** [comment]
I'd rather not workaround this issue in Enketo and wait for a pyxform fix. We would have to disable the recent performance improvements wrt `odk:xforms-version="1.0.0"` and it would also break some possible fancy forms that are in use because we dropped the position-injection logic.

**Comment by MartijnR** [comment]
Frank, I see you are with Ona. Great. You may want to nudge @ukanga abt the pyxform issue, as he is very familiar with the relative-ref code (he wrote it) ;)
