### ISSUE TITLE
itemset issue

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#717]
Reported here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/enketo-users/7LKKwRmAUrI/pTgzRK28BAAJ by Patrick Delcroix

> if the filter is in a group that is hidden when the filter condition is set (another variable outside the group), then when the group is displayed  enketo is not taking current value of the variable used in the filter.

[test_FILTER.xlsx](https://github.com/enketo/enketo-core/files/4684787/test_FILTER.xlsx)

**Comment by MartijnR** [comment]
Looks like itemset.update is flawed when called with updated.relevantPath, because it does not find itemset nodes with ancestor that have that path.

**Comment by MartijnR** [comment]
similar to https://github.com/enketo/enketo-core/issues/592

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=test_FILTER.xml

**Comment by MartijnR** [comment]
* [ ] fix issue
* [ ] add tests
* [ ] fix similar issue with static shared itemsets inside repeats

**Comment by pbowen-oc** [comment]
@MartijnR - Is this fix specific to the newer version of Pyxform? It seemed to work on our Deb server with a newer version of Pyxform in use. However, since we are not deploying the newer version of Pyxform right now, we are testing with our existing older version and it is not working. The selection items all display no choices if I attempt to filter them.

[itemset-relevant.old-pyxform.xml.txt](https://github.com/enketo/enketo-core/files/5052997/itemset-relevant.old-pyxform.xml.txt)

**Comment by MartijnR** [comment]
I think this was not related to pyxform. 

* [ ] check if original issue is fixed

**Comment by MartijnR** [comment]
Looks like indeed related to pyxform:

Paul's XForm has:

```xml
<itemset nodeset="instance('state')/root/item[starts-with(label,  /itemset-relevant.pab/start )]">
        <value ref="name" />
        <label ref="jr:itext(itextId)" />
</itemset>
```

Note that `starts-with()` looks at a `instance('state')/root/item/label node but that node doesn't exist. Itext is used instead.

So the XForm output should probably be:

#### A

```xml
<itemset nodeset="instance('state')/root/item[starts-with(jr:itext(itextId),  /itemset-relevant.pab/start )]">
        <value ref="name" />
        <label ref="jr:itext(itextId)" />
</itemset>
```
However, this would also not work in Enketo since Enketo has not implement itext() as an XPath function. It should though. Related to https://github.com/enketo/enketo-core/issues/532, https://github.com/enketo/enketo-core/issues/32, https://github.com/enketo/enketo-transformer/issues/66, https://github.com/enketo/enketo-transformer/issues/68

#### B (no itext, since form contains no translations

```xml
<-- changed structure of instance 'state' without using itext -->

<itemset nodeset="instance('state')/root/item[starts-with(label,  /itemset-relevant.pab/start )]">
        <value ref="name" />
        <label ref="label" />
</itemset>
```

* [ ] file pyxform issue
* [ ] close this issue
* [ ] possibly work on making itext() an xpath function

**Comment by MartijnR** [comment]
@pbowen-oc, it was an issue with the old pyxform which has been fixed. The issue would remain for translated forms, if the label is used in conjunction with `starts-with()` (or any other function) which actually seems quite unlikely for translated forms. The solution to that is to change the formula using in the form `starts-with(jr:itext(label), ${start})` and properly add `itext()` handling to Enketo.

In most cases, it would probably be better to use the `name` (value) instead, so `starts-with(name, ${start})`. That makes your form work (also with the old pyxform).
