### ISSUE TITLE
Editing records within a repeat group

### ISSUE THREAD

**Issue by Janemesi** [enketo/enketo-core#720]
We are encountering an issue with relevant conditions when editing records on Enketo that are within nested repeat groups. An error message is thrown when one has submitted information for more than 2 iterations on each repeat group. 

For instance, on the sample form shared the error message is being thrown when one submits information for more than 2 buildings and on each building, one submits information for more than 2 rooms. We have tested the same form on KoBo and we were able to replicate the issue. Any recommendations or ideas that you may have regarding resolving this issue will be highly appreciated.

The attached screenshot displays the thrown error message. 
<img width="933" alt="er1" src="https://user-images.githubusercontent.com/36330603/83870196-7e76aa00-a736-11ea-9975-30c3b87f9c05.png">
[SchoolSurveyTestingFOrm2.xlsx](https://github.com/enketo/enketo-express/files/4735683/SchoolSurveyTestingFOrm2.xlsx)

**Comment by FrankApiyo** [comment]
Hey, @MartijnR, I'm interested in working on this. I've been able to set up enketo locally and replicate the issue. I may reach out when I need some guidance.

**Comment by FrankApiyo** [comment]
Although it seems I can't really `git push` to this repo, I already have some changes that I'd like to get your opinion on.

Please let me know if there is anything I need to do in order to be able to push code here. Thank.

**Comment by MartijnR** [comment]
That's great @FrankApiyo! I've invited you to Enketo Collaborators, so I think you can push into a "fix/" branch now. Otherwise, you can also fork and send a PR. Thanks!
