### ISSUE TITLE
Textarea disabled after condition is meet

### ISSUE THREAD

**Issue by dbianco** [enketo/enketo-core#726]
If you have a text type with appareance multiline (which is rendered in html as textarea) that will be shown after a condition is meet in a previous questions, once the condition is meet, the textarea is visible, but disabled, so the user is not able to type any text on it.
I saw this issue in the grid theme

**Comment by MartijnR** [comment]
https://docs.google.com/spreadsheets/d/1nKxah8soR0Aq3vlcGMqYTd_uDxMRFqcQDOnFnC8ogrE/edit?usp=sharing

**Comment by MartijnR** [comment]
@dbianco, I am having trouble reproducing this with the form above. Could you perhaps post a form to reproduce the issue with (as small as possible)?

**Comment by dbianco** [comment]
Sorry, I tested with the xls that you created and works fine, closing the bug
