### ISSUE TITLE
pulldata() not accepting search strings of a certain format

### ISSUE THREAD

**Issue by vituslehner** [enketo/enketo-core#727]
**Describe the bug**
When pulling data from a CSV using `pulldata()`, certain search string values will throw an error. In this particular case, e.g. the value `12E345` will throw the following error, while `12A345` is doing fine. The hypothesis is that the former value gets recognized as science-notation exponential float and the `pulldata()` function does not seem to expect this case. 

Error:
```
FormLogicError: Could not evaluate: /model/instance[@id="BugDemoSourceIds"]/root/item[source_id = 12E345]/source_name, message: The expression is not a legal expression. (line: undefined, character: undefined)
```

Note that values like `12XE345`, `12E`, `E345`, `12.345`, `12`, would all work fine, too. So far, only the exponential-style values are causing a problem. Capitalization does not matter.

**To Reproduce**
Find attached files for reproducing the issue. For ease of the demo, the values can be prefilled using a URL query parameter.
1. Upload the XForm together with the CSV file as a media attachment.
2. Open the form and attach the query parameter: d[source_id]=12A345 (this should show an A in the form - fine)
3. Open the form and attach the query parameter: d[source_id]=12E345 (this will throw the above error)

**Expected behavior**
The third step should not throw an error, but instead pull data from the CSV and show an E in the form.

**Enketo version**
2.3.4

Let me know if you need further information or if this is an easy fix.

**Comment by MartijnR** [comment]
fixed by https://github.com/enketo/enketo-core/commit/d6c503d1e201ee00e033584fc93e1be15efaad52

**Comment by MartijnR** [comment]
@vituslehner if you happen to be able to test the latests enketo-express master with the fix, this would be much appreciated.

**Comment by vituslehner** [comment]
Hi Martijn, thanks for your quick reaction! As you declared this closed, did you already test it yourself in the meantime?

**Comment by neurolabs** [comment]
@vituslehner Here's the commit with the change, containing a test case for the issue: https://github.com/enketo/enketo-core/commit/d6c503d1e201ee00e033584fc93e1be15efaad52

**Comment by MartijnR** [comment]
Hi @vituslehner, 

Actual testing with a form is still welcome (but yes, I'm quite confident it is fixed). Just reopen if you find an issue. Thanks!
