### ISSUE TITLE
indexed-repeat enketo-express issue (repeated inside a repeated group) Cannot read property 'querySelectorAll' of null

### ISSUE THREAD

**Issue by Red1to2** [enketo/enketo-core#734]
**Describe the bug**
The form do not respond to the numbers of repeats inside another repeated group correctly using indexed-repeat function when the repeat number is 1.

**To Reproduce**

When the numbers of repeats is filled by 1 inside the second repeat.
The numbers of repeats is not recognized, and the repeat group do not show!

**Expected behavior**
Repeat the group 1 time.

**Screenshots**
System error log:

enketo-webform-bundle.min.js:35 Uncaught TypeError: Cannot read property 'querySelectorAll' of null
at Object.getInfoIndex (enketo-webform-bundle.min.js:35)
at Object.updateRepeatInstancesFromCount (enketo-webform-bundle.min.js:35)
at Array.forEach ()
at Object.countUpdate (enketo-webform-bundle.min.js:35)
at Boolean. (enketo-webform-bundle.min.js:92)
at Array.forEach ()
at HTMLDivElement. (enketo-webform-bundle.min.js:92)
at hi.setVal (enketo-webform-bundle.min.js:35)
at Object._updateCalc (enketo-webform-bundle.min.js:92)
at enketo-webform-bundle.min.js:92
getInfoIndex @ enketo-webform-bundle.min.js:35
updateRepeatInstancesFromCount @ enketo-webform-bundle.min.js:35
countUpdate @ enketo-webform-bundle.min.js:35
(anonymous) @ enketo-webform-bundle.min.js:92
(anonymous) @ enketo-webform-bundle.min.js:92
hi.setVal @ enketo-webform-bundle.min.js:35
_updateCalc @ enketo-webform-bundle.min.js:92
(anonymous) @ enketo-webform-bundle.min.js:92
update @ enketo-webform-bundle.min.js:92
(anonymous) @ enketo-webform-bundle.min.js:92
(anonymous) @ enketo-webform-bundle.min.js:92
hi.setVal @ enketo-webform-bundle.min.js:35
_updateCalc @ enketo-webform-bundle.min.js:92
(anonymous) @ enketo-webform-bundle.min.js:92
update @ enketo-webform-bundle.min.js:92
(anonymous) @ enketo-webform-bundle.min.js:92
(anonymous) @ enketo-webform-bundle.min.js:92
hi.setVal @ enketo-webform-bundle.min.js:35
(anonymous) @ enketo-webform-bundle.min.js:92
dispatch @ enketo-webform-bundle.min.js:33
m.handle @ enketo-webform-bundle.min.js:33
**Browser and OS (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
[Sample Form](https://gofile.io/d/sGU4qs)

**Comment by Red1to2** [comment]
@MartijnR  Yes actually, still the same error on https://getodk.org/xlsform/. 

Thanks in advance.

**Comment by MartijnR** [comment]
Thanks @Red1to2!

If you have a minimal test form to reproduce it with, I'll have a look. Creating such a form is probably 90% of the work required to fix this.

**Comment by Red1to2** [comment]
@MartijnR  I updated the post with a mini form uploaded on GoFile at the [Link](https://gofile.io/d/49ZmgH).

Thanks again

**Comment by MartijnR** [comment]
Thanks!

Looks like the repeat count is not evaluated properly for the nested repeat. Not sure if anything is wrong with indexed-repeat.

* [ ] fix repeat-count evaluation
* [ ] check if anything goes wrong with indexed-repeat()

**Comment by MartijnR** [comment]
@Red1to2, this is pretty complex. It makes me remember why I think we shouldn't support nested repeats at all. I don't think we'll have a fix anytime soon. I'm not quite sure what is broken here.

Fwiw, I was wondering why you are using the `Number_of_Family_Members_index` calculation at all instead of pointing `repeat_count` directly to `${Number_of_Family_Members}` (and similar with the relevant formula). It's not clear to me what indexed-repeat() is calculating here. It's always `Number_of_Family_Members` of the current repeat, right? If so, please don't use it. It makes things unnecessarily complex.

* I think there is an issue in pyxform as well with the output for nested repeats (seems the template includes an instance too many). 
* I think there may also be an issue with evaluating relevant for nested repeats in Enketo.

**Comment by Red1to2** [comment]
@MartijnR  Thanks for your respond. I removed all the indexed-repeat() calculation and still get the same error. Just adding any repeat inside a repeat will produce the same issue.

And the issue is gone when you increase the numbers of repeats >1 then decrease it again to 1!!!

**Comment by MartijnR** [comment]
Focusing just on the exception:

1. http://localhost:8005/?xform=mini_form.xml
2. fill in 1 for top-level repeat
3. fill in 1 for nested repeat

Issue appears to be with the cache maintained by Form.getRelatedNodes. Forcing that cache to rebuild avoids it.

**Comment by MartijnR** [comment]
Finally figured it out @Red1to2. Thanks much for your help. It will be added to the next release of Enketo Express.

Pinging #728 (@nanzhang01) and #720 (@FrankApiyo), because it is possible this fix had an effect on those issues too.

**Comment by Red1to2** [comment]
@MartijnR Thanks a lot for your support. Tested @localhost working like a charm.

**Comment by MartijnR** [comment]
Great. Thanks a lot for testing this @AmjadRabadi!
