### ISSUE TITLE
screen reader support

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#735]
from https://community.kobotoolbox.org/t/accessibility-standards-for-visually-disabilities/10885

When filling out the form using a screen reader programme:

* The voice-over reads content that is not actually visible on the page. I assume the programme reads something from the code of the page, including content from other pages. The voice-over should read only the content that is visible on the page.
* When moving to the next page, screen reader by default goes to the bottom of a page. It is very inconvenient when a user with visual impairment must manually search and find the beginning of a page. When clicking “next”, it should take you to the next question by default.

**Comment by MartijnR** [comment]
* [ ] add attribute/class to invisible pages that tells screenreader to skip it
* [ ] automatically focus on first question on page after page flip

**Comment by FrankApiyo** [comment]
I'll like to work on this
