### ISSUE TITLE
TypeError when loading form with jr:choice-name for select from secondary instance and default answer

### ISSUE THREAD

**Issue by lognaturel** [enketo/enketo-core#738]
**To Reproduce**
Load a form with a `jr:choice-name` call on a select from secondary instance with a default answer such as https://docs.google.com/spreadsheets/d/1gYdi9BtC3VxsIY_1DjNKL1ikXSu1RdMeS1_im96F-Vo/edit#gid=0

**Expected behavior**
No load error

**Additional context**
Introduced by https://github.com/enketo/enketo-core/commit/7cd49a8796bbe1546a432fddbb36557ae96ec376. @kkrawczyk123 saw this during Central regression testing when we updated Enketo to 2.3.10

[choice-name-enketo.xml.zip](https://github.com/enketo/enketo-express/files/5092866/choice-name-enketo.xml.zip) gives a slightly different error and I haven't investigated why yet.

CC @matthew-white

**Comment by MartijnR** [comment]
possibly fixed by https://github.com/enketo/enketo-core/pull/762. still to check

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=jr-choice-name-external.xml
