### ISSUE TITLE
Support up to w13 (or w12) in Grid Theme 

### ISSUE THREAD

**Issue by Kalyan-Lama** [enketo/enketo-core#742]
**Describe the bug**

While creating a matrix question, users are able to have a maximum column of 10 but when they try to have more then 10 columns the matrix question gets visually distorted.

**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).
1. Upload this xlsform with `w10` and test it with KoBoToolbox. 
[matrix_Working.xlsx](https://github.com/enketo/enketo-express/files/5169827/matrix_Working.xlsx)
It has `10 columns` for a matrix question and does not have any visualization issue. As a reference please see the image as shown below:
![Image 1](https://user-images.githubusercontent.com/50188479/92139944-33049280-ee30-11ea-8bf0-5f8ece864479.png)

2. Now upload this xlsform with `w11` and test it with KoBoToolbox.
[matrix_Error.xlsx](https://github.com/enketo/enketo-express/files/5169838/matrix_Error.xlsx)
It has `11 columns` for a matrix question and the table gets distorted. As a reference please see the image as shown below:
![Image 2](https://user-images.githubusercontent.com/50188479/92140271-9a224700-ee30-11ea-836d-4c09342730ca.png)

**Expected behavior**

Users are able to create a survey form for a matrix question with more than 10 columns without the tables being distorted.

**Browser and OS (please complete the following information):**
 - OS: Windows
 - Browser [e.g. chrome]

**Additional context**

`Community Forum Link:` https://community.kobotoolbox.org/t/unable-to-include-14-columns-in-a-matrix-question/12037

**Comment by nanometrenat** [comment]
From this user's perspective, 12 (or more) columns would be magnificent so we can collect Sex and Age Disaggregated Data via matrix in Grid Theme.

This allows  allow for 10 age brackets, plus Other, plus M/F/O row labels.

At the moment we have a workaround that looks OK for the enumerator but makes the data structure underneath very difficult to analyse!

Thanks a lot

**Comment by nanometrenat** [comment]
Hi there, any thoughts on when this might be able to be picked up and looked at (I am happy to test but sadly can't contribute code...)  It would be great to be able to follow the Sphere standards for disaggregated data, and have the 12 columns available please :)  Thanks a lot!

**Comment by lognaturel** [comment]
Sounds like you use Enketo through KoBo? Would be great to see if someone from their team can pick this up.

**Comment by joshuaberetta** [comment]
@lognaturel, @nanometrenat here's how things turn out once we start heading over the current 10 column maximum:

<img width="1057" alt="10 col" src="https://user-images.githubusercontent.com/50016008/120396586-a66a0080-c2eb-11eb-8109-2d11b0d3fce8.png">

<img width="1071" alt="12 col" src="https://user-images.githubusercontent.com/50016008/120396597-ae29a500-c2eb-11eb-8c39-6342bc98509f.png">

<img width="1079" alt="13 col" src="https://user-images.githubusercontent.com/50016008/120396622-bc77c100-c2eb-11eb-8d06-fff33319cf1d.png">

There's barely a noticeable difference between 12 and 13 columns but the styling doesn't look great. I wonder if introducing a horizontal scroll once a certain column number is reached will make this look better? I'm not sure if that will be confusing for enumerators to have some columns hidden from view?

**Comment by joshuaberetta** [comment]
> 13 is principled -- it's 12 months plus a column for row headings

Agreed.

> I think it'd be best to have a true form spec for tables and introduce things like vertical or slanted column headings

This sounds like a good way forward. So should we put a hold on the increase to 13 until a new spec has been introduced?

**Comment by lognaturel** [comment]
I'm sorry, I meant beyond 13! I think 13 is defensible and there's a very clear-cut usecase for it that is straightforward to make look good.

**Comment by nanometrenat** [comment]
Thanks @joshuaberetta for picking this up!  Will make a big difference to us.

> I wonder if introducing a horizontal scroll once a certain column number is reached will make this look better? I'm not sure if that will be confusing for enumerators to have some columns hidden from view?
As grid-theme was explicitly designed to have a similar feel to paper forms, I don't think a scroll bar is a good idea.  Also would cause problems when printing (and given how many people have raised questions/queries around printing/pdfing recently I think we should keep the 'like paper' focus.

The original example given above (with full dates and times as column headings) doesn't in my view represent the main use case.  * If it's age brackets that go by the Sphere standards e.g. 6-12, 40-49, 80+ etc. then they are short and also could easily split across 2-3 lines without any adverse readibility
* if it's months of the year then they could easily be abbreviated also

Whilst it would be great to have a full spec I don't think it's a dependency for extending Grid Theme to support w13 :)

Thanks again

**Comment by joshuaberetta** [comment]
@nanometrenat thanks for adding context 🙌
