### ISSUE TITLE
Safari: Date-time calculations appear to include UTC offsets

### ISSUE THREAD

**Issue by nanzhang01** [enketo/enketo-core#745]
**Describe the bug**
When a datetime question has a calculation, the result appears to be adjusted by the UTC offset.

**Sample xls form**
[date-time.calc.has.utc.offset.xlsx](https://github.com/enketo/enketo-core/files/5358618/date-time.calc.has.utc.offset.xlsx)
 
**Screenshots**
Calculation `now() + 0` produces a result +8 hours in China Standard Time.
Chrome:
![Screen Shot 2020-10-10 at 3 56 50 PM](https://user-images.githubusercontent.com/29697780/95649766-c5741200-0b11-11eb-9af7-21e77c1aada9.png)

Safari on MacOS:
<img width="608" alt="Screen Shot 2020-10-10 at 3 55 58 PM" src="https://user-images.githubusercontent.com/29697780/95649768-cc028980-0b11-11eb-883e-19f8cb89b86c.png">

 
**Browser and OS (please complete the following information):**
 - Only Safari on macOS can reproduce this issue and other browsers work as expected.

**Comment by nanzhang01** [comment]
@MartijnR, The returned calculation result is correct from xpathJS, the key is: the native Date constructor returns different values between Safari and other browsers. I would like to create a PR to fix this.

**Comment by MartijnR** [comment]
Thanks for reporting, and yes please create a PR 👍
