### ISSUE TITLE
Accidental support for unsupported HTML tags

### ISSUE THREAD

**Issue by nanzhang01** [enketo/enketo-core#750]
**Describe the bug**
If use html tags in choice label of dropdown questions, the tag itself will be displayed, instead of rendered text.
Sample xls form: [issue html in dropdown choice label.xlsx](https://github.com/enketo/enketo-core/files/5620622/issue.html.in.dropdown.choice.label.xlsx)

**Screenshots**  
![00_bug_screenshot1](https://user-images.githubusercontent.com/29697780/100704396-6c717d80-33e0-11eb-8089-840b929b9edf.gif)

xls form:
![image](https://user-images.githubusercontent.com/29697780/100704273-2fa58680-33e0-11eb-85e4-c1c4c3107ffc.png)
![image](https://user-images.githubusercontent.com/29697780/100704296-3cc27580-33e0-11eb-9a9f-c0722675e83b.png)

**Expected behavior**
HTML tag in selected choice label renders correctly for dropdown qustion, like this: 
![image](https://user-images.githubusercontent.com/29697780/100704532-a17dd000-33e0-11eb-981c-fc2d7fba92ea.png)

**Additional context**
The html tag in the dropdown option rendered correctly.

**Comment by nanzhang01** [comment]
It seems that this issue is a regression since the change from https://github.com/enketo/enketo-core/commit/36244d2927dc986e694c2298c6610de0bc7fdfec#diff-07bdf3586144615e3d6a6b2e07995c79374fea7568c9046d737e4902ec698b69R149.

**Comment by MartijnR** [comment]
Thanks @nanzhang01. The bug is actually that it displays bold, italic in the dropdown. We don't support any HTML other than what is mentioned here: https://xlsform.org/en/#styling-prompts


* [  ] remove accidental support for `<b>` and `<i>`

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=issue.html.in.dropdown.choice.label.xml
