### ISSUE TITLE
Form instance name starts with spatial characters or numbers leads to error if it contains autocomplete choice question.

### ISSUE THREAD

**Issue by nanzhang01** [enketo/enketo-core#752]
**Describe the bug**
Form root id starts with spatial characters or numbers leads to error if it contains autocomplete choice question.

**To Reproduce** 
1. unpack this zip file: [00_test_bugs.zip](https://github.com/enketo/enketo-core/files/5621760/00_test_bugs.zip), and create survey with the inside xform:  the root instance name is `_00_bug_test`.
2. load the form in enketo-core and oberserve, an alert will pop up, it shows messages like: `Failed to execute 'querySelector' on 'Document': 'xxxxx' is not a valid selector.` 

**Screenshots** 
xform: 
![image](https://user-images.githubusercontent.com/29697780/100727271-f92c3380-3400-11eb-808b-6f14a70e0852.png)

alert in enekto-core:
![image](https://user-images.githubusercontent.com/29697780/100727351-0f39f400-3401-11eb-9d88-f348643775a8.png)

**Additional context**
Although the generated instance name in webform is a fixed name(`data`) from enketo-transformer, but according to the  ODK XForms specification, the instance name can start with spatial characters or numbers, so this issue maybe happen on the system with is based on enketo but has some customized change.

**Comment by nanzhang01** [comment]
The autocomplete widget calls "this.question.querySelectorAll( datalist#${listId} > option ) ]" to get all the choice options, but if the listId starts with number or spatial characters, this codes will through error. The id need to be escaped.

The correct way is:
"this.question.querySelectorAll( datalist[id="${listId}"] > option ) ]"
or:
"this.question.querySelectorAll( datalist#${CSS.escape(listId)} > option ) ]" 

The same codes exist in image-map.js and form.js.

**Comment by MartijnR** [comment]
Nice one! Thank you!
