### ISSUE TITLE
Unable to proceed further when users delete a repeat from a repeat group question

### ISSUE THREAD

**Issue by Kalyan-Lama** [enketo/enketo-core#755]
**Describe the bug**
Users are unable to proceed further when they delete a repeat from a repeat group question while collecting data with Enketo.

**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).
1. Upload and deploy this sample xlsform that has a repeat group question.
[Repeat Groups.xlsx](https://github.com/enketo/enketo-express/files/5664730/Repeat.Groups.xlsx)
2. Make at least 3 repeats.
3. Once you have at least 3 repeats try to delete the last repeat (as shown in the image below):
![Image 101](https://user-images.githubusercontent.com/50188479/101609571-38750880-3a2f-11eb-911b-fe1b8aa8a335.png)
4. Everything seems to be OK till this phase but once you press `Submit` (if you are in the `KoBoToolbox server` or in this **[validation link](https://getodk.org/xlsform/)** you should see the following that never stops:
![Image 102](https://user-images.githubusercontent.com/50188479/101609750-75d99600-3a2f-11eb-8f8a-09be8d73bc18.png)

**Expected behavior**
The page should not hang as shown in the image above.

**Browser and OS (please complete the following information):**
 - OS: `Windows 10`
 - Browser: `Chrome`

**Additional context**
This happens only when you have a repeat more than (or equals to) three. A repeat with 2 does not have this issue.

For details, you could follow the community discussion **[here](https://community.kobotoolbox.org/t/deleting-the-entries-from-roster/14361/4)**.

**Comment by MartijnR** [comment]
Confirmed that an exception occurs after removing third repeat.

**Comment by lognaturel** [comment]
@MartijnR From the diff it looks like this only affected user-initiated deletes? So no chance of it being related to https://forum.getodk.org/t/hanging-enketo-submission-to-central/31347/3?

**Comment by MartijnR** [comment]
I think it would affect deleting repeats in general, so also triggered from count updates. To be honest, I didn't go very deep with this fix...
