### ISSUE TITLE
Allow to specify hint text for choice options

### ISSUE THREAD

**Issue by nmandrescu** [enketo/enketo-core#765]
**Is your feature request related to a problem? Please describe.**

Sometime choice options need an extra clarification to the end users. We would like to keep the option text short, and add a longer text that clarifies the option meaning. Unfortunately for now we have to define long option text to include the clarification.

**Describe the solution you'd like**

In the choice list of option, have the possibility to configure choice option hint. Please also allow the hint to contain html markup similar to the question hint.

**Describe alternatives you've considered**
Current alternative: extra text in the choice name.

**Additional context**

Question hint allows html markup. In such markup we can add custom css class to render the hint as a tooltip. For this reason it would be useful to allow html markup in choice as well. If html markup here is not possible, then please allow to configure such hints to display as tooltip.

**Comment by lognaturel** [comment]
Let's keep this tracked at the spec level since we'd want to consider it there first.
