### ISSUE TITLE
Choice with minimal appearance in matrix grid layout doesn't always fit into the page width

### ISSUE THREAD

**Issue by nmandrescu** [enketo/enketo-core#769]
**Describe the bug**
Choice with `minimal` appearance (i.e. dropdown) in some grid with matrix layout get pushed to the next row.

**To Reproduce**
Sample XLS form: 
[dropdown-sample.xlsx.zip](https://github.com/enketo/enketo-express/files/6122911/dropdown-sample.xlsx.zip)

1. As in provided sample, with 6w row width (group), of which 2w are for the question note and 4 x 1w for dropdown entries
2. Pick to show 1, 2 or 3 entries and they are all fitting within the row.
3. Pick to show 4 entries and the 4th entry is moved to the next row.

**Expected behavior**
All entries should remain on the same row no matter if 1, 2, 3 or 4 are selected to show.

**Screenshots**
When 1 entry is selected:
![one-entry](https://user-images.githubusercontent.com/17854915/110786864-50019e80-8275-11eb-8db4-4de2dd4665b6.png)
When 4 entries are selected, the last one is pushed to the next row:
![four-entries](https://user-images.githubusercontent.com/17854915/110786876-53952580-8275-11eb-8d6b-b0a5cae1777d.png)

**Browser and OS (please complete the following information):**
 - OS: Linux
 - Browsers:
   - Chrome Version 89.0.4389.82 (Official Build) (64-bit)
   - Firefox 86.0 (64-bit)
   - Opera 74.0.3911.203

**Additional context**
The solution is to explicitly configure the width. An example for the shared XForm use case:
```
@media print, screen and (min-width: 600px) {
  .or-appearance-w6 .or-appearance-w1 {
      width: calc(16.6666666667%);
  }
}
```

**Comment by MartijnR** [comment]
Thanks for posting! I think this issue is just related to the width of the screen.

<img width="1168" alt="Screen Shot 2021-03-11 at 4 39 47 PM" src="https://user-images.githubusercontent.com/627350/110869833-7da41300-8288-11eb-861f-c44cc78645d5.png">

The Grid Theme only works (as a grid) on larger screens.

**Comment by nmandrescu** [comment]
Thanks for checking! My screen is almost 24" with plenty of left and write space around the survey form in the page.

By looking at your sample I realize it's related to our custom Enketo Express theme where more padding space around the question is used. Looks like we'll need to replicate https://github.com/enketo/enketo-core/blob/master/src/sass/grid/_main.scss#L395 on our end, unless you could integrate the change within Enketo core that will work with any custom padding.

**Comment by MartijnR** [comment]
Ah ok, please mention next time that you are using a custom theme....

No, thanks for this padding PR offer.
