### ISSUE TITLE
Range value doesn't display when draft (offline) survey is loaded

### ISSUE THREAD

**Issue by nmandrescu** [enketo/enketo-core#771]
**Describe the bug**
Range value doesn't display when draft (offline) survey is loaded.

**To Reproduce**
[Range test.xlsx.zip](https://github.com/enketo/enketo-core/files/6164522/Range.test.xlsx.zip)
1. Create the form based on attached sample.
2. Open the survey in offline mode.
3. Configure some range value (e.g. 2).
4. Save as draft
5. Reopen the draft version
6. Notice the tick correctly shows the range value, but the value doesn't display.

**Expected behavior**
The range value must be displayed when form is loaded from draft.

**Screenshots**
Value displayed on first time selection (before saved as draft):
![selected](https://user-images.githubusercontent.com/17854915/111636422-23afca00-8801-11eb-8d9b-d1a7a67d0b14.png)
Value is gone if you reload the draft:
![reloaded-from-draft](https://user-images.githubusercontent.com/17854915/111636458-2dd1c880-8801-11eb-85f4-766bc079056e.png)

**Browser and OS (please complete the following information):**
 - OS: Linux
 - Browsers:
   - Chrome 89.0.4389.90 (Official Build) (64-bit)
   - Firefox 86.0.1 (64-bit)
   - Opera 74.0.3911.218

**Additional context**
1. In loaded draft version, clicking on the same value doesn't bring its display. You have to select another value (e.g. 3), and then select the initial one (e.g. 2) to see it displayed.
2. I have been using the online Kobo Toolbox that is based on official Enketo Express.
3. Here is a link for test https://ee.kobotoolbox.org/x/xCi9Grlc

**Comment by MartijnR** [comment]
Thank you!

**Comment by nmandrescu** [comment]
Please note the same issue occurs when opening the submission instance for edit.
