### ISSUE TITLE
Form with XPath lookup on 30k item external CSV locks up browser and fails to validate

### ISSUE THREAD

**Issue by lognaturel** [enketo/enketo-core#773]
**Describe the bug**
With the new XPath evaluator, forms with large secondary instances can be loaded. 🎉🎉 Forms with cascading selects with large numbers of choices work great. Lookup expressions are not instant but are satisfactorily performant. However, something in the validation process seems to fail or take prohibitively long. 

See [this public form](https://test.central.getodk.org/-/single/F28hV2Vevi0pbNVGWehpVL1UbdYEhOz?st=C4n4Z3qALZoZR98JLP!aTzDeACcpaFHmUuieCs7J48CELDPfRN0mi89ufNQGOZ4s) for an example. The same behavior is observed when clicking on "Validate" with a preview. The server is doing nothing. The client machine gets fans spinning and Chrome eventually reports that the tab is not responding.

**To Reproduce**
The form used is [person_lookup.xlsx](https://github.com/enketo/enketo-express/files/6200759/person_lookup.xlsx) with attachment [persons.csv.zip](https://github.com/enketo/enketo-express/files/6200761/persons.csv.zip).

**Expected behavior**
Fast validation and submission.

**Browser and OS (please complete the following information):**
 - OS: macOS 11.2.3
 - Browser: Version 89.0.4389.90 (Official Build) (x86_64)

No urgency around this but I wanted to file it since performance has been top of mind.

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=person_lookup.xml

**Comment by MartijnR** [comment]
Will take only a fraction of a second now. Thanks for reporting this! 😅

**Comment by lognaturel** [comment]
Hehe, seemed like the kind of thing that might be silly. Thanks for the quick, satisfying fix!

Out of curiosity, is there something special (e.g. pre-computation of filtered lists) that happens in the case of cascading selects? I'd expect the filter expressions to take a little bit to evaluate just like the lookup but getting the filtered lists feels instant. Or maybe it's that the lookup form does two passes through the item list for (redundant) id and name lookups?

**Comment by MartijnR** [comment]
>  is there something special (e.g. pre-computation of filtered lists) that happens in the case of cascading selects?

No, nothing fancy happening. Are you seeing unexpected cascading selects speed in another form? It should be significantly slower than a calculation as in this form (even if the calculation is done twice, I think).

There is some caching of cascading selects but that only plays a role after a query has been performed once (for similar lists e.g. in repeat instances).

**Comment by lognaturel** [comment]
> Are you seeing unexpected cascading selects speed in another form?

Yes, see how brilliantly [this form](https://test.central.getodk.org/-/single/jrULueZyiLS88VNjONUKsb3OW0XQgf8?st=ZHNv0NGl1zrdSQ0ob9003gtjRYmhyeeqElo$LOCnMee56At4amGZeDbws6OnW41x) performs! There are ~52k settlements: [source](https://drive.google.com/drive/u/0/folders/1QwX7E-u19jzXvzwkOpj2Y4X-xb9ihd1f).

**Comment by MartijnR** [comment]
Oh wow, that is impressive. It is just an accident, I think! Or maybe @alxndrsn performed some additional magic with his XPath evaluator by adding secret predictive AI capabilities. It should slow down again in the near future when I change a line of code somewhere. 🤣 

Enjoy it while it lasts!

**Comment by lognaturel** [comment]
Hah! We do some quick informal benchmarking before upgrading Enketo in Central so don't expect to get away with too much. 😉
