### ISSUE TITLE
Support npm 7

### ISSUE THREAD

**Issue by magicznyleszek** [enketo/enketo-core#786]
**Describe the bug**
Project doesn't work with `npm CLI` version `7.x`.

**To Reproduce**
1. Use `npm` version 7
2. run `npm install`
3. observe errors due to `enketo-transform`'s `libxslt` dependency

**Browser and OS (please complete the following information):**
 - OS: MacOS

**Comment by lognaturel** [comment]
https://github.com/enketo/enketo-transformer/issues/98 is the root issue. https://github.com/enketo/enketo-express/issues/240 is the analog on `enketo-express`. It's also related to #767.

The likely next steps are to either take over maintenance of `libxslt`

**Comment by lognaturel** [comment]
I haven't yet, @fsmanuel

**Comment by lognaturel** [comment]
I tried to do an `npm audit` during a brownout for [TLS 1.0 and 1.1 deprecation](https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/). I thought I might need to upgrade from npm 6 to address it but it looks like I was able to just change my registry setting:

``
npm set registry=https://registry.npmjs.org/
```

**Comment by lognaturel** [comment]
Fixed in libxslt
