### ISSUE TITLE
Removal of test coverage badge from README.md

### ISSUE THREAD

**Issue by eyelidlessness** [enketo/enketo-core#801]
When faster builds with ESBuild was introduced in #797, this also removed test coverage reporting instrumentation, causing code coverage to be reported as 100% (#795). While it may be possible to reintroduce that functionality, it would negate much of the performance benefits of the build tooling change. And while test coverage itself is great, these metrics are not always very useful in determining the quality of coverage, or the level of risk where coverage is low.

The root cause was discovered in the course of work on #798, wherein upgrades also caused generating the badge itself to fail. In discussion with @lognaturel we concluded that the badge likely doesn't provide enough value to justify blocking other important changes. A similar change is pending in enketo/enketo-express#298, and a similar issue will be opened there. I'm opening this issue to make this change known more visibly and to get an idea whether there's a major objection to the change.

**Comment by lognaturel** [comment]
It's been gone for a while and no one seems to mind. We can run with coverage locally and we carefully review tests as part of code review.
