### ISSUE TITLE
Name collision with calculate in repeat causes error

### ISSUE THREAD

**Issue by jkuester** [enketo/enketo-core#815]
**Describe the bug**
This is a bit of an edge case, but we are seeing an issue where an error is thrown if you have a `calculate` field in a sub-group within a `repeat` and the `calculate` has the _same name_ as a prior question in the `repeat` (but the question is not in the same sub-group as the `calculate`).  When a form is setup like this, the error gets thrown if there is _more than one_ entry in the repeat.

Error Log:

```
form-model.js:1239 no context element found /data/outside_group/test_repeat/inner_group/text_in_repeat -1
FormModel.evaluate @ form-model.js:1239
form-model.js:1318 Uncaught FormLogicErrormessage: "Could not evaluate: /model/instance[1]/data/outside_group/repeat_count, message: Failed to execute 'evaluate' on 'XPathEvaluator': parameter 2 is not of type 'Node'."name: "FormLogicError"stack: "Error\n    at new FormLogicError (https://enketo.getodk.org/js/build/enketo-webform.js:47547:18)\n    at FormModel.evaluate (https://enketo.getodk.org/js/build/enketo-webform.js:48699:15)\n    at Object._updateCalc (https://enketo.getodk.org/js/build/enketo-webform.js:56597:59)\n    at https://enketo.getodk.org/js/build/enketo-webform.js:56505:18\n    at Array.forEach (<anonymous>)\n    at Object.update (https://enketo.getodk.org/js/build/enketo-webform.js:56488:13)\n    at https://enketo.getodk.org/js/build/enketo-webform.js:57175:12\n    at Array.forEach (<anonymous>)\n    at HTMLFormElement.<anonymous> (https://enketo.getodk.org/js/build/enketo-webform.js:57174:30)\n    at Object.add (https://enketo.getodk.org/js/build/enketo-webform.js:49372:15)"[[Prototype]]: Error
```

**To Reproduce**

1. Open [this xForm](https://docs.google.com/spreadsheets/d/1cCXefohzrcGmiKTXBaOS5xPOl3W9ORN5/edit?usp=sharing&ouid=110810027707570331679&rtpof=true&sd=true)
1. Enter `2` (or any value > 1) for the "How many times to repeat" question
1. See the error in the browser console

One definite side-effect that we have noticed is that this error affects the `note` widgets within the `repeat` and causes the notes in subsequent repeat entries (all but the first) to also display a read-only text box.  You can see in the screenshot that in the second entry of the repeat, the note, "This is a repeated note" is actually displayed as a read-only text question.

![image](https://user-images.githubusercontent.com/8441903/133801493-54e9833c-2504-4110-b858-4687e1044dfa.png)

**Expected behavior**

Since the two fields with the same name are not in the same group (and so actually have distinct paths) I expected this to work without an error.  

One practical use case that could result in this name collision is found in the [default `delivery` form](https://github.com/medic/cht-core/blob/master/config/default/forms/app/delivery.xlsx) in cht-core. This form has several questions within a repeat and then uses calculates within a sub-group in the repeat to massage the data from the questions. However, the calculates in the sub-group just have the same names as the questions.

This seems to be an issue in how the index is getting caluculated to pick which data node to update: https://github.com/enketo/enketo-core/blob/4347aa79485db1bc281d867ecc7a6d3294ede149/src/js/calculate.js#L61
That line of code is simply grabbing the first child element of the repeat entry that has the `dataNodeName` and then using that element to determine the actual index to use: https://github.com/enketo/enketo-core/blob/4347aa79485db1bc281d867ecc7a6d3294ede149/src/js/calculate.js#L62
The problem is that with the name collision, the element selected as the `dataNode` is not the calculate (but is instead the text question with the same name).  This causes `props.index` to be set to `-1` which, in turn, eventually triggers the error seen in the logs.

Updating the code for selecting the `dataNode` to the following solved the issue for me:

```.js
const childNodeList = this.form.model.node( updated.repeatPath, updated.repeatIndex ).getElement().querySelectorAll( dataNodeName );
const dataNode = Array.from(childNodeList).filter( node => dataNodes.includes( node ) )[0];
```

Let me know if this explanation/analysis makes sense and if the proposed solution is acceptable.  I would be happy to submit this in a PR.  Thank you!

**Browser and OS (please complete the following information):**
 - OS: Linux Mint 20.2
 - Browser: Brave 1.29.79 Chromium: 93.0.4577.63

**Comment by MartijnR** [comment]
I think this is a bug in Enketo. Though Enketo doesn't like it, those same names should be supported (see warning in https://validate.enketo.org).

Would you welcome a PR for this @eyelidlessness, @lognaturel, @yanokwa?
