### ISSUE TITLE
loading a record with a meta block in the http://openrosa.org/xforms namespace, fails to properly create and populate a deprecatedID node

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#835]
https://github.com/XLSForm/pyxform/issues/105#issuecomment-959796769

* [x] add tests if they do not exist - found one [here](https://github.com/enketo/enketo-core/blob/master/test/spec/form.spec.js#L108)

http://localhost:8005/?xform=meta-namespace.xml

**Comment by MartijnR** [comment]
Thanks! 

I am able to reproduce it with http://localhost:8005/?xform=meta-namespace.xml and ` instanceStr: '<data xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" id="meta-namespace">\n          <a>ert</a>\n          <b/>\n          <orx:meta>\n              <orx:instanceID>uuid:d5708aa1-2db4-47f6-a98a-bf7962a73905</orx:instanceID>\n              <orx:timeStart>2021-11-03T16:30:30.165-04:00</orx:timeStart>\n              <orx:timeEnd>2021-11-03T16:30:30.166-04:00</orx:timeEnd>\n              <orx:deviceID>localhost:KOGktYtzKR4oqudH</orx:deviceID>\n              <orx:userID/>\n          </orx:meta>\n        </data>'`

This results in:
```xml
 instanceStr: '<data xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" id="meta-namespace">\n          <a>ert</a>\n          <b/>\n          <orx:meta>\n              <orx:instanceID>uuid:d5708aa1-2db4-47f6-a98a-bf7962a73905</orx:instanceID>\n              <orx:timeStart>2021-11-03T16:30:30.165-04:00</orx:timeStart>\n              <orx:timeEnd>2021-11-03T16:30:30.166-04:00</orx:timeEnd>\n              <orx:deviceID>localhost:KOGktYtzKR4oqudH</orx:deviceID>\n              <orx:userID/>\n          </orx:meta>\n        </data>'
``` 

The `deprecatedID` is created but not populated (1st issue), and not in the correct namespace (2nd issue).

**Comment by vituslehner** [comment]
Hi, I think I'm having a similar issue with submissions that were exported from ODK Aggregate via Briefcase. Those submissions get a `n0:` namespace for meta data which causes submission editing to fail when imported into ODK Central and loaded for editing in Enketo.

![grafik](https://user-images.githubusercontent.com/10120310/147076496-a50ebac6-2460-4e29-addc-2b5c55c04610.png)

The error is: `Error: Could not load input field value with name: /data/n0:meta/n0:instanceID and value: uuid:xxxxx`

![grafik](https://user-images.githubusercontent.com/10120310/147076660-92ec887e-a9f7-443b-8e45-9b669a60aabe.png)

When I remove the `n0:` prefixes, it's working fine.

**Comment by MartijnR** [comment]
Yes, `n0` refer to the same namespace so this should be the same issue. The PR (#836) was approved.
