### ISSUE TITLE
Apply Skip Logic to Enketo Form Printouts and PDF Files

### ISSUE THREAD

**Issue by eochieng-lab** [enketo/enketo-core#848]
When a user wants to print out a form or save it as a PDF, they open the form on Enketo and click the printer icon. If the form has the skip logic applied to any questions, all the questions in the form will appear in the printout or pdf file despite this. The questions to be skipped appear greyed out while the rest appear in a bolder darker colour. For example, the form below loads as shown.
![image](https://user-images.githubusercontent.com/77043654/146909777-cefd9758-3f7b-436a-9549-684b453fa29e.png)

Question 2 is hidden and is only visible when a user selects Yes or No to question 1.

However, when a user selects the printer icon, question 2 will appear in the printout even when no selection has been made on question 1 as shown below.
![image](https://user-images.githubusercontent.com/77043654/146909840-b8564cb0-b04e-40b7-b0ef-1866650757a6.png)

Is there a way to ensure that the skip logic applies to questions in the printouts or PDF files?

**Comment by eochieng-lab** [comment]
@enketo-issue-mover , kindly requesting support on this issue.

**Comment by MartijnR** [comment]
thanks @eochieng-lab. 

With Enketo Express, when loading an existing already-submitted record for viewing or editing via the API (e.g. by clicking on a button in KoBoToolbox, I'm not sure which other servers support it), it will only print the relevant parts.

Does that help you?

**Comment by eochieng-lab** [comment]
@MartijnR , thanks for the feedback. Just to give a bit more context...

The user seems to understand on the skip logic bit. However, her form appears to have overlapping questions when she tries to print. Please have a look at the below screenshot:
![image](https://user-images.githubusercontent.com/77043654/150332961-743ba9f8-4dec-405d-847d-8116c3e2fe59.png)

Attached is the XLSForm. Not sure whether it's a bug causing this. I looked at the XLSForm and noticed there are `appearance` attributes added to the questions where there is an overlap. Could this be the cause and if yes, is this normal?

**Comment by MartijnR** [comment]
Created a new issue #854
