### ISSUE TITLE
form_logo is not displaying in Enketo 3.0.4

### ISSUE THREAD

**Issue by yanokwa** [enketo/enketo-core#850]
In Central v1.2.2 (Enketo 2.7.3), when you add a form_logo.png file to a form, it shows up centered and small at the top of the form
<img width="1140" alt="Screen Shot 2022-01-05 at 15 38 20" src="https://user-images.githubusercontent.com/32369/148306833-9ae605d4-87ff-41db-86bf-257b254ac873.png">

In Central v1.3.3 (Enketo 3.0.4), when you add a form_logo.png file to a form, the small logo is not there.
<img width="1131" alt="Screen Shot 2022-01-05 at 15 53 21" src="https://user-images.githubusercontent.com/32369/148306862-c3a5b4c5-4dc3-410b-b7ae-3e87cec86c88.png">

The form_logo feature is a bit of a [magic](https://github.com/getodk/xforms-spec/issues/34) thing so it's not necessarily bad that it's gone, but we should be more explicit about these things. Anyway, it's a regression so we should fix it.

Form source: [form_logo_test.zip](https://github.com/enketo/enketo-core/files/7818483/form_logo_test.zip)

**Comment by lognaturel** [comment]
@eyelidlessness since we're working towards a point release I think it’d be good to take a quick look and see whether there might be a straightforward fix.

**Comment by eyelidlessness** [comment]
Found the issue! I'll have a PR open shortly.
