### ISSUE TITLE
Unable to randomize choices with `randomize=true`

### ISSUE THREAD

**Issue by joshuaberetta** [enketo/enketo-core#853]
**Describe the bug**
Choices cannot be randomized with the parameter `randomize=true`.

**To Reproduce**

**survey**

| type               | name | label  | parameters             |
| ---                | ---  | ---    | ---                    |
| select_one numbers | num  | Number | randomize=true |

**choices**

| list_name | name | label |
| ---       | ---  | ---   |
| numbers   | 1    | One   |
| numbers   | 2    | Two   |
| numbers   | 3    | Three |
| numbers   | 4    | Four  |
| numbers   | 5    | Five  |

Result:

<img width="651" alt="enketo" src="https://user-images.githubusercontent.com/50016008/149838146-f23e6e01-3d11-40ff-b91c-6b2f600e0347.png">

**Expected behavior**
Same behaviour as Collect: choices are randomized.

<img width="333" alt="collect" src="https://user-images.githubusercontent.com/50016008/149838178-ec6445f8-71da-4ef6-a111-27619a8b9f0f.png">

**Additional context**
Report in KoBo community forum: https://community.kobotoolbox.org/t/seed-and-randomize-whats-that-preventing-to-deploy-my-form/4739/12

**Comment by lognaturel** [comment]
You’re running the latest version with https://github.com/enketo/enketo-core/pull/822?

**Comment by joshuaberetta** [comment]
Aha, we're not — still on 2.8.1 👌
