### ISSUE TITLE
printing issue with select_one minimal

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#854]
@MartijnR , thanks for the feedback. Just to give a bit more context...

The user seems to understand on the skip logic bit. However, her form appears to have overlapping questions when she tries to print. Please have a look at the below screenshot:
![image](https://user-images.githubusercontent.com/77043654/150332961-743ba9f8-4dec-405d-847d-8116c3e2fe59.png)

Attached is the XLSForm. Not sure whether it's a bug causing this. I looked at the XLSForm and noticed there are `appearance` attributes added to the questions where there is an overlap. Could this be the cause and if yes, is this normal? Or is it related to our Enketo version?

[cash_assurance_monitoring_RBC_v2_0_3.xls](https://github.com/enketo/enketo-core/files/7904829/cash_assurance_monitoring_RBC_v2_0_3.xls)

_Originally posted by @eochieng-lab in https://github.com/enketo/enketo-core/issues/848#issuecomment-1017418047_

**Comment by MartijnR** [comment]
@eochieng-lab could you please let us know if you're seeing this in the latest version of Enketo Express?

**Comment by eochieng-lab** [comment]
@MartijnR , currently on version 2.7.3

**Comment by eochieng-lab** [comment]
@MartijnR , would it be safe to say that the version we are using is the issue? We've been trying to take a look at Enketo change logs and it doesn't explicitly mention whether the new versions would resolve the issue.

**Comment by MartijnR** [comment]
I believe this usually has the cutting-edge version, so you could check: https://getodk.org/xlsform/

**Comment by eochieng-lab** [comment]
Thanks @MartijnR , we intend to upgrade the enketo version on our staging site to test this. Once I have feedback, I will let you know whether we can close the issue.
