### ISSUE TITLE
sum() expression inside a repeat only counts the number in the very repeat instance and does count for numbers in sibling repeat instances.

### ISSUE THREAD

**Issue by nanzhang01** [enketo/enketo-core#872]
**Describe the bug** 
`sum()` inside a repeat only counts the number in the very repeat instance and does count for numbers in sibling repeat instances.
 
**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).
1.  Publish xls form: [00test-sum test.xlsx](https://github.com/enketo/enketo-core/files/8220658/00test-sum.test.xlsx).
2. Type 1 in the `num1` Field.
3. Click the ‘+’ symbol to add another repeat instance.
4. Type 1 in the `num1` Field in the new repeat instance.
4. Repeat steps 3 and 4.
 
**Screenshots**
xls form:
<img width="1194" alt="Screen Shot 2022-03-10 at 1 40 41 PM" src="https://user-images.githubusercontent.com/29697780/157597100-2b573d09-7266-450c-8704-cbd7c4a6b5dc.png">

![enketo xml(1)](https://user-images.githubusercontent.com/29697780/157600175-5282b824-d20d-424a-8cbe-5ba525167200.jpg)

**Expected behavior**
 No matter the sum() (or count()) inside or outside a repeat, all instances of the result updated automatically everywhere.
like this: 

![Untitled1112](https://user-images.githubusercontent.com/29697780/157598828-b0ba13c2-426f-46b1-8f6e-5c82927bb398.gif)

**Browser and OS (please complete the following information):**

**Additional context**

**Comment by MartijnR** [comment]
I think this is a pyxform feature. ${num1} should be transformed into `../num1` and `/data/repeat/num1` respectively, in the XForm. In this case, it looks like Enketo is evaluating the expressions correctly. Please close once you confirm.

**Comment by lognaturel** [comment]
See https://github.com/XLSForm/pyxform/issues/525#issuecomment-816303610
