### ISSUE TITLE
Questions outside of repeat with randomize=true cannot work if questions inside of repeat with randomize=true exist.

### ISSUE THREAD

**Issue by nanzhang01** [enketo/enketo-core#874]
**Describe the bug**
Questions outside of repeat with randomize=true cannot work if questions inside of repeat with randomize=true exist.

**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).

1. Publish survey with this xls form: [randomized in repeat.xlsx](https://github.com/enketo/enketo-core/files/8348592/randomized.in.repeat.xlsx), there are two choice quesetions, one in in repeat(named rating), the other(named fruits) is outside the repeat,  both of the choide questions are randomized, publish the survey.
2. Add a repeat, observe that the choice order of `select fruits` question are changed.

**Expected behavior**
The choice order outside the repeat don't changed after adding new repeat instance.

**Screenshots**
xls form:
<img width="922" alt="Screen Shot 2022-03-25 at 4 05 55 PM" src="https://user-images.githubusercontent.com/29697780/160079919-883d0b12-02bb-4525-a8e6-6691f4df31ae.png">

screenshot:
![bug_record](https://user-images.githubusercontent.com/29697780/160080883-f63cab53-943b-4880-8cd5-0bb79d13ad8e.gif)

**Browser and OS (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by MartijnR** [comment]
oh dear... 

Thanks for reporting. Fwiw, I think the cause can be found somewhere in itemset.js.

**Comment by eyelidlessness** [comment]
I've tracked this down to `Form#getRelatedNodes` [here](https://github.com/enketo/enketo-core/blob/51c5c2f/src/js/form.js#L683). I've explored a couple of approaches to solving this, none of which I'm particularly fond of but they do work. I don't have time today to write up a test and wrap up a solution, but should be able to get a PR open next week.
