### ISSUE TITLE
Unexpected warning when form has nested `meta` group

### ISSUE THREAD

**Issue by jkuester** [enketo/enketo-core#890]
**Describe the bug**

Forms in [the CHT](https://github.com/medic/cht-core) often include a nested sub-group named `meta`. I have noticed that when these forms are opened in the browser, [a warning](https://github.com/enketo/enketo-core/blob/5e1ec1bf1746664825cc4391b711596eeb205995/src/js/nodeset.js#L160) is logged:

```
Data node: /*/meta/deprecatedID with null-based index: undefined not found. Ignored.
```

**To Reproduce**

Simply init a form that has a nested group named `meta` without explicitly specifying the `deprecatedID` as a part of the model's metadata.

type | name | label::en
-- | -- | --
begin_group | text_widgets | Text widgets
begin_group |  meta | Meta Group
text | text | Text widget
end group | |  
end_group |   |  

**Expected behavior**

The expected behavior is that we do not have the warning (and the `deprecatedID` processing completes normally). It appears that the source of the problem is that when the form model is being initialized, it [creates a node for `deprecatedID`](https://github.com/enketo/enketo-core/blob/5e1ec1bf1746664825cc4391b711596eeb205995/src/js/form-model.js#L663) if one does not already exist.  However, if there are multiple `meta` groups in a form, the first element found by `this.xml.querySelector('* > meta');` might not be the top-level `meta` group for the instance (but could be a sub-group).  This causes the node for `deprecatedID` to be appended at the wrong place and then the call further down to `this.getMetaNode( 'deprecatedID' ).setVal( instanceIdExistingVal );` fails with the previously noted warning since the meta node returned by `this.getMetaNode( 'deprecatedID' )` does not actually have a `deprecatedID` child.

Now there are a couple complicating factors from the CHT that I would like to acknowledge:

When I tested a sample form out on https://getodk.org/xlsform/ I received the error `Error: There are two sections with the name meta.` (even though my `meta` group was nested and not at the top level). This leads me to think that at least at some level of the Enketo ecosystem, groups named `meta` are not supported (outside of the top level group [reserved for specifying metadata for the completed form](https://docs.getodk.org/openrosa-metadata/#completed-form-metadata)...).  So, I guess my first question is if anyone can point me to some documentation regarding this (have not been able to find anything explicit). I see quite a bit [in the spec](https://getodk.github.io/xforms-spec/#metadata) regarding the main `meta` block, but so far have not found anything that says you cannot have any other groups named `meta`.  It would be very helpful to know if the CHT is out-of-spec by allowing these groups! (Or even just if we are exposed to additional potential problems from Enketo by allowing these groups...)

Also, it is worth noting that currently the CHT does not make use of the `deprecatedID`. (We have separate logic for handling revisions to reports.) So, we are not seeing any kind of adverse behavior from this warning (at least none that we know of...). But it seemed worth raising this issue to get some additional context/thoughts here so we can understand if this could be a problem going forwards.

For what it is worth, I _think_ all that would be required to fix this processing would be to modify the selector used here: https://github.com/enketo/enketo-core/blob/5e1ec1bf1746664825cc4391b711596eeb205995/src/js/form-model.js#L663

I think just changing it to be `instance > * > meta` would prevent it from finding the nested meta groups. Let me know if this seems like a reasonable change and I am happy to raise a PR!

**Browser and OS:**

-   OS: Linux Mint 20.3
-   Browser: Chromium 101.0.4951.64
-   enketo-core: 5.18.1 (have been mainly testing with this version, but the code in question remains unchanged as of version 6.0.5)

**Comment by eyelidlessness** [comment]
Hi @jkuester, I looked at this earlier but forgot to come back to it. I think the query you suggest is correct. We'd certainly welcome a PR, thank you!
