### ISSUE TITLE
FomLogicError thrown on relevance on field without a control element in a repeat

### ISSUE THREAD

**Issue by KipSigei** [enketo/enketo-core#908]
A form with cascade repeats throws the following error:

`FormLogicError: Could not evaluate: not(selected( ../uccmake ,'UccMakeOther')), message: Failed to execute 'evaluate' on 'XPathEvaluator': parameter 2 is not of type 'Node'.`

The issue is caused by a mismatch in the index of a cloned repeat node. When a repeat node is added or removed the `repeatIndex` doesn't seem to sync correctly with the `repeat-number` DOM element.

**Comment by lognaturel** [comment]
Is "cascade repeat" a nested repeat?

**Comment by lognaturel** [comment]
Thanks so much for the quick report and follow up, @KipSigei! In general, please include a form definition if you can. It's unlikely we'll be able to troubleshoot any kind of error without one.

I've confirmed this is the same pattern reported by @aurdipas which led to #907. I confirmed the fix works with this form by changing all `pulldata` calls to `a` ([UCC_Inventory_V1.xlsx](https://github.com/enketo/enketo-core/files/8930888/UCC_Inventory_V1.xlsx)) and running it through the test from #907 on `master` and with the fix.

@KipSigei we should have a fix out by Weds of next week.
