### ISSUE TITLE
Problem with preinstall script on windows

### ISSUE THREAD

**Issue by hussain1368** [enketo/enketo-core#912]
There is a problem with preinstall script on windows:
`"preinstall": "test -f ./node_modules && ./scripts/preinstall || true"`
Can you please change this script to something windows friendly?

**Comment by yanokwa** [comment]
Suggest an alternative and send in a PR

**Comment by hussain1368** [comment]
Actually, I am not really sure what would be the alternative. but if you can just make it work with windows? Or maybe just remove that preinstall script. Here is the error for your information:
```
Command: test -f ./node_modules && .\scripts\preinstall || true
Arguments:
Directory: D:\MyDTM\Apps\DQMv2\DQM\webpack\node_modules\enketo-core
Output:
'test' is not recognized as an internal or external command,
operable program or batch file.
'true' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by lognaturel** [comment]
Closing in favor of #855
