### ISSUE TITLE
Progress bar not working properly on ENKETO webform

### ISSUE THREAD

**Issue by elysd** [enketo/enketo-core#915]
Hello,

I need some help please. I am building a survey via KoboToolbox but using the online-offline submission for web form/ ENKETO. The progress bar fills in progressively but only for the first questions. After the first set of questions the bar is full, indicating as if there is no more questions, which is not the case. Any idea why? the first questions do not have skip logic. The remainder of the questions, where the progress bar shows as complete, all include skip logic. Any tips?

Thanks

**Comment by lognaturel** [comment]
There are likely issues with your relevant expressions. This repo is for organizing work on Enketo Core. You can get support at https://community.kobotoolbox.org/!
