### ISSUE TITLE
Namespace-prefixed attribute above /h:html/h:head/model/instance/* breaks model bindings referencing that namespace

### ISSUE THREAD

**Issue by eyelidlessness** [enketo/enketo-core#923]
**Describe the bug**

When an XForm specifies a namespaced-prefixed attribute on the `<model>` element, that namespace is not resolved in model bindings.

**To Reproduce**

1. Access a form with
  - a namespace declared on the form's root element;
  - a namespace-prefixed attribute on `<model>`;
  - a model binding referencing that namespace.
2. Note that the namespace-referencing binding will error.

**Expected behavior**

Namespaces referenced anywhere in a form will be handled as declared.

**Additional context**

The root cause as I've been able to determine it:

1. By default, enketo-transformer places `xmlns:*` attributes on the primary instance's first child element. But if a namespace prefix is used higher in the document hierarchy, the `xmlns:*` attribute is instead placed on that node.
2. In enketo-core, namespace mapping is determined _only_ by `xmlns:*` attributes on the primary instance's first child.

It seems unlikely this is solvable without changes in both projects. My inclination:

- _Always_ place `xmlns:*` attributes on the `<model>` element
- Replace the logic [manually building a namespace mapping](https://github.com/enketo/enketo-core/blob/27a8f5ffd4ab9e531ead4cb18b8066c259edf1bf/src/js/form-model.js#L1145) with the native [`createNSResolver`](https://developer.mozilla.org/en-US/docs/Web/API/Document/createNSResolver)

**Comment by lognaturel** [comment]
How is `odk:xforms-version` handled? Is it a special case? Is it done in a reasonable way that could be replicated?

**Comment by lognaturel** [comment]
Well, I guess the interesting thing with `entities:entities-version` is that Enketo can ignore it since it's not going to be building entities itself so if the underlying issue were fixed the attribute wouldn't have to be known by Enketo. Ok, maybe that is the better approach. @eyelidlessness did you maybe already have a spike we could look at? Any risk performance-wise or would it still only consider namespaces defined at the top level?

**Comment by lognaturel** [comment]
This is related to some broader discussion about how namespaces are used in the ODK XForms spec: https://github.com/XLSForm/pyxform/issues/105#issuecomment-1297787840

Interestingly, there's only a crash related to a namespaced attribute on `model` if that namespace is used in bind `nodeset` expressions. So this issue does not affect our current desired usage as far as I can tell.

**Comment by lognaturel** [comment]
Closing because we don't have a user-facing reason to fix this currently.
