### ISSUE TITLE
Signature and draw widget are considered to have a value after it has been emptied/reset

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#924]
**Describe the bug**
When adding a signature and then removing it, it is considered to have a value after 2 successive validations

**To Reproduce**
Steps to reproduce the behavior. 

1. Open [sig_widget.xml.txt](https://github.com/enketo/enketo-core/files/9923121/sig_widget.xml.txt) in enketo-core
2. Add a signature
3. Reset the signature widget
4. Click Validate and confirm correct 'required' validation error
5. Click Validate again and see that the 'required' validation error is no longer there

**Expected behavior**
For an emptied signature widget to be considered empty until a new signature is drawn.

**Additional context**
I'll do some further investigation and will edit/update this issue.

(P.S. the delay in signature widget populating is also a little odd because of validation errors appearing and disappearing with a delay but haven't heard complaints about this yet.)

**Comment by lognaturel** [comment]
Maybe some relationship with https://github.com/enketo/enketo-express/issues/339?

**Comment by MartijnR** [comment]
Notes (to self mostly):

### cause: canvas blur event handler firing after validation

* The canvas automatically gets focus if it's the first invalid question on the form. 
* The widget is not able to make a distinction between an empty canvas and an edited canvas and presumably returns the empty image as dataUrl. 
* You can reproduce the bug without validation too by using the keyboard to toggle focus/blur on a previously-cleared canvas.

### fixes:

1. Adding a (or using an already-added) mechanism to make the widget aware of whether the user added any strokes and if not, return an empty value (which is an empty string I believe).

**Comment by lognaturel** [comment]
Closed by #931
