### ISSUE TITLE
Support minimal appearence on repeat question.

### ISSUE THREAD

**Issue by nanzhang01** [enketo/enketo-core#925]
**Describe the bug**
Minimal appearence on repeat question is not working, there is still a default repeat instance existing when form loaded.

**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).

Sample xls form:  [minimal repeats.xlsx](https://github.com/enketo/enketo-core/files/10055022/minimal.repeats.xlsx)

**Expected behavior**
The minimal repeat should display none instance by default.

**Screenshots**
<img width="1069" alt="Screen Shot 2022-11-21 at 5 16 56 PM" src="https://user-images.githubusercontent.com/29697780/203012071-70f1e5d5-fba2-40b5-b918-ab2524d5b902.png">
<img width="703" alt="Screen Shot 2022-11-21 at 5 13 25 PM" src="https://user-images.githubusercontent.com/29697780/203011741-3db0e28f-36c1-4154-bb9f-74e519965d13.png">

**Browser and OS (please complete the following information):**

-   OS: [e.g. iOS]

-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by lognaturel** [comment]
As far as I know, this appearance for repeats is not documented anywhere in the ODK XForms or XLSForm specs. It also looks like there weren't any tests for it. Are you sure it was an intentional feature? What's the use case for it? Is it for non-linear flows through a form or something else?

**Comment by nanzhang01** [comment]
I've always thought that appearance for repeats is included in the XLSForm spec and it's supported by enketo , but now I realize it's not.

The use case of setting minimal appearence on repeat is like that: for survey author, by setting the appearance of a begin repeat question to minimal, a repeatable collection of questions is not visible on startup. The user must click the add button to see the questions in the repeat. This is useful when repeated questions don't need to be completed in a survey.  

Author can setting the repeat_count as 0 to show empty repeat on startup, but the user will have no chance to add new repeat instance .

@lognaturel, If survey authors want to have this feature, is there any workaround existing for them to take? 
If there is no workaround, although this feature is not in the odk or XLSForm spec, is it posibile for enekto to support this feature as a enhancement? Thanks!

**Comment by lognaturel** [comment]
The relevance approach from the docs above is generally a good one. It does require having a condition to check on but typically it does make the user experience clearer as well.
