### ISSUE TITLE
Nested repeats with repeat_count are broken

### ISSUE THREAD

**Issue by joshuaberetta** [enketo/enketo-core#934]
**Describe the bug**
A nested repeat group using `repeat_count` does not repeat the inner group's questions after the first outer instance.

**To Reproduce**

**survey**

| type         | name         | label        | repeat_count | calculation  |
| ---          | ---          | ---          | ---          | ---          |
| begin_repeat | outer_repeat | Outer Repeat | 2            |              |
| calculate    | p1           |              |              | position(..) |
| text         | q1           | Q${p1}       |              |              |
| begin_repeat | inner_repeat | Inner Repeat | 2            |              |
| calculate    | p2           |              |              | position(..) |
| integer      | q2           | Q${p1}.${p2} |              |              |
| end_repeat   |              |              |              |              |
| end_repeat   |              |              |              |              |

[nested-repeat-count.xlsx](https://github.com/enketo/enketo-express/files/10200303/nested-repeat-count.xlsx)

**Expected behavior**

The inner group questions are repeated in all outer group instances.

**Screenshots**
 
Expected behavior observed in EE `3.0.5`
<img width="626" alt="3 0 5" src="https://user-images.githubusercontent.com/50016008/206861266-4b8117af-33bf-4ce9-87ac-572f08150c25.png">

Broken behavior in EE `5.0.0`:

<img width="619" alt="5 0 0" src="https://user-images.githubusercontent.com/50016008/206861278-f6248d9a-6950-46ad-a03c-c972cd9e2cb8.png">

**Browser and OS (please complete the following information):**

- OS: macOS
- Browser: Firefox

**Additional context**
Issue present since at least EE `4.1.1`.

**Comment by lognaturel** [comment]
@eyelidlessness has linked this to the big performance improvement from https://github.com/enketo/enketo-core/pull/887 released with [Core 6.1.0](https://github.com/enketo/enketo-core/releases/tag/6.1.0) and [Express 4.0.0](https://github.com/enketo/enketo-express/releases/tag/4.0.0).

**Comment by jnm** [comment]
Thank you @lognaturel and @eyelidlessness. I've gotten the old behavior back for now by reverting 1d8313900e3bc1ab86eb87b7cf9155cbe566af80.
