### ISSUE TITLE
Remove Analog Scale widget?

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#950]
The analog scale widget was developed for a particular clinical trial use case (for OpenClinica). It has to rigidly look a particular way in a particular form to be certified for certain trials. I think my rationale for putting it in Enketo Core (long ago) was that others could perhaps benefit from it.

However, likely nobody outside OpenClinica knows about it. It was never added to the default widgets configuration in Enketo Express either (and not to ODK Collect).

It might be more efficient for OpenClinica to add/move this widget to their fork of Enketo Express and continue working on it there. 

Would anybody have any objections to removing this widget from Enketo Core (to avoid confusion)? Or is anybody excited about this potential code cleanup?

**Comment by lognaturel** [comment]
I think it makes sense to maintain separately!
