### ISSUE TITLE
npm start no longer works 

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#955]
**Describe the bug**
Some missing enketo-transformer dependencies (vite, vite-plugin-node, and others) when running `npm start`. 

**To Reproduce**

1. run `npm start` on a clean install

**Browser and OS (please complete the following information):**

node 14.20.1, npm 6.14.17

**Other info**
`npm install` and `npm test` run fine

Not sure if this would need to be fixed here or in enketo-transformer.

**Comment by roemhildtg** [comment]
I'm seeing the same issue. I was having issues installing with npm actually (i had 9.x installed) and after downgrading to 6, it was able to install.

**Comment by eyelidlessness** [comment]
This was fixed in transformer 2.3.0 and f92ac93.
