### ISSUE TITLE
Add a guide for configuring enketo core via the docker image

### ISSUE THREAD

**Issue by roemhildtg** [enketo/enketo-core#965]
**Is your feature request related to a problem? Please describe.**

I'm interested in documenting a configuration guide for enketo core so that users of the docker image would be able to modify/override certain properties in the enketo core frontend. For example, I would like to change the value for `textMaxChars`. 

**Describe the solution you'd like**

I could work on documenting this feature in the markdown folder. 

**Additional context**

I just need a quick guide as to how the process works to configure enketo core via the docker image, then I can get started in writing a markdown file for this. I've tried troubleshooting where that config gets stored but haven't had any luck so far. 

Thanks!

**Comment by lognaturel** [comment]
Hi! Can you please provide some context as to how you're using Enketo? Are you really just using Core? If so, what Docker image are you referencing? What application are you wrapping it with?

If you're referring to the Enketo Express Docker image published at https://github.com/enketo/enketo-express/pkgs/container/enketo-express, you can find a tutorial for configuring EE at https://enketo.github.io/enketo-express/tutorial-10-configure.html. That's linked from the README under "technical documentation". I believe the config key you're looking for is `text field character limit`.

**Comment by lognaturel** [comment]
> contained core at some level

That's correct but most customization points for Core are exposed from Express. The fact that they're separate is an implementation for most users of Express. The separation exists for folks who want to wrap Core with their own services.

**Comment by roemhildtg** [comment]
This is resolved for me, thanks again!
